# -*- coding: utf-8 -*-
class CategoryTransform
  def remove_sub_dups(list)
    list.delete_if do |sub|
      list.find { |s| (s.length > sub.length) && (s[0...(sub.size)] == sub) }
    end
  end

  def apply_rules(pd)
    pd.supplier_categories.each do |cat|
      @source_categories << cat
    end

    remove_sub_dups(pd.supplier_categories)
    pd.categories = []
    @rules.each do |rule, category|
      if res = rule.call(pd, category)
        pd.categories = (pd.categories + res).uniq
      end
    end

    # Remove parent categories after all rules to work correct with exclude
    remove_sub_dups(pd['categories'])

    if Rails.env.production?
      pd.categories = [['Other']] if pd.categories.empty?
    else
      pd.categories += pd.categories.collect { |cat| ['YBySupplier', @supplier] + cat }

      unused_categories = (pd.supplier_categories - @used_categories.to_a).collect { |cat| cat.collect { |s| s.gsub('/', 'slash') } }
      unused_categories << ['AAA'] if pd.categories.empty?
      unless unused_categories.uniq.empty?
        pd.categories += unused_categories.collect { |cat| ['XUnOrganized', @supplier] + cat }
      end

      pd.categories += (pd.supplier_categories - unused_categories).collect { |cat| ['ZSuppliers', @supplier] + cat }
    end
  end

  attr_reader :supplier
  def initialize(supplier)
    @supplier = supplier
    @rules = []
    @used_categories = Set.new
    @source_categories = Set.new
    process_category(data, [])
  end

  def rules_count
    @rules.length
  end

  def status
    defunct_categories = (@used_categories - @source_categories).to_a.sort
    unless defunct_categories.empty?
      puts "Defunct Categories:"
      defunct_categories.each do |cat|
        puts "  #{cat.join('/')}"
      end
    end
  end

private
  def process_category(records, parent_category)
    records.each do |name, rules, sub_records|
      category = parent_category + [name]
      [rules].flatten.compact.each { |r| @rules << [r, category] }
      process_category(sub_records, category) if sub_records
    end
  end

  def sup(name, *rules)
    return nil unless name == @supplier
    rules.flatten.compact
  end

  def cat(*cat)
    Proc.new do |record, match_category|
      @used_categories << cat # In proc to acount for supplier hiding
      [match_category] if record['supplier_categories'].find { |c| c[0...cat.length] == cat }
    end
  end

  def always(exclude = nil)
    Proc.new do |record, match_category|
      if exclude
        [match_category[0..(-1-exclude)]]
      else
        [match_category]
      end
    end
  end

  def match(properties, values, exclude = nil)
    properties = [properties].flatten
    values = [values].flatten.collect { |v| v.is_a?(String) ? v.downcase : v }
    Proc.new do |record, match_category|
      if exclude
        if exclude.is_a?(Integer)
          cat = match_category[0..(-1-exclude)]
        else
          cat = exclude
        end
        next nil unless record.categories.find { |cs| cs[0...(cat.length)] == cat }
      end
#      puts "Match #{match_category.inspect} : #{properties.inspect} : #{values.inspect}"
      match = properties.find do |property|
        if record[property]
          val = record[property]
        else
          list = record.variants.collect { |v| v[property] || (v.properties[property]) }.compact.uniq
          next if list.empty?
          val = list.join(' ')
        end
        res = values.find do |v|
          if v.is_a?(String)
            val.downcase.include?(v)
          else
            v === val
          end
        end
#        puts " \- #{property}: #{val.inspect} => #{res}"
        res
      end
      match ? [match_category] : nil
    end
  end

  def exclude(elements)
    Proc.new do |record, match_category|
      [elements].flatten.compact.each do |elem|
        if elem.call(record, match_category)
          record.categories.delete_if { |cat| cat == match_category }
        end
      end
      nil
    end
  end

  def duplicate(src, field = 'categories')
    Proc.new do |record, match_category|
      ret = record[field].collect { |cat| (cat[0...(src.length)] == src) ? (match_category + cat[src.size..-1]) : nil }.compact
      next nil if ret.empty?
      ret
    end
  end

  def dup(*src)
    [src.last, [duplicate(src)]]
  end

  def all(*list)
    list = list.flatten.compact
    Proc.new do |record, match_category|
      result = nil
      list.find do |proc|
        not (result = proc.call(record, match_category))
      end
      result
    end
  end

  def data
[
  ['Apparel',
  [sup('Ash City', cat('Catalog', 'NESPORT')), # Kludge for 68627,
   sup('Ash City', cat('NEW STYLES'), cat('NEW Styles'))
  ],[
     ['Hats & Caps',
      [match('name', /(?:^| )hat(?:$| |\/)/),
       exclude(match('name', ['stress', 'keychain', 'hat clip'])),
       sup('High Caliber Line', cat('Headwear', 'Regular') ),
       sup('Norwood',
           cat('OUTDOOR', 'HEADWEAR'),
           all(cat('GOLF'),
               match('name', 'cap') ) ),
       sup('Ash City',
           match('name', 'cap'),
           all(cat('Team Wear'),
               match('name', 'cap'))),
       sup('Hit Promotional Products', cat('Headwear') ),
       sup('Sweda', cat('Headwear') ),
       sup('Prime Line', cat('Headwear | Caps') ),
      ],[
         ['Visors',
          [match('name', 'visor', 1),
           sup('Ash City', match('name', 'visor')) ] ],
         ['Knit Caps',
          [match('name', 'knit', 1) ] ],
        ] ],
     ['Team Wear',
      [sup('Ash City', cat('Team Wear') ) ] ],
     ['Talls',
      [sup('Ash City', cat('Talls') ) ] ],
     ['ECO Collection',
      [sup('Ash City', cat('e.c.o Collection') ) ] ],
     ['Outerwear',
      [sup('Ash City',
           cat('Outerwear'),
           match('name', 'jacket') ) ],
      %w(Windvests Windshirts Insulated\ Seam-Sealed Teflon Soft\ Shells Leather Insulated Seam-Sealed Reversible\ Jackets Reversible\ Vests Workwear).collect do |name|
        [name, [sup('Ash City', match('name', name.gsub(/s$/,''), 1))]]
      end + 
      [
       ['Performance Jackets',
        [sup('Ash City',
             all(match('name', 'jacket', 1),
                 match(%w(name material), 'performance', 1) ) ) ] ],
       ['Techno series',
        [sup('Ash City',
             match('description', 'EZAWAY', 1) ) ] ],
      ] ],
     ['Soft Shell',
      [sup('Ash City', cat('Soft Shells') ) ],
      [
       ['Performance Jackets',
        [sup('Ash City',
             all(match('name', 'jacket', 1),
                 match(%w(name material), 'performance', 1) ) ) ] ],
       ['Performance Vests',
        [sup('Ash City',
             all(match('name', 'vest', 1),
                 match(%w(name material), 'performance', 1) ) ) ] ],
      ] ],
     
     ['Fleece',
      [sup('Ash City', cat('Fleece') ),
       match('name', 'fleece')],
      %w(Vests Microfleece Vintage).collect do |name|
        [name, [sup('Ash City', match('name', name.gsub(/s$/,''), 1))]]
      end + 
      [
       ['Microfleece',
        [sup('Ash City',
             match(%w(name material description), 'microfleece', 1) ) ] ],
       ['Poly fleece',
        [sup('Ash City',
             match(%w(name material description), 'polyester', 1) ) ] ],
       ['Interactive Fleece',
        [sup('Ash City',
             match('name', 'interactive', 1) ) ] ],
       ['Cotton/Poly Fleece',
        [sup('Ash City',
             all(match(%w(name material description), 'cotton', 1),
                 match(%w(name material description), 'polyester', 1) ) ) ] ],
       ['Bonded Fleece',
        [sup('Ash City',
             match('name', 'bonded', 1) ) ] ],
      ] ],
     ['Knits',
      [sup('Ash City',
           cat('Knits'),
           match('name', 'polo') ) ],
      %w(Jersey Pique Teflon Edry Textured Eperformance Jacquard Mercerized Interlock Micro\ pima).collect do |name|
        [name, [sup('Ash City', match(%w(name material description), name, 1))]]
      end + 
      [
      ] ],
     ['Wovens',
      [sup('Ash City',
           cat('Wovens') ), ],
      %w(Easy\ care Primalux Twill Teflon Stretch Cotton Denim Service Vintage Wrinkle\ Free Wrinkle\ Resistant).collect do |name|
        [name, [sup('Ash City', match(%w(name material description), name, 1))]]
      end + 
      [
       ['Silk blend',
        [sup('Ash City',
             match(%w(name material description), 'silk', 1) ) ] ],
      ] ],
     ['Active Wear',
      [sup('Ash City', cat('Active Wear') ) ],
      [
      ] ],
     ['Pants',
      [match('name', 'pants', 1)]],
     ['Safety',
      [match('name', 'safety vest'),
       sup('Ash City', cat('Safety') ),
       sup('High Caliber Line',
           all(cat('Safety Items'),
               match('name', %w(vest shirt)) ) ) ],
      [
      ] ],
    ] ],
 ['Awards',
  [
  ],[
     ['Acrylics',
      [sup('Norwood', cat('AWARD', 'ACRYLIC') ) ] ],
     ['Art Glass',
      [sup('Norwood', cat('AWARD', 'ART') ),
       sup('Logomark', cat('Crystal Awards') ),
       sup('The Magnet Group', cat('Crystal', 'Art Glass') )
      ] ],
     ['Awards & Plaques',
      [match('name', 'trophy'),
       sup('Norwood', cat('AWARD', 'AWARDS') ),
       sup('Leeds',
           cat('Awards & Recognition', 'Awards'),
           cat('Awards & Recognition', 'Awards & Recognition')),
       sup('Logomark',
           cat('Crystal Awards'),
           cat('Metal and Wood Awards') ),
       sup('The Magnet Group', cat('Crystal', 'Optically Perfect Awards') )
      ],[ 
         ['Dichroic Awards',
          [match(%w(name description), 'dichroic', 1),
           sup('The Magnet Group', cat('Crystal', 'Dichroic Awards') )
          ]],
         ['Star Awards',
          [match('name', 'star', 1),
           sup('The Magnet Group', cat('Crystal', 'Optically Perfect Award Stars') )
          ]],
         ['Globe Awards',
          [match('name', 'globe', 1),
           sup('The Magnet Group', cat('Crystal', 'Optically Perfect Award Globes') )
          ]],
         ['Glass Awards',
          [match(%w(name description material), 'glass', 1),
           sup('The Magnet Group', cat('Crystal', 'Glass Awards') )
          ]],
         ['Jade Glass Awards',
          [match(%w(name description material), 'glass', 1),
           sup('The Magnet Group', cat('Crystal', 'Jade Glass') )
          ]],
         ['Wood Awards',
          [match(%w(name description material), 'wood', 1),
           sup('The Magnet Group', cat('Crystal', 'Wood and Glass Awards') )
          ]],
        ] ],
     ['Clocks',
      [sup('Norwood', cat('AWARD', 'CLOCKS') ) ] ],
#     ['Bases',
#      [sup('Norwood', cat('AWARD', 'BASES') ) ] ],
#     ['Coasters & Beverage Ware',
#      [sup('Norwood', cat('AWARD', 'COASTER') ) ] ],
     ['3D Lasered Crystal',
      [sup('Norwood', cat('AWARD', 'IMAGE3') ),
       sup('The Magnet Group', cat('Crystal', '3D Lasered') )
      ] ],
     ['Specialty Gifts',
      [sup('Norwood', cat('AWARD', 'SPECIALTY') ) ] ],
     ['Vases',
      [sup('Norwood', cat('AWARD', 'VASE') ),
       sup('The Magnet Group', cat('Crystal', 'Vases') )
      ] ],
#     ['Trophies',
#      [sup('Norwood',
#                cat('AWARD', 'TROPHIES') ) ] ],
    ] ],
 ['Calendars',
  [
  ],[
     ['Calendars by Industry', [],
      { 'Agriculture' => %w(4000 4400 1851 3204 1900 5323 7047),
        'Real Estate' => %w(7001 7039 8335 2508 1503 7549 4251),
        'Religious' => %w(1653 1654 1650 2503 2509 3304),
        'Construction' => %w(1600 6100 6101 6102 6103 6104 6105 3206 2302 4425),
        'Utilities' => %w(1722 4101 4152 6702 6100 6101 6102 6103 6104 6105 6201),
        'Manufacturing' => %w(3108 6201 6602 8150 6100 6101 6102 6103 6104 6105 6251),
        'Hospitality' => %w(7231 7025 7229 5323 5351 8228),
        'Insurance' => %w(7039 7001 8125 4251 3110 8335),
        'Health Care' => %w(1301 8371 4251 1400 1403 5323 8203),
        'Retail' => %w(2201 3011 8228 1600 1717 2103),
        'Financial' => %w(7039 7001 4101 4251 8335 4152),
        'Automotive' => %w(1855 1850 5324 3200 1862 3011 7037),
        'Food Industry' => %w(1301 4151 8371 8229 7031 1300 1303),
        'Education' => %w(8153 8320 8330 8350 7569 7303 8960 6350),
      }.collect do |name, nums|
        ["#{name} Calendars",
         [sup('Norwood', match('supplier_num', Regexp.new('^'+nums.join('|')+'$') ) ) ] ]
      end
     ],
     ['Appointment Calendars',
      [sup('Norwood',
           cat('CALENDAR', 'APPT'),
           cat('GV', 'GV_APPT') ) ]],
     ['Commercial Calendars',
      [sup('Norwood', cat('CALENDAR', 'COMM') ) ]],
     ['Custom Calendars',
      [sup('Norwood', cat('CALENDAR', 'CUSTOM') ) ]],
     ['Executive Calendars',
      [sup('Norwood',
           cat('CALENDAR', 'EXEC'),
           cat('GV', 'GV_BUSINESS') ) ]],
     ['Non-Dated Calendars',
      [sup('Norwood', cat('CALENDAR', 'NODATE') ) ]],
     ['Nude Calendars',
      [sup('Norwood', cat('CALENDAR', 'NUDE') ) ]],
     ['Planners',
      [sup('Norwood', cat('CALENDAR', 'PLANNER') ) ]],
     ['Pocket and Desk Calendars',
      [sup('Norwood',
           cat('CALENDAR', 'POCKET'),
           cat('GV', 'GV_MINI') ) ]],
     ['Stick up Calendars',
      [sup('Norwood', cat('CALENDAR', 'SUC') ) ]],
     ['Perpetual Calendars',
      [sup('Logomark', cat('Perpetual Calendars') ) ] ],
    ] ],

 ['Automobile',
  [sup('Norwood', cat('AUTO', 'AUTO'))
  ],[
     ['Auto Accessories',
      [match('name', ['roadside', 'auto visor']),
       match('description', 'car visor'),
       sup('Leeds', cat('Safety & Auto', 'Auto Accessories') ),
       sup('Gemline', cat('Sport & Travel', 'Cargo') ),
       sup('Gemline',
           all(cat('Gifts', 'Safety/Auto'),
               match('name', 'auto detail') ) ),
       sup('High Caliber Line', cat('Auto') ),
       sup('Bullet Line', cat('Travel, Health & Beauty', 'Automotive Accessories') ),
       sup('Crown Products', cat('Auto Accessories') ),
       sup('Logomark', cat('Auto Accessories') ),
      ] ],
     ['Auto Organizers',
      [match('name', %w(organize contain), 1)
      ] ],
     ['Auto Safety     ',
      [sup('Leeds', cat('Safety & Auto', 'Auto Safety') ),
       sup('Gemline', cat('Gifts', 'Safety/Auto') ),
       sup('Norwood', cat('AUTO', 'HIGHWAY') ),
      ] ],
     ['Ice Scraper',
      [match('name', 'ice scraper'),
       sup('Lanco', cat('Tools / Knives', 'Ice Scraper') ) ]],
    ]],
 ['Bags',
  [sup('Norwood',
       all(cat('BAG', 'COMPBAG'),
           match('name', %w(bag brief))) ),
   sup('High Caliber Line', cat('Bags') ),
   sup('Ash City',
       all(cat('Accessories'),
           match('name', %w(bag pack portfolio tote brief)))),
   sup('Prime Line',
       cat('Bags'),
       exclude(match(%w(name description), 'cooler'))),
   sup('Hit Promotional Products',
       cat('Bags, Totes & Koolers'),
       exclude(match('name', 'kool')) ),
   sup('Crown Products',
       cat('Bags'),
       cat('Bags, Bags') ),
   sup('Sweda', cat('Bags') )
  ],[
     ['Backpacks',
      [match('name', %w(Backpack Daypack Sports\ Pack)),
       match('description', 'backpack', 1),
       sup('Leeds', cat('Backpacks', 'Backpacks')),
       sup('Gemline',
           ['Sports', 'New', 'Clearance'].collect do |name|
             cat('Backpacks', name)
           end),
       sup('Prime Line', cat('Bags', 'Backpacks') ),
       sup('Lanco', cat('Bags / Containers', 'Backpacks')),
       sup('Norwood', cat('BAG', 'BACKPACK') ),
       sup('High Caliber Line',
           all(cat('Bags'),
               match('name', 'backpack'))),
       sup('Logomark', cat('Backpacks and Slings') ),
       sup('Sweda', cat('Bags', 'Backpacks') ),
       sup('The Magnet Group', cat('Bag Factory', 'Backpacks') ),
       sup('Starline', cat('Bags', 'Backpacks') )
      ],[
         ['Cooler Backpacks',
          [match('name', 'cooler', 1)]],
         ['Computer Backpacks',
          [match('name', ['compu', 'laptop'], 1),
           sup('Leeds', cat('Backpacks', 'Compu-Backpacks') ),
           sup('Gemline', cat('Backpacks', 'Computer') ),
          ]],
         ['Checkpoint Friendly Backpacks',
          [sup('Gemline', cat('Backpacks', 'Checkpoint-friendly') )
          ]],
         ['Drawstring & Cinch Backpacks',
          [match('name', %w(drawstring cinch), 1),
           match('description', 'drawstring closure', 1),
           sup('Leeds', cat('Backpacks', 'Cinches')),
           sup('Gemline',
               cat('Backpacks', 'Cinchpacks'),
               all(cat('Backpacks', 'Sports'),
                   match('name', 'cinch') ) ),
           sup('Bullet Line', cat('Bags', 'Drawstrings & Backpacks')),
           sup('Starline', cat('Bags', 'Cinchpaks') )
          ]],
         ['Hydration Backpacks',
          [match('name', 'hydrat', 1)]],
         ['Kid Friendly Backpacks',
          [sup('Gemline', cat('Kid-friendly', 'Backpacks') ) ] ],
         ['Sling Backpacks',
          [match('description', 'sling', 1),
           sup('Leeds', cat('Backpacks', 'Slings')),
           sup('Gemline',
               cat('Backpacks', 'Monopacks'),
               all(cat('Backpacks', 'Sports'),
                   match('name', 'sling') ) ) ]],
         ['Tote Backpacks',
          [match('name', 'tote', 1)]],
         ['Wheeled Backpacks',
          [match('name', %w(wheel roll), 1),
           sup('Gemline', cat('Backpacks', 'Wheeled') )]],
         ['Womens Backpacks',
          [sup('Gemline', cat('Women`s', 'Backpacks')),
           sup('High Caliber Line',
               all(cat("Women´s Gifts"),
                   match('name', 'bag') ) ) ] ],
        ] ],
     ['Portfolios & Business Bags',
      [match('name', ['portfolio', /attache(?:\s|$)/, 'briefcase', 'brief case']),
       match('name', 'brief', 1),
       sup('Leeds', cat('Business Cases', 'Business Cases') ),
       sup('Gemline',
           ['Clearance', 'New'].collect do |name|
             cat('Portfolios', name)
           end),
       sup('Lanco', cat('Bags / Containers', 'Business Cases')),
       sup('Prime Line',
           all(cat('Bags', 'Computer Bags'),
               match('name', 'brief') ) ),
       sup('Norwood', cat('BAG', 'BRIEFCASES') ),
       sup('Bullet Line',
           all(cat('Bags', 'Briefcases & Laptop Cases'),
               match('name', ['brief', 'messenger', 'document']) ) ),
       sup('Logomark', cat('Briefcases') ),
       sup('Sweda', cat('Bags', 'Messenger & Laptop') ),
       sup('The Magnet Group', cat('Bag Factory', 'Business Cases') ),
       sup('Starline', cat('Bags', 'Business Briefs') )
      ],[
         ['Computer Business Bags',
          [match('name', 'computer brief'),
           sup('Leeds',
               cat('Business Cases', 'Compu-Cases'),
               cat('Business Cases', 'Compu-Messenger Bags') ),
           sup('Gemline',
               cat('Portfolios', 'Computer Cases') ) ]],
         ['Messenger & Saddle Bags',
          [match('name', %w(messenger saddle), 2),
           match('name', 'messenger bag'),
           sup('Leeds',
               cat('Business Cases', 'Messenger Bags'),
               cat('Business Cases', 'Compu-Messenger Bags') ),
           sup('Gemline',
               cat('Portfolios', 'Business'),
               cat('Portfolios', 'Messenger Bags') ),
           sup('Logomark', cat('Shoulder Bags') )
          ]],
         ['Leather Business Bags',
          [match('name', 'lthr', 1), # Why doesn't this work?
           match('material', 'leather', 1),
           sup('Logomark',
               all(cat('Leather Bags'),
                   match('name', 'brief') ) ),
          ]],
         ['Recycled Business Bags',
          [match(%w(name description), 'recycle', 1) ]],
         ['Wheeled Business Bags',
          [match('name', 'wheel', 1),
           sup('Leeds', cat('Business Cases', 'Wheeled Business Cases') ),
           sup('Gemline', cat('Portfolios', 'Wheeled') )
          ]],
         ['Kid Friendly Portfolios',
          [sup('Gemline', cat('Kid-friendly', 'Portfolios')) ]],
         ['Womens Portfolios',
          [sup('Gemline', cat('Women`s', 'Portfolios')) ]],
         ['Vertical Bags',
          [sup('Gemline', cat('Portfolios', 'Vertical Bags')) ]],
         ['Checkpoint Friendly Portfolios',
          [sup('Gemline', cat('Portfolios', 'Checkpoint-friendly')) ]],
        ] ],
     ['Duffel Bags',
      [match('name', ['duffel', 'duffle']),
       sup('Gemline',
           ['Clearance', 'New', 'Travel Bags'].collect do |name|
             cat('Sport & Travel', name)
           end),
       sup('Lanco', cat('Bags / Containers', 'Sport and Duffle Bags')),
       sup('Norwood', cat('BAG', 'DUFFELS')),
       sup('Bullet Line', cat('Bags', 'Duffels') ),
       sup('Logomark', cat('Duffel Bags') ),
       sup('Sweda', cat('Bags', 'Duffels') ),
       sup('Starline', cat('Bags', 'Duffels') ),
      ],[
         ['Executive Duffel Bags',
          [sup('Leeds', cat('Duffels', 'Executive Duffels') ) ]],
         ['Sport Duffel Bags',
          [match('name', %w(athletic fitness), 2), # for Prime Line
           match('name', 'Sport Duffel', 1),
           sup('Leeds', cat('Duffels', 'Sport Duffels') ),
           sup('Gemline',
               cat('Sport & Travel', 'Sport Bags'),
               match('name', 'sport bag')),
           sup('Norwood', cat('BAG', 'SPORT') )
          ],[['Kid Friendly Sport Bags',
              [sup('Gemline',
                   cat('Kid-friendly', 'Sport & Travel') ) ] ],
            ]],
         ['Wheeled Duffel Bags',
          [match('name', 'wheeled'),
           sup('Leeds', cat('Duffels', 'Wheeled Duffels') ),
           sup('Gemline', cat('Sport & Travel', 'Wheeled') ) ]]
        ]],
     ['Golf Bags',
      [match('name', 'golf', 1),
       sup('Leeds',
           all(cat('Travel & Golf', 'Golf'),
               match('name', %w(bag duffel)) ) ),
       sup('Norwood',
           all(match('name', %w(bag carrier)),
               cat('GOLF') ),
           match('name', ['stand bag', 'cart bag'])),
       sup('Starline', cat('Bags', 'Golf Bags') )
      ]],
     ['Luggage',
      [sup('Leeds', cat('Travel & Golf', 'Luggage') ),
       sup('Norwood',
           cat('TRAVEL', 'LUGGAGE'),
           match('name', 'carry on') ),
       sup('Logomark', cat('Luggage') ),
      ]],
     ['Checkpoint Friendly Bags',
      [ ],
      [dup('Bags', 'Backpacks', 'Checkpoint Friendly Backpacks'),
       dup('Bags', 'Portfolios & Business Bags', 'Checkpoint Friendly Portfolios') ] ],
     ['Leather Bags',
      [match('material', 'leather', 1),
       sup('Logomark', cat('Leather Bags') )
      ]],
     ['Computer Bags',
      [match('name', ['computer case', 'computer bag', 'laptop bag', 'laptop case']),
       match('name', 'compu', 1),
       sup('Prime Line', match('name', ['computer sleeve', 'laptop sleeve']) ),
       sup('Logomark', cat('Computer Cases') ),
       sup('Starline', cat('Bags', 'Computer Bags') )
               
      ],[dup('Bags', 'Backpacks', 'Computer Backpacks'),
         ['Laptop Sleeves',
          [match('name', 'laptop sleeve'),
           sup('Prime Line', cat('BUILT', 'LaptopslashTablet Sleeves'))
          ]],
        ] ],
     ['Wheeled Bags',
      [match('name', 'wheel', 1),
       sup('Gemline', cat('Sport & Travel', 'Wheeled') )
      ],[dup('Bags', 'Backpacks', 'Wheeled Backpacks'),
         dup('Bags', 'Business Bags', 'Wheeled Business Bags'),
         dup('Bags', 'Duffel Bags', 'Wheeled Duffel Bags')
        ] ],
     ['Tote Bags',
      [match('name', 'tote'),
       sup('Leeds', cat('Totes', 'Totes')),
       sup('Gemline',
           ['New', 'Clearance'].collect do |name|
             cat('Totes', name)
           end),
       sup('Lanco', cat('Bags / Containers', 'Tote Bags')),
       sup('Prime Line', cat('Bags', 'Totes')),
       sup('Norwood', cat('BAG', 'TOTE') ),
       sup('Bullet Line', cat('Bags', 'Totes') ),
       sup('Logomark', cat('Tote and Shoppers') ),
       sup('Sweda', cat('Bags', 'Totes') ),
       sup('The Magnet Group', cat('Bag Factory', 'Totes') ),
       sup('Starline', cat('Bags', 'Totes') ),
      ],[
         ['Business & Meeting Totes',
          [match(%w(name description), %w(business meeting computer laptop), 1),
           exclude(match('description', 'business card')) ] ],
         ['Cotton Canvas Totes',
          [match(%w(name description material), %w(cotton canvas), 1),
           sup('Leeds', cat('Totes', 'Cotton Totes') ),
           sup('Gemline',
               cat('Totes', 'Cotton Bags') )]],
         ['Jute Totes',
          [match(%w(name description material), %w(jute), 1),
           sup('Prime Line', cat('Bags', 'Jute') )]],
         ['Non-woven Polypropylene Totes',
          [match('material', %w(poly non-woven non\ woven), 1),
           match(%w(name description), ['poly', 'pet plastic', 'non-woven'], 1),
           sup('Leeds', cat('Totes', 'Non-Woven Totes') ),
           sup('Gemline', cat('Totes', 'Non-woven') ),
           sup('Prime Line', cat('Bags', 'Non-Woven') )]],
         ['Shopper Totes',
          [match(%w(name description), %w(shopper grocery market), 2),
           sup('Gemline', cat('Totes', 'Shoppers') ),
           sup('Prime Line', cat('Bags', 'Grocery') ) ]],
         ['Cooler & Insulated Totes',
          [match(%w(name description), %w(cooler lunch six\ pack insulate), 2)]],
         ['Trade Show Totes',
          [match(%w(name description), %w(trade\ show tradeshow expo convention), 1),
           sup('Gemline', cat('Totes', 'Expo'))]],
         ['Kid Friendly Totes',
          [sup('Gemline', cat('Kid-friendly', 'Totes') ) ] ],
         ['Recycled & Organic Totes',
          [match(%w(name description), 'recycled', 1) ]],
         ['Backpack Totes',
          [match(%w(name description), 'backpack', 1)],
          [
           ['Drawstring Totes',
            [match(%w(name description), 'drawstring', 2),
             match('name', %w(cinch sling), ['Bags', 'Backpacks', 'Drawstring Backpacks'])]],
          ] ],
         ['Womens Totes',
          [match('name', 'gloss', 1),
           sup('Gemline', cat('Women`s', 'Totes')) ]],
         ['Zippered Totes',
          [match(%w(name description), 'zipper', 1)]],
        ] ],
     ['Tool Bags',
      [match('name', ['tool', 'utility case'], 1),
       sup('Gemline',
           all(cat('Gifts', 'Home Improvement'),
               match('name', %w(bag case)))),
       sup('Starline',
           all(cat('Tools', 'Tool Sets/Bags'),
               match('name', 'bag') ) )
      ]],
     ['Wine Bags',
      [match(%w(name description), 'wine', 1),
       match('name', ['wine kit', 'wine tote', /wine.+holder/i])]],
     ['Womens Bags',
      [sup('Gemline', cat('Women`s', 'Sport & Travel')) ]],
     ['Waist Pack',
      [match('name', ['waist pack', 'fanny pack']) ] ],
     ['Pouches',
      [match('name', 'pouch'),
       sup('Lanco', cat('Bags / Containers', 'Small Pouches & Bags'))] ],
     ['Amenity Cases',
      [match('name', 'toiletr'),
       sup('Gemline', cat('Sport & Travel', 'Amenity Cases') ),
       sup('Bullet Line',
           all(cat('Travel, Health & Beauty', 'Travel Accessories'),
               match('name', ['amenity', 'travel']) ) ),
       sup('Norwood', cat('TRAVEL', 'UTILITY') )
      ]],
    ] ],

 ['Candles, Bath & Body',
  [
  ],[
     ['Bath & Body Gift Sets',
      [sup('Lanco', cat('Candles / Bath / Body', 'Bath & Body Gift Sets') ) ]],
     ['Candles',
      [match('name', 'candle'),
       sup('Lanco', cat('Candles / Bath / Body', 'Candles') ) ]],
     ['Bath & Body Kits',
      [match('name', 'spa kit'),
       sup('Lanco', cat('Candles / Bath / Body', 'Bath & Body Kits') ) ]],
     ['Massagers',
      [match('name', 'massager') ]],
     ['Bath & Body Lotions',
      [sup('Lanco', cat('Candles / Bath / Body', 'Bath & Body Lotions') ) ]],
    ] ],

 ['Brands',
  [sup('Gemline', duplicate(['Brands'], 'supplier_categories'))
  ],[
     ['Cleveland®',
      [sup('Norwood', cat('GOLF', 'CLEVE')) ]],
     ['Titleist®',
      [sup('Norwood', cat('GOLF', 'TITLEIST')) ]],
     ['Callaway®',
      [match('name', 'callaway'),
       sup('Norwood', cat('GOLF', 'CALLAWAY')),
       sup('Sweda', cat('BRANDS', 'Callaway Golf') )
      ]],
     ['Wilson®',
      [sup('Norwood', cat('GOLF', 'WILSON')) ]],
     ['Nike®',
      [match('name', 'nike'),
       sup('Norwood', cat('GOLF', 'NIKE')) ] ],
     ['Built®',
      [sup('Prime Line', cat('BUILT')) ]],
     ['contigo®',
      [sup('ETS Express Inc', cat('contigo')) ]],
     ['h2go®',
      [sup('ETS Express Inc', cat('h2go bottles')) ]],

    ] ],

 ['Computer Accessories',
  [match('name', 'Computer Accessory'),
   sup('Prime Line', cat('Technology') ),
   sup('Norwood', cat('TECHNOLOGY', 'ELEC') ),
   sup('LogoIncluded', cat('Card Reader') ),
   sup('Logomark', cat('Computer Accessories') ),
   sup('Starline', cat('Business', 'Computer Accessories') )
  ],[
     ['Apple Accessories',
      [match('name', /i(P(o|a)d)|(Phone)/),
       sup('LogoIncluded', cat('Mobile / Apple Accessories')),
      ]],
     ['CD Products',
      [match('name', ['CD case', 'DVD case']),
       sup('Lanco', cat('Office / Computer Essentials', 'CD Products') ),]],
     ['Computer Accessory Kits',
      [match('name', 'computer accessories')]],
     ['Computer Brush',
      [match('name', 'computer brush'),
       sup('Lanco', cat('Office / Computer Essentials', 'Computer Brush') ) ]],
     ['Cables & Cords',
      [match('name', %w(cable cord), 1),
       match('name', %w(phone\ cord)),
       match('name', /((usb)|(network)).+cable/i),
       sup('Lanco', cat('Office / Computer Essentials', 'Modem Cord') ) ]],
     ['Computer Mice',
      [match('name', 'mouse ', 1),
       match('name', /mouse($|\s)/),
       exclude(match('name', 'pad') ),
       sup('Norwood',
           all(match('name', ' mouse'),
               cat('TECHNOLOGY', 'OTHERTECH'), ) ),
       sup('LogoIncluded', cat('Mouse') ),
       sup('Sweda', cat('Computer', 'Mouse') )
      ]],
     ['Computer Keyboards / Keypads',
      [match('name', ['keyboard', 'keypad']),
      ]],
     ['Computer Mouse Pads',
      [match('name', ['mousepad', 'mouse pad']), 
       sup('Norwood',
           all(match('name', 'mousepad'),
               cat('OFFICE', 'TECHNOLOGY') ) ),
       sup('Bic Graphics',
           match('supplier_num', /^((MPC?\d)|(MPSH)|(MPFR))/) ),
      ] ],
     ['Screen Cleaners',
      [match('name', 'screen cleaner'),
       match('description', /screen.+?brush/i),
       sup('LogoIncluded', cat('Screen Cleaner') )] ],
     ['MP3 Players',
      [match('name', %w(mp3 mp4) + [/(^|\s)ipod(\s|$)/i]),
       sup('Lanco', cat('Office / Computer Essentials', 'Mouse Pads') ),
       sup('Prime Line',
           all(cat('Mp3 / Radios'),
               match(%w(name description), %w(mp3 iPod)) ) ),
       sup('LogoIncluded', cat('MP3 Player / MP4 Player') )]],
     ['Web Cams',
      [match('name', 'web cam')] ],
     ['Web Keys',
      [sup('LogoIncluded', cat('Web Key') )] ],
     ['WiFi Finders',
      [sup('LogoIncluded', cat('WiFi Finder') )] ],
     ['Tablet Accessories',
      [sup('Gemline', cat('Gifts', 'Tablet Accessories') )
      ],[['iPad Accessories',
          [match('name', 'iPad')]],
         ['Tablet Cases, Stands & Sleeves',
          [all(match('name', %w(case stand sleeve holder padfolio)),
               match(%w(name description), %w(tablet iPad))),
           sup('Gemline', cat('Padfolios', 'e-Padfolios'),
               cat('Technology', 'Tablet cases/stands'))
          ]],
         ['Screen Stylus',
          [all(match('name', ['stylus', 'tablet pen']),
               match('description', ['screen', 'ipad', 'iphone']))
          ]],
        ] ],
     ['Camera & Phone Holders',
      [all(match('name', 'case'),
           match('name', %w(ipod nano camera))),
       match('name', ['device holder', /phone.+?case/i])]],
     ['USB Hubs',
      [match('name', 'hub', 1),
       match('name', /usb.+hub/i),
       sup('Leeds', cat('Technology', 'USB Hubs') ),
       sup('Norwood',
           all(match('name', ' hub'),
               cat('OFFICE', 'TECHNOLOGY') ) ),
       sup('LogoIncluded', cat('USB Hub')),
       sup('Sweda', cat('Computer', 'Hubs') )
      ]],
     ['USB Accessories',
      [all(match('name', 'usb'),
           match('name', ['charger']) ),
       all(match('name', ['sd card', 'card reader']),
           match(%w(name description), 'USB')),
       sup('LogoIncluded',
           cat('USB Accessories'),
           cat('SD Cards  Readers'),
           all(cat('Tech Accessories'),
               match(%w(name description), 'USB'))) ]],
     ['USB Flash Drives',
      [match('name', %w(flash memory mb gb), 1),
       sup('Leeds', cat('Memory') ),
       sup('Prime Line', cat('Technology', 'USB Memory Sticks') ),
       sup('Logomark', cat('USB Drives') ),
       sup('LogoIncluded', cat('USB Drive') ),
       sup('Starline', cat('Business', 'Flash Drives') )
      ],[
         ['Pen USB Flash Drives',
          [match('name', 'pen', 1),
           sup('Leeds', cat('Memory', 'Memory Pens & Gift Sets') ),
           sup('LogoIncluded', cat('Pen Drive') )]],
         ['Recycled Flash Drives',
          [match(%w(name description), 'recycle', 1) ]],
        ] +
      ['128M', '256M', '512M', '1G', '2G', '4G', '8G', '16G', '32G', '64G'].collect do |name|
        ["#{name}B Flash Drives",
         [match('name', name, 1),
          sup('LogoIncluded',
              match('memory', name) ) ]]
      end
     ],
     ['Digital Photo Frames',
      [sup('Leeds', cat('Technology', 'Digital Photos') ),
       sup('Norwood',
           all(match('name', 'digital photo'),
               cat('OFFICE', 'TECHNOLOGY') ) ),
       sup('LogoIncluded', cat('Digital Photo Frame') ),
       sup('Sweda', cat('Computer', 'Digital Picture Frames') )
      ]],
    ] ],

 ['Desktop Accessories',
  [sup('Leeds',
       cat('Desktop', 'Desktop Accessories And Sets'),
       cat('Desktop', 'Desktop Essentials'),
       cat('Desktop', 'Electronics & Clocks') ),
   sup('Prime Line',
       cat('Office', 'Desk Items')),
   sup('Norwood',
       cat('GOLF', 'DESKFUN'),
       cat('OFFICE', 'DESKACC')),
   sup('Bullet Line', cat('Desktop', 'Desktop Accessories') ),
   sup('Hit Promotional Products',cat('Desk Accessories') ),
   sup('Logomark', cat('Desk and Office Accessories') ),
   sup('Starline', cat('Business', 'Convention/Desktop') )
  ],[
     ['Calculators',
      [match('name', 'calculator'),
       sup('High Caliber Line', cat('Calculators') ),
       sup('Prime Line', cat('Office', 'Calculators') ),
       sup('Lanco', cat('Calc / Clocks / Radios', 'Calculators') ),
       sup('Hit Promotional Products',
           match('name', 'calc') ),
       sup('Logomark', cat('Calculators') ),
       sup('Sweda',
           cat('Calculators', 'Desktop'),
           cat('Calculators', 'Handheld') ),
       ] ],
     ['Clocks',
      [match('name', 'clock'),
       sup('Lanco', cat('Calc / Clocks / Radios', 'Clocks') ),
       sup('High Caliber Line', cat('Clocks') ),
       sup('Norwood', cat('AWARD', 'CLOCKS') ),
       sup('Logomark',
           cat('Desk Clocks'),
           cat('Clocks with Photo Frames'),
           cat('Watch Clocks') ),
       sup('Sweda',
           cat('Clocks', 'Desktop'),
           cat('Clocks', 'Wall Clocks'),
           cat('Clocks', 'Travel Alarm') ),
       sup('The Magnet Group',
           cat('Clocks', 'Elegant Clocks'),
           cat('Clocks', 'Clock/Frame Combos'),
           cat('Innovations', 'Clocks') ),
       sup('The Magnet Group', cat('Clocks') )
      ],[
         ['Acrylic Clocks',
          [match(%w(name description material), 'acrylic', 1),
           sup('The Magnet Group', cat('Clocks', 'Acrylic Clocks') )
          ] ],
         ['Brass Clocks',
          [match(%w(name description material), 'brass', 1),
           sup('The Magnet Group', cat('Clocks', 'Brass Clocks') )
          ] ],
         ['Gimble Clocks',
          [match(%w(name description), %w(gimble twist), 1),
           sup('The Magnet Group', cat('Clocks', 'Gimble Clocks') )
          ] ],
         ['Glass Clocks',
          [match(%w(name description material), 'glass', 1),
           sup('The Magnet Group', cat('Clocks', 'Glass Clocks') )
          ] ],
         ['Marble Clocks',
          [match(%w(name description material), 'marble', 1),
           sup('The Magnet Group', cat('Clocks', 'Marble Clocks') )
          ] ],
         ['Wood Clocks',
          [match(%w(name description material), 'wood', 1),
           sup('The Magnet Group', cat('Clocks', 'Wood Clocks') )
          ] ],
         ['Silver Clocks',
          [match(%w(name description material), 'silver', 1),
           sup('The Magnet Group',
               all(cat('Clocks', 'Silver and Unique Clocks'),
                   match(%w(name description material), 'silver') ) ),
          ] ],
         ['Unique Clocks',
          [sup('The Magnet Group',
               cat('Clocks', 'Silver and Unique Clocks'),
               exclude(match(%w(name description material), 'silver') ) ),
          ] ],
         ['Travel Clocks',
          [match(%w(name description), 'travel', 1),
           sup('Leeds',
               all(cat('Travel Gifts', 'Travel Clocks'),
                   match('name', 'clock')) ),
           sup('Logomark', cat('Travel Clocks') ),
          ] ] ] ],
     ['Pen Stands and Holders',
      [sup('Logomark', cat('Pen Stands and Holders') ) ] ],
     ['Radios',
      [match('name', 'radio'),
       sup('Prime Line',                
           match(%w(name description), %w(radio am/fm) ) ),
       sup('Lanco', cat('Calc / Clocks / Radios', 'Radios') ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Radios') ),
       sup('Logomark', cat('Radios') )
      ]],
     ['Weather Station',
      [match('name', 'weather station'),
       sup('Logomark', cat('Weather Stations') ),
       sup('Starline', cat('Business', 'Weather Stations') )
      ]],
     dup('Computer Accessories', 'Digital Photo Frames'),
     ['Picture Frames',
      [match('name', ['photo frame', 'picture frame']),
       match('name', 'frame', 1),
       sup('Norwood', cat('OFFICE', 'PHOTO') ),
       sup('High Caliber Line', cat('Picture Frames') ),
       sup('Prime Line',
           match('name', 'frame')),
       sup('Logomark',
           cat('Photo Frames'),
           cat('Clocks with Photo Frames') ),
       sup('Sweda',
           cat('Photo Frames'),
           cat('Picture Frames') ),
       sup('The Magnet Group',
           cat('Clocks', 'Clock/Frame Combos'),
           cat('Innovations', 'Frames'),
           cat('Innovations', 'Acrylic Frames'),
           cat('Innovations', 'Metal Displays and Frames')),
      ]],
     ['Photo Albums',
      [match('name', %w(photo\ album brag\ book)) ] ],
     ['Letter Openers',
      [match('name', ['letter opener', 'slitter']),
       match('name', 'opener', 1),
       sup('Lanco', cat('Office / Computer Essentials', 'Letter Opener') ),
       sup('Logomark', cat('Letter Openers') )
      ]],
     ['Laser Pointers',
      [match('name', 'laser', 1),
       match('name', 'laser pointer'),
       sup('High Caliber Line', cat('Laser Pointers') ),
       sup('Bullet Line', cat('Lighting', 'Laser Pointers') ),
       sup('LogoIncluded', cat('Wireless Presenter') ),
       sup('Logomark', cat('Laser Pointers') )]],
     dup('Computer Accessories', 'Computer Mice'),
     ['Bookmarks',
      [match('name', ['bookmark', 'book mark']) ] ],
     ['Speakers',
      [match('name', 'speaker'),
       sup('Leeds',
           all(cat('Technology', 'Music & Media'),
               match(%w(name description), 'speaker') ) )] ],
     ['Headphones & Earbuds',
      [match('name', %w(headphones head\ phones earbuds ear\ buds earphone ear\ plugs ear\ phones)),
       all(match('name', 'headset'), match('name', 'headphones') ),
       sup('Leeds',
           all(cat('Technology', 'Music & Media'),
               match('name', %w(headph ear)) ) ),
       sup('LogoIncluded', cat('Bluetooth Headset') ),
       sup('Bullet Line', cat('Technology', 'Media') )
      ] ],
     ['Desktop Organizers',
      [match('name', ['desk caddy', 'desk organizer', 'pen caddy'])]],
     ['Card Holders',
      [match('name', 'card holder', 1),
       match(%w(name description), 'business card holder'),
       sup('Prime Line',
           match('name', 'card case') ),
       sup('High Caliber Line',
           all(cat('Office'),
               match('name', 'card holder') ) ),
       sup('Bullet Line',
           match('name', 'card case') ),
       sup('Logomark',
           cat('Business Card Holders') ),
       sup('The Magnet Group',
           cat('Innovations', 'Pocket Items'),
           exclude(match(%w(name description), ['money clip', 'cloth']) ) ),
      ] ],
     ['Note Holders',
      [match('name', ['note holder', 'memo holder', 'memo stack', 'Post-it holder','note dispenser', 'sticky note', 'sticky flag']), #, 1),
       sup('Lanco',
           cat('Office / Computer Essentials', 'Memo Holder'),
           cat('Office / Computer Essentials', 'Memo Dispenser'),
           cat('Journals / Portfolios', 'Sticky Holder')),
       sup('Prime Line',
           all(cat('Office', 'Desk Helpers'),
               match('name', 'note') ) ),
       sup('High Caliber Line',
           all(cat('Office'),
               match('name', ' clip') ),
           match('name', 'note holder') ),
       sup('Norwood', cat('OFFICE', 'NOTES') ),
       sup('Bullet Line', cat('Sticky Notes', 'Office Accessories') ),
       sup('Logomark', cat('Memo Holders') ),
       sup('The Magnet Group',
           all(cat('Innovations', 'Paper Clip, Tape & Note Dispense'),
               match('name', 'note dispenser') ) )
      ],[
         ['Notenest & Note Clips',
          [match('name', 'clip', 1),
           match('name', ['notenest', 'memo clip']),
           sup('Prime Line',
               match('name', 'notenest') ),
           sup('Hit Promotional Products',
               match('name', 'clip', 2) ),
           sup('The Magnet Group', cat('Innovations', 'Power Clips') )
          ] ],
         ['Memo Books',
          [match('name', ['memo book', 'message pad holder'], 2)]],
         ['Sticky Note Books',
          [match('name', ['sticky memo', 'sticky flags', 'sticky note'], 1),
           match('name', /stick.+((note)|(flag)).+book/i),
           sup('Prime Line', cat('Office', 'Sticky Books')),
           sup('Bullet Line', cat('Sticky Notes', 'Booklets & Notebooks') ),
           sup('Bic Graphics',
               match('supplier_num', /^((MFP?B)|(PFBD)|(PF[CN]))$/) ) ] ]
        ]],
     ['Notepads',
      [],
      [['Adhesive Cubes',
        [sup('Bic Graphics',
             match('supplier_num', /^SNC\d/)) ]],
       ['Adhesive Notepads',
        [sup('Bic Graphics',
             match('supplier_num', /^((V?P\d)|(SND\d))|(B4A6A150)/)) ]],
       ['Non-Adhesive Notepads',
        [sup('Bic Graphics',
             match('supplier_num', /^NS\d/)) ]],
       ['Non-Adhesive Cubes',
        [sup('Bic Graphics',
             match('supplier_num', /^((NC2)|(V?NC3)|(VNC4[AB]$))/)) ]],

      ]],
     ['Paper Clips & Fasteners',
      [#match('name', 'paper clip'),
       sup('Norwood',
           cat('OFFICE', 'CLIP') ),
       sup('The Magnet Group',
           all(cat('Innovations', 'Paper Clip, Tape & Note Dispense'),
               match('name', 'paper clip') ) )
      ]],
     ['Paper Clip Holders',
      [match('name', ['clip dispenser', /paper.+clip.+((dispens)|(holder))/i]),
       match('name', ['cache', 'clip holder', 'clip keeper'], 1),
       match(%w(name description), 'paper clip', 1),
       sup('Lanco', cat('Office / Computer Essentials', 'Paper Clip Holder') ),
       sup('Prime Line',
           match('name', 'cache') )]],
     ['Paperweights',
      [match('name', 'paperweight'),
       sup('The Magnet Group', cat('Crystal', 'Paperweights and Crystal Boxes') )
      ]],
     ['Piggy Bank',
      [match(%w(name description), /(pig(gy)?)|(coin) bank/i),
       all(match('name', 'bank'), match(%w(name description), 'coin')),
       exclude(match('name', 'stress') ),
      ] ],
     ['Push Pins',
      [match('name', 'push pin')] ],
     ['Rulers',
      [match('name', 'ruler'),
       sup('Lanco', cat('Office / Computer Essentials', 'Ruler') ) ]],
     ['Scissors',
      [match('name', 'scissor'),
       sup('Lanco', cat('Office / Computer Essentials', 'Scissors') ) ]],
     ['Staplers',
      [match('name', 'stapler'),
       sup('Lanco', cat('Office / Computer Essentials', 'Stapler') ),
       sup('Lanco', cat('Writing Instruments', 'Stapler') ),
       sup('The Magnet Group', cat('Innovations', 'Staplers') )
      ]],
     ['Staple Removers',
      [match('name', 'staple remover'),
       sup('Lanco', cat('Writing Instruments', 'Staple Remover') ) ]],
     ['Tape Dispensers',
      [match('name', 'tape dispenser'),
       sup('Lanco', cat('Office / Computer Essentials', 'Tape Dispenser') ),
       sup('High Caliber Line',
           all(cat('Office'),
               match('name', 'tape') ) )]],
     ['Magnets',
      [sup('Norwood', cat('OFFICE', 'MAGNET') ),
       sup('The Magnet Group', cat('Innovations', 'Dots and Springs') ),
       sup('The Magnet Group', cat('Magnets') ) ## TEMPORARY
      ],
      [['Business Card Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG[EJ]?BC/) ),
         sup('The Magnet Group',
             cat('Magnets', 'Business Card Magnets'),
             cat('Magnets', 'Business Card Magnets - Unique') ),
         sup('Starline',
             cat('Magnets & Tags', 'Business Cards') )
        ]],
       ['Stock Shape Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGSS/) ),
         sup('Starline',
             cat('Magnets & Tags', 'Stock Shapes') )
        ]],
       ['States and Countries',
        [sup('Starline',
             cat('Magnets & Tags', 'States and Countries') )
        ]],
       ['Custom Shape Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG((CS)|(SE))/) ),
         sup('Starline',
             cat('Magnets & Tags', 'Custom Shapes') )
        ]],
       ['Dry Erase Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG[DS]E/) ) ]],
       ['Picture Frame Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGSPF/) ),
         sup('The Magnet Group', cat('Magnets', 'Picture Frames') ),
         sup('Starline',
             cat('Magnets & Tags', 'Picture Frames') )
        ]],
       ['Calendar & Schedule Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG((CL)|(SCH))/) ),
         sup('The Magnet Group',
             cat('Magnets', 'Calendars'),
             cat('Magnets', 'Schedule Magnets') ),
         sup('Starline',
             cat('Magnets & Tags', 'Calendars'),
             cat('Magnets & Tags', 'Schedules'),)
        ]], 
       ['Mood Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^(MG((FM)|(M[AM])))$/) ) ]], 
       ['Car Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGCAR/) ),
         sup('The Magnet Group', cat('Magnets', 'Car Signs') )
        ]], 
       ['Paper Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGECO/) ) ]], 
      ]],
     ['Snow Globe',
      [match(%w(name description), ['snow globe', 'glitter globe']) ] ],
     ['Book Lights',
      [match('name', ['book light', 'book-light']),
       sup('Bullet Line', cat('Lighting', 'Book Lights') ) ] ],
     ['Pencil Sharpeners',
      [match('name', 'pencil sharpener')] ],
     ['Magnifiers',
      [match('name', 'magnifier', 1),
       sup('Logomark', cat('Magnifiers') ) 
      ]],
    ] ], 

 ['Coolers',
  [match('name', ['cooler', 'kooler']),
   sup('Gemline',
       cat('Coolers', 'New') ),
   sup('Lanco', cat('Bags / Containers', 'Lunch Bag & Coolers')),
   sup('Prime Line',
       cat('Bags', 'Coolers'),
       all(cat('Bags'),
           match(%w(name description), 'cooler'))),
   sup('Norwood', cat('BAG', 'COOLERS') ),
   sup('High Caliber Line',
       all(cat('Bags'),
           match('name', 'cooler'))),
   sup('Bullet Line', cat('Coolers', 'Rolling & Chair Coolers') ), 
   sup('Hit Promotional Products',
       all(cat('Bags, Totes & Koolers'),
           match('name', 'kool') ) ),
   sup('Crown Products', cat('Coolers') ),
   sup('Logomark', cat('Coolers') ),
   sup('Sweda', cat('Bags', 'Coolers') ),
   sup('The Magnet Group', cat('Bag Factory', 'Coolers') )
  ],[
     ['Can Coolers',
      [match('name', 'can', 1)] ],
     ['Chair Coolers',
      [match('name', 'chair', 1) ] ],
     ['Event Coolers',
      [sup('Leeds', cat('Coolers', 'Event Coolers') ),
       sup('Gemline', cat('Coolers', 'Event') ) ]],
     ['Drink Coolers',
      [sup('Norwood', cat('OUTDOOR', 'HSCOOLERS') ) ] ],
     ['Kid Friendly Coolers',
      [sup('Gemline', cat('Kid-friendly', 'Coolers') ) ] ],
     ['Lunch Coolers',
      [match('name', 'lunch', 1),
       match('name', ['lunch kit', 'lunch bag']),
       sup('Leeds', cat('Coolers', 'Lunch Coolers') ),
       sup('Gemline', cat('Coolers', 'Lunch Bags') ),
       sup('Bullet Line', cat('Coolers', 'Lunch Coolers') ),
       sup('Sweda', cat('Bags', 'Lunch Bags') )
      ] ],
     ['Wheeled Coolers',
      [match('name', %w(wheel rolling), 1),
       sup('Gemline', cat('Coolers', 'Wheeled') ),
       sup('Logomark', cat('Rolling Bags') )
      ]],
     ['Refrigerators',
      [sup('Logomark', cat('Refrigerators') ) ] ],
     ['Wine Coolers',
      [duplicate(['Bags', 'Wine Bags']),
       match(%w(name description), 'wine', 1)]]
    ] ],
 ['Drinkware',
  [#match('name', %w(coffe))
   sup('Prime Line', cat('Drinkware') ),
   sup('Norwood', cat('DRINK', 'BOTTLE') ),
   sup('High Caliber Line', cat('Drinkware') ),
   sup('Lanco', cat('Drinkware', 'Cups') ),
   sup('Hit Promotional Products', cat('Plastic & Metal Drinkware') ),
   sup('Crown Products', cat('Drinkware') ),
   sup('Logomark',
       cat('Water Bottles and Flasks'),
       cat('Executive Drinkware') ),
   sup('Sweda',
       cat('Drinkware', 'Water Bottles'),
       cat('Drinkware', 'Water Bottles (Plastic)') ),
   sup('ETS Express Inc')
  ],[
     ['Acrylic Drinkware',
      [match(%w(name description material), 'acrylic', 1),
       sup('Leeds', cat('Drinkware', 'Acrylic') ),
      ]],
     ['Aluminum Bottles',
      [match(%w(name description material), 'aluminum', 1),
       sup('Leeds',
           cat('Drinkware', 'Aluminum Sport Bottles')),
       sup('Lanco',
           cat('Drinkware', 'Metal Bottles') ),
       sup('ETS Express Inc',
           cat('aluminum') ),
      ]],
     ['Stainless Steel Bottles', # Should this be vacuum tumbers?
      [sup('Leeds', cat('Drinkware', 'Stainless Sport Bottles')),
       sup('ETS Express Inc', cat('steel') )
      ]],
     ['Vacuum Tumblers',
      [sup('Sweda', cat('Drinkware', 'Vacuum Bottles') ),
       sup('Starline', cat('Drinkware', 'Vacuum Tumblers'),
           cat('Drinkware', 'Vacuum Bottles') )
      ] ],
     ['Can & Bottle Holders',
      [match('name', ['can holder', 'bottle holder', 'bottle insulator']), # Was matched on descrption but to broad
       match('name', 'holder', 1),
       all(match('name', 'insulator'),
           match('description', 'drink') ),
       sup('Lanco', cat('Drinkware', 'Can & Bottle Holder') ),
       sup('Prime Line', cat('Drinkware', 'Can Bottle Holders') ),
       sup('Norwood', cat('DRINK', 'KOOZIE') ),
       sup('High Caliber Line',
           all(cat('Drinkware', 'Accessories'),
               match('name', 'holder') ) ),
       sup('Hit Promotional Products',
           all(cat('Leisure'),
               match('name', 'Kan') ) ),
       sup('Logomark', cat('Bottle Holders') )
      ] ],
     ['Coasters', 
      [match('name', 'coaster'),
       sup('Lanco', cat('Drinkware', 'Coasters') ),
       sup('Norwood',
           cat('HOUSEWARES', 'COASTERS'),
           cat('AWARD', 'COASTERS') ),
       sup('Hit Promotional Products',
           exclude(match('name', 'mug') ) ),
       sup('Logomark', cat('Coasters') )]],
     ['Jigger',
      [match('name', 'jigger')]],
     ['Ceramic',
      [match('name', 'ceramic', 1),
       sup('Leeds', cat('Drinkware', 'Ceramics') ),
       sup('Bullet Line', cat('Drinkware', 'Ceramics') ),
       sup('Hit Promotional Products', cat('Ceramics') ),
       sup('ETS Express Inc', cat('ceramic') ),
       sup('Hit Promotional Products', cat('Ceramic Mugs') )
      ]],
     ['Drinkware Sets',
      [sup('Leeds', cat('Drinkware', 'Drinkware Sets') ),
       sup('Norwood', cat('DRINK', 'DRINKGIFT') )
      ]],
     ['Thermos Bottles',
      [sup('Starline', cat('Drinkware', 'Thermos Bottles') )
      ] ],
     ['Insulated Bottles',
      [sup('Leeds', cat('Drinkware', 'Insulated Bottles') ) ]],
     ['Mugs & Tumblers',
      [match('name', %w(tumbler mug), 1),
       match('name', 'flask'),
       sup('Leeds', cat('Drinkware', 'Mugs & Tumblers') ),
       sup('Lanco', cat('Drinkware', 'Travel Mugs & Tumblers') ),
       sup('Norwood', cat('DRINK', 'METAL') ),
       sup('High Caliber Line',
           match('name', 'Mug') ),
       sup('Bullet Line', cat('Drinkware', 'Mugs & Tumblers') ),
       sup('Logomark',
           cat('Mugs'),
           cat('Tumblers') ),
       sup('Sweda', cat('Drinkware', 'Travel Mugs') ),
       sup('Starline', cat('Drinkware', 'Travel Mugs'),
           cat('Drinkware', 'Travel Tumblers') )
      ],[
         ['Desk Mugs',
          [sup('Leeds', cat('Drinkware', 'Desk Mugs') )]],
         ['Ceramic Coffee Mugs',
          [match('name', 'coffee', 1),
           sup('Lanco', cat('Drinkware', 'Mugs') ),
           sup('Norwood', cat('DRINK', 'CERAMIC') )]],
        ]],
     ['Sport Bottles',
      [match('name', %w(bottle chill poly polly sports), 1),
       match('description', ['polyclear', 'sports bottle', 'squeeze bottle'], 1),
       sup('Leeds', cat('Drinkware', 'Plastic Sport Bottles') ),
       sup('Lanco',
           cat('Drinkware', 'Polycarbonate Bottles'),
           cat('Drinkware', 'Sports Bottles')),
       sup('Prime Line', cat('Drinkware', 'Sport Bottles') ),
       sup('Norwood',
           all(cat('DRINK', 'BOTTLE'),
               match('description', 'bottle') ) ),
       sup('Bullet Line', cat('Drinkware', 'Sports Bottles') ),
       sup('Starline', cat('Drinkware', 'Water Bottles') ),
       sup('ETS Express Inc', cat('h2go bottles') ),
       exclude(match('name', 'holder') )
      ]],
     ['Plastic Drinkware',
      [match(%w(name material), 'plastic', 1),
       sup('ETS Express Inc', cat('plastic') ) ] ],
     ['Glassware',
      [sup('Norwood', cat('DRINK', 'GLASS') ),
       sup('Starline', cat('Drinkware', 'Glassware') ),
       sup('ETS Express Inc', cat('glass') ),
      ] ],
     ['Specialty Drinkware',
      [sup('Bullet Line', cat('Drinkware', 'Specialty Drinkware'))
      ]],
    ] ],
 ['Food Gifts',
  [
  ],[
     ['Lollipop',
      [sup('The Magnet Group', cat('Innovations', 'Make It Pop!') ) ] ],
     ['Candy',
      [match('name', %w(jelly\ bean skittles))] ],
     ['Gourmet Food Gifts',
      [sup('Lanco', cat('Food Gifts', 'Gourmet Food Gifts') ) ]],
     ['Chocolate Foil Wrapped Pieces',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Foil Wrapped Pieces') ) ]],
     ['Chocolate Truffles',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Truffles') ) ]],
     ['Boxes with Gourmet Fills',
      [sup('Lanco', cat('Food Gifts', 'Boxes with Gourmet Fills') ) ]],
     ['Mints',
      [match('name', 'mint'),
       exclude(match('name', 'balm') ),
       sup('Lanco', cat('Food Gifts', 'Mints') ),
      sup('High Caliber Line',
          cat('Mints') )]],
     ['Coffee, Hot Chocolate, Ice Tea',
      [sup('Lanco', cat('Food Gifts', 'Coffee, Hot Chocolate, Ice Tea') ) ]],
     ['Candy Dispenser',
      [sup('Lanco', cat('Food Gifts', 'Candy Dispenser') ) ]],
     ['Novelty Chocolate',
      [sup('Lanco', cat('Food Gifts', 'Novelty Chocolate') ) ]],
     ['Chocolate Squares in Gift Sets',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Squares in Gift Sets') ) ]],
     ['Bags with Gourmet Fills',
      [sup('Lanco', cat('Food Gifts', 'Bags with Gourmet Fills') ) ]],
     ['Chocolate Bars',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Bars') ) ]],
     ['Custom Molded Chocolate',
      [sup('Lanco', cat('Food Gifts', 'Custom Molded Chocolate') ) ]],
     ['Filled Glass Apothecary Jar',
      [sup('Lanco', cat('Food Gifts', 'Filled Glass Apothecary Jar') ) ]],
     ['Gum',
      [sup('Lanco', cat('Food Gifts', 'Gum') ) ]],
     ['Bottled Water',
      [match('name', 'bottled water'),
       sup('Lanco', cat('Food Gifts', 'Bottled Water') ) ]],
     ['Tea Bags',
      [match('name', 'tea bag'),
       sup('Lanco', cat('Food Gifts', 'Tea Bags') ) ] ],
     ['Elopes',
      [match('name', 'elopes'),
       sup('Lanco', cat('Food Gifts', 'Elopes') ) ] ],
    ] ],
 ['Games & Toys',
  [sup('Leeds',
       cat('Games', 'Desktop Games'),
       cat('Games', 'Home Games')),
   sup('High Caliber Line', cat('Fun & Games')),
   sup('Prime Line', cat('Executive Toys') ),
   sup('Norwood',
       match('name', 'hockey'),
       cat('GOLF', 'FUN'),
       cat('GOLF', 'GAMES'),
       cat('FUN', 'GAMES') ),
   sup('Lanco',
       cat('Toys & Games', 'Toys'),
       cat('Tradeshow', 'Toys') ),
   sup('Logomark', cat('Executive Games') )
  ],[
     ['Electronic Games',
      [match('name', 'electr', 1),
       match('description', ['electr', 'batteries', 'LCD'], 1)]],
     ['Outdoor Games',
      [match('name', ['ball'], 1),
       match('name', ['flying disc', 'flyer', 'kite', 'football', 'rocket', 'boomerang', 'basketball', 'soccer']),
       exclude(match('name', %w(stress pen scripto))),
       exclude(sup('LogoIncluded', always)),
       sup('High Caliber Line',
           match('name', ['super ball', 'flying star', 'paddle ball']) ),
       sup('Gemline', cat('Gifts', 'Outdoor Fun') ),
       sup('Leeds', cat('Games', 'Outdoor Games') ),
       sup('Lanco', cat('Toys & Games', 'Hacki Balls') ),
       sup('Hit Promotional Products',
           all(cat('Leisure'),
               match('name', %w(ball disk disc rocket rope spin) ) ) ), ]],
     ['Mind Games',
      [match('name', %w(suduko sudoku brain perplex mind))
      ],[
         ['Puzzles',
          [match('name', 'puzzle'),
           sup('Prime Line',
               all(match('name','Magic'),
                   match('name', '&reg;'))) ]],
         ['Rubiks Cubes',
          [match(%w(name description), 'rubik'),
           match('name', 'rubi', 1),
           sup('Prime Line',
                    cat("Rubik's Cubes") ) ] ],
        ]],
     ['Decision Makers',
      [sup('Logomark', cat('Decision Makers') ) ] ],
     ['Magic',
      [sup('High Caliber Line', cat('Magic') ) ]],
     ['Travel Games',
      [sup('Leeds', cat('Games', 'Travel Games') ) ]],
     ['Stress Reliever',
      [match('name', 'stress', 1),
       match('name', 'stress reliever'),
       sup('Prime Line', cat('Stress Relievers') ),
       sup('Lanco',
           cat('Toys & Games', 'Stress Balls & Shapes'),
           cat('Tradeshow', 'Stress Balls & Shapes')),
       sup('Norwood', cat('HEALTH', 'STRESS') ),
       sup('Bullet Line', cat('Stress Relievers', 'Stress Relievers') ),
       sup('Hit Promotional Products',
           all(cat('Stress Relievers & Unique Specia'),
               match('name', 'stress') ) ),
       exclude(match('name', %w(pen scripto))),
      ] ],
     ['Dartboards',
      [match('name', 'dartboard') ]],
     ['Poker Sets',
      [match('name', 'poker') ]],
     ["Yo-Yo's",
      [match(%w(name description), ['Yo-Yo', 'Yo Yo', 'YoYo']),
       sup('Lanco', cat('Toys & Games', 'Yo-Yo\'s') )]],
    ] ],
 # Bad category
 ['Travel',
  [sup('Gemline', cat('Gifts', 'Travel') ),
   sup('High Caliber Line', cat('Travel') ),
   sup('Crown Products', cat('Travel') )
  ],[
     ['Luggage Tags',
      [match('name', 'luggage'),
       sup('Leeds', cat('Travel Gifts', 'Luggage Tags') ),
       sup('Lanco', cat('Travel / Personal Care', 'Luggage Tags') ),
       sup('Logomark', cat('Luggage Tags') ),
       sup('The Magnet Group', cat('Innovations', 'Luggage Tags') )
      ] ],
     ['Travel Accessories',
      [sup('Leeds',
           cat('Travel Gifts', 'Travel Accessories'),
           exclude(match('name', 'charge'))),
       sup('Bullet Line', cat('Travel, Health & Beauty', 'Travel Accessories') ),
       sup('Logomark', cat('Travel Accessories') )
      ] ],
     ['Phone Chargers',
      [match('name', ['charger', 'charging']),
       sup('Leeds',
           all(cat('Travel Gifts', 'Accessories'),
               match('name', 'charge'))),
       sup('LogoIncluded', cat('Solar Charger') ),
       sup('Starline', cat('Business', 'Mobile/Solar Power Packs') )
      ] ],
     ['Travel Clocks', duplicate(['Desktop Accessories', 'Clocks', 'Travel Clocks']) ],
     ['Travel Games', duplicate(['Games & Toys', 'Travel Games']) ],
     ['Travel Sets',
      sup('Leeds', cat('Travel Gifts', 'Gift Sets') ) ],
     ['Utility Kits',
      sup('Leeds', cat('Travel & Golf', 'Utility Kits') ) ],
     ['Travel Technology',
      sup('LogoIncluded',
          cat('Solar Charger'),
          cat('Executive Kit'))],
    ] ],
 ['Housewares',
  [
   match('name', 'door knob'),
  ],[
     ['Boxes & Waterproof Containers',
      sup('Lanco', cat('Bags / Containers', 'Boxes / Waterproof Containers'))],
     ['BBQ & Picnic',
      [match('name', %w(grill bbq picnic)),
       sup('Leeds', cat('Outdoor Living', 'Bbq & Picnic') ),
       sup('Norwood',
           cat('HOUSEWARES', 'PICNIC2'),
           cat('OUTDOOR', 'PICNIC') ),
       exclude(sup('LogoIncluded', always)),
       sup('Logomark',
           cat('BBQ Sets'),
           cat('Picnic') ),
       sup('Starline',
           cat('HomeStyles', 'BBQ'),
           cat('HomeStyles', 'Picnic') )
      ]],
     ['Beverage & Bar',
      [match('name', 'bar', 1),
       sup('Logomark', cat('Bar Accessories') )
      ] ],
     ['Decorations',
      [sup('Norwood', cat('HOUSEWARES', 'DECO') ) ]],
     ['Food Storage',
      [sup('Leeds', cat('Housewares', 'Food Storage') ),
       sup('Norwood', cat('HOUSEWARES', 'FOOD') ),]],
     ['Wine Collection',
      [match('name', 'wine'),
       sup('Leeds',
           cat('Housewares', 'Wine & Cheese'),
           cat('Housewares', 'Wine & Cheese Collection'),
           exclude(match('name', 'cheese')) ),
       sup('Norwood', cat('HOUSEWARES', 'WINE') ),
       sup('Logomark', cat('Wine Accessories') ),
       sup('Starline', cat('HomeStyles', 'Wine') )
      ] ],
     ['Cheese Collection',
      [sup('Leeds',
           cat('Housewares', 'Wine & Cheese'),
           cat('Housewares', 'Wine & Cheese Collection'),
           match('name', 'cheese') ),
       sup('Starline', cat('HomeStyles', 'Cheese') ) ] ],
     ['Kitchen',
      [match(%w(name description), 'kitchen'),
       match('name', ['measuring cup', 'measuring spoon', 'pizza cutter', 'spatula', 'basting', 'dishwasher', 'silicone glove', 'cream scoop', 'oven mitt', 'pot holder']),
       sup('Norwood', cat('HOUSEWARES', 'UTENSILS'))
      ],[
         ['Aprons',
          [match('name', 'apron'),
           sup('Prime Line', cat('Aprons') ) ]],
         ['Thermometers',
          [match('name', 'thermometer', 1)]],
         ['Toasters',
          [match('name', 'toaster') ]],
        ]],
     ['Cutlery',
      [sup('Leeds', cat('Housewares', 'Cutlery') ),
       sup('Starline', cat('HomeStyles', 'Knives/Boards') )
      ]],
     ['Salt & Pepper Shakers & Mills',
      [sup('Starline', cat('HomeStyles', 'Salt and Pepper Mills') )
      ] ],
     ['Tabletop & Serving',
      [sup('Leeds', cat('Housewares', 'Tabletop & Serving') ) ]],
     ['Vases',
      [match('name', 'vase'),
       sup('Norwood', cat('AWARD', 'VASE') ) ] ],
     ['Ornaments',
      [sup('The Magnet Group', cat('Crystal', 'Ornaments') ) ] ],
    ] ],
 ['Health & Personal Care',
  [sup('Gemline',
       cat('Gifts', 'Fitness/Wellness') ),
   sup('Norwood',
            match('name', 'growth chart'), # Only 40253
       all(cat('HEALTH'),
           match('name', 'thermometer')), # Only 40014
       all(cat('HEALTH'),
           match('name', ['flu', 'CPR'])), # Only 400693, 50049
       cat('HEALTH', 'SPA') ),
   sup('High Caliber Line', cat('Healthy Living') ),
   sup('Prime Line', cat('Health Wellness', 'Personal Care') ),
   sup('Hit Promotional Products', cat('Amenities') ),
   sup('Logomark', cat('Health and Fitness') )          
  ],[
     ['First Aid Kits',
      [match('name', 'first aid'),
       sup('Leeds',
           all(cat('Outdoor Living', 'Excursion'),
               match('name', 'first aid') ),
           cat('Safety & Auto', 'Personal Safety') ),
       sup('Lanco', cat('Health', 'First Aid Kit') ),
       sup('Norwood', cat('HEALTH', 'FIRSTAID') )]],
     ['Bandage Dispensers',
      [match('name' ,['bandage caddy', 'bandage dispenser', 'bandage case']),
       sup('Lanco', cat('Health', 'Bandage Dispenser') ),
       sup('Norwood', cat('HEALTH', 'BANDAGE') )]],
     ['Sanitizers',
      [match('name', ['hand cleaner', 'hand sanitizer']),
       sup('Lanco',
           cat('Hand Sanitizers', 'Hand Sanitizers'),
           cat('Candles / Bath / Body', 'Hand Sanitizers') ),
       sup('High Caliber Line', cat('Sanitizers') ),
       sup('Prime Line', cat('Health Wellness', 'Hand Sanitizer') )
      ],[ ['Hand Sanitizers',
           [match('name', 'hand', 1)] ]
        ] ],
     ['Stain Removers',
      [match('name', 'stain remove'),
       sup('Lanco', cat('Travel / Personal Care', 'Stain Removers'))
      ] ],
     ['Pedometers',
      [match('name', ['pedometer', 'step-meter', 'step meter']),
       sup('Leeds',
           all(cat('Outdoor Living', 'Excursion'),
               match('name', 'pedometer') ) ),
       sup('High Caliber Line', cat('Pedometer') ),
       sup('Lanco', cat('Travel / Personal Care', 'Pedometer') ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Pedometers') ),
       sup('Sweda', cat('Pedometers') )
      ] ],
     ['Fitness Sets',
      [all(match('name', %w(set kit), 1),
           match('name', %w(exercise fitness)) ),
       sup('Leeds', cat('Personal Wellness', 'Fitness') ) ]],
     ['Dental Products',
      [match('name', %w(floss toothbrush tooth\ brush toothpick))]],
     ['Pill Cases',
      [match(%w(name description), ['pill hold', 'pill case', 'pill box', 'pill tube', 'pill caddy']),
       sup('Lanco', cat('Health', 'Pill Cases') ),
       sup('Norwood', cat('HEALTH', 'PILLBOX') )]],
     ['Pill Cutters',
      [match('name', 'pill cut'),
       sup('Lanco', cat('Health', 'Pill Cutters') )]],
     ['Bug Repellant',
      [match('name', ['bug zapper', 'bug repellant']),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Bug Repellant') )
      ] ],
     ['Outlet Covers',
      [sup('Lanco', cat('Health', 'Outlet Cover') )]],
     ['Shoe Accessories',
      [match('name', %w(shoe callus)),
       sup('Lanco', cat('Travel / Personal Care', 'Shoe Items') ) ]],
     ['Soap',
      [match('name', 'soap') ] ],
     ['Wipes & Cleaning Cloths',
      [match('name', ['wipes', 'cleaning cloth', 'towelette']) ] ],
     ['Jump Rope',
      [match('name', 'jump rope') ] ],
     ['Fans',
      [match('name', ['mini fan', 'hand fan', 'personal fan']),
       sup('Lanco', cat('Travel / Personal Care', 'Fans') ),
       sup('High Caliber Line',
           all(cat('Toys & Games'),
               match('name', 'fan') ) ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Fans') ),
       sup('Sweda', cat('Unique', 'Fans') )
      ]],
     ['Mirrors',
      [match('name', 'mirror'),
       sup('Lanco', cat('Travel / Personal Care', 'Mirrors') ) ]],
     ['Lint Brushes',
      [match(%w(name description), ['lint brush', 'lint roller']),
       sup('Lanco', cat('Travel / Personal Care', 'Lint Brushes') ) ]],
     ['Brush & Combs',
      [sup('Lanco', cat('Travel / Personal Care', 'Brush & Combs') ) ]],
     ['Sewing Kits',
      [match('name', ['sewing kit', 'mending']),
       sup('Lanco', cat('Travel / Personal Care', 'Sewing Kits') ) ]],
     ['Dental Products',
      [sup('Lanco', cat('Travel / Personal Care', 'Dental Products') ) ]],
     ['Sun Kits',
      [sup('Lanco', cat('Sun / Outdoors / Sports', 'Sun Kits') ) ]],
     ['Lip Balm',
      [match('name', %w(lipbalm lip\ balm)),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Lipbalm') ),
       sup('High Caliber Line', cat('Lip Balm') )
      ]],
     ['Outdoor Kits',
      [sup('Lanco', cat('Sun / Outdoors / Sports', 'Outdoor Kits') ) ]],
     ['Sunblock',
      [match('name', %w(sunscreen sun\ screen sunblock sun\ block)),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Sunscreen') ),
       sup('Norwood', cat('HEALTH', 'SUN') ) ]],
     ['Lotions',
      [match('name', 'lotion') ] ],
     ['Manicure',
      [match('name', ['manicure', 'nail file', 'emery board', 'pedicure']) ]],

     ['Info Guide',
      [sup('Norwood', cat('HEALTH', 'INFOGUIDE')) ]],

    ] ],

 ['Personal Accessories',
  [
  ],[
     ['Umbrellas & Rainwear',
      [match('name', 'umbrella'),
       sup('Leeds', duplicate(['Umbrellas'], 'supplier_categories')),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Umbrellas') ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Umbrellas') ),
       sup('Sweda', cat('Umbrellas') ),
      ],[
         ['London Fog',
          [sup('Sweda', cat('BRANDS', 'London Fog') ) ]],
        ] ],
     ['PDAs & Phone Holders',
      [match('name', ['phone holder', 'phone stand']),
       sup('Lanco', cat('Bags / Containers', 'PDA Holder') ),
       sup('LogoIncluded', cat('Phone Cases') ) ] ],
     ['Eyeglass Accessories',
      [],[
          ['Eyeglass Cases',
           [match('name', /((sun)|(eye)| )glass.+case/) ] ],
          ['Eyeglass Straps',
           [match('name', /((sun)|(eye)| )glass.+strap/) ] ],
          ['Eyeglass Clips',
           [match('name', /((sun)|(eye)| )glass.+clip/) ] ],
         ] ],
     ['Micro Fiber Cloth',
      [match('name', 'micro fiber'),
       sup('High Caliber Line', cat('Micro Fiber') ) ] ],
     ['Sun Glasses',
      [match('name', 'sunglasses'),
       exclude(match('name', 'case')),
       sup('High Caliber Line', cat('Sunglasses') ),
       sup('Starline', cat('Performance Eyewear', 'Outdoor Sport') )
      ] ],
     ['Safety Glasses',
      [sup('Starline', cat('Performance Eyewear', 'Safety') )
       ] ],
     ['Badge Holders',
      [match('name', %w(badge ident)),
       match('description', 'badge holder'),
       exclude(match('name', 'bag')),
       sup('Lanco', cat('Badge Holders / Ribbons', 'Badge Holders') ),
       sup('High Caliber Line',
           cat('Badge Holders'),
           cat('Office', 'Badge Holders')),
       sup('Norwood', cat('OFFICE', 'BADGE') ),
       sup('Bullet Line', cat('Key Tags & Badge Holders', 'Badge Holders') ),
       sup('Logomark', cat('Badge Holders') ),
       exclude(match('name', 'lanyard'))]],
     ['Lanyards',
      [match('name', 'lanyard'),
       sup('Lanco', cat('Badge Holders / Ribbons', 'Badge Holder Accessories') ),
       sup('High Caliber Line',
           cat('Lanyards'),
           cat('Lanyards', 'Econo Lanyards'),
           cat('Lanyards', 'Factory Direct Lanyards'),
           cat('Lanyards', 'Fast Track Lanyards') )
      ],[
         ['Eco Friendly Lanyards',
          [sup('High Caliber Line', cat('Lanyards', 'Eco Friendly Lanyards') ) ] ]
        ] ],
     ['Dog Tags',
      [sup('Lanco', cat('Badge Holders / Ribbons', 'Dog Tags') )]],
     ['Carabiners',
      [match('name', 'carabiner'),
       sup('Lanco', cat('Carabiners / Key Chains', 'Carabiner') ),
       sup('Leeds', cat('Keychains Keylights & Carabiner', 'Carabiners') ),
       sup('High Caliber Line', cat('Carabiners') ),
       sup('Bullet Line',
           cat('Key Tags & Badge Holders', 'Carabiners'),
           cat('Lighting', 'Carabiners') ),
       sup('The Magnet Group', cat('Innovations', 'Carabiners') )
      ]],
     ['Key Chains',
      [match(%w(name description), ['key chain', 'keychain', 'key holder', 'key tag', 'key ring']),
       sup('High Caliber Line',
           cat('Key Chains'),
           cat('Key Chains', 'Alcraft Key Chains')),
       sup('Prime Line', cat('Key Tags') ),
       sup('Lanco',
           cat('Carabiners / Key Chains', 'Keychains'),
           cat('Tools / Knives', 'Keychains') ),
       sup('Norwood', cat('AUTO', 'KEYCHAIN') ),
       sup('Leeds', cat('Keychains Keylights & Carabiner', 'Keychains') ),
       sup('Bullet Line',
           cat('Stress Relievers', 'Stress Reliever Keychains'),
           cat('Key Tags & Badge Holders', 'Key Tags')),
       sup('Crown Products', cat('Key Chains') ),
       sup('Logomark', cat('Key Rings') ),
       sup('Sweda',
           cat('Key Tags'),
           cat('Keychains') ),
       sup('The Magnet Group',
           cat('Innovations', 'Keytags'),
           cat('Innovations', 'Keychains') )
      ],[
         ['Bottle Opener Key Chains',
          [match('name', 'opener', 1),
           sup('Bullet Line', cat('Key Tags & Badge Holders', 'Bottle Openers') ) ]],
         ['Key Chains with Light',
          [match('name', 'light', 1),
           match('name', /LED.+?light.+?key/i),
           exclude(match('name', 'limelight')),
           sup('Leeds', cat('Keychains Keylights & Carabiner', 'Keylights') ),
           sup('Bullet Line', cat('Lighting', 'Key Lights') ),
           sup('The Magnet Group', cat('Innovations', 'Key Lights') ),
           sup('Starline', cat('Flashlights', 'LED Keylights') ),
          ] ],
         ['Flash Drive Key Chains',
          [sup('LogoIncluded', match(%w(name description), ['key chain', 'keychain', 'key holder']))]],
        ] ],
     ['Wallets',
      [match('name', %w(wallet checkbook)),
       match('description', ['travel wallet', 'leather organizer', 'passport jacket']),
       sup('Leeds',
           cat('Travel Gifts', 'Travel Wallets') ),
      ]],
     ['Money Clips',
      [match('name', ['money clip', 'money band', 'credit card holder']),
       sup('Logomark', cat('Money Clips') )
      ] ],
     ['Wristbands',
      [match(%w(name description), [/wrist.*band/, 'bracelet']) ] ],
     ['Watches',
      [sup('Leeds',  ),
       sup('Logomark',
           cat('Classic Watches'),
           cat('Fashion Watches') ),
      ],[
         ['Executive Watches',
          [sup('Sweda', cat('Watches', 'Analog Executive') ), ]],
         ['Sport Watches',
          [match('name', 'sport', 1),
           sup('Logomark', cat('Sport Watches') ),
           sup('Sweda',
               cat('Watches', 'Analog Sport'),
               cat('Watches', 'Digital') ),
          ] ],
        ] ],
     dup('Travel', 'Personal Travel'),

    ] ],

 ['Recreation',
  [sup('High Caliber Line', cat('Sports and Recreation') ),
   sup('Bullet Line', cat('Fitness & Recreation', 'Summer & Outdoor Items')),
  ],[
     ['Binoculars & Telescopes',
      [match('name', %w(binocular telescope monocular)),
       sup('Leeds', cat('Outdoor Living', 'Binoculars') ),
       sup('High Caliber Line', cat('Binoculars') ),
       sup('Sweda', cat('Binoculars') )
      ] ],
     dup('Games & Toys', 'Outdoor Games'),
     dup('Health & Personal Care', 'First Aid Kits'),
     dup('Health & Personal Care', 'Pedometers'),     
     ['Compasses',
      [match('name', 'compass'),
       sup('Leeds',
           all(cat('Outdoor Living', 'Excursion'),
               match('name', 'compass') ) ) ]],
     ['Beach ware',
      [match('name',%w(beach)),
       match('name', 'towel', 1),
       sup('Leeds', cat('Towels', 'Beach Towels') ),
       sup('Prime Line', cat('Health Wellness', 'Sport Towels') )
      ]],
     ['Golf',
      [match('name', 'golf'),
       sup('Leeds', cat('Luggage & Golf', 'Golf') ) ,
       sup('Norwood', cat('GOLF') ),
       sup('Crown Products', cat('Golf') ),
       sup('Logomark', cat('Golf Gifts' ) )
      ],[
         ['Ladies Golf',
          [sup('Norwood', cat('GOLF', 'LADIES') ) ] ],
         ['Golf Balls',
          [match('name', 'balls', 1),
           sup('Lanco', cat('Golf', 'Golf Balls') ),
           sup('Norwood', cat('GOLF', 'GOLFBALL') ) ] ],
         ['Golf Club',
          [sup('Norwood', cat('GOLF', 'GOLFCLUB') ) ] ],
        ['Golf Kits',
          [match('name', 'kit', 1),
           match('name', 'putter'),
           sup('Lanco', cat('Golf', 'Golf Kits') ),
           sup('Norwood', cat('GOLF', 'EVENT') )]],
         ['Golf Tags',
          [match('name', 'tag', 1),
           sup('Lanco', cat('Golf', 'Golf Tags') ) ]],
         ['Golf Towels',
          [match('name', 'towel', 1),
           sup('Lanco', cat('Golf', 'Golf Towels') ),
           sup('Leeds', cat('Towels', 'Golf Towels') )]],
         ['Tees, Ball Markers & Divot Tools',
          [match('name', ['tees', 'ball marker'], 1),
           match('name', 'divot'),
           sup('Leeds',
               all(cat('Travel & Golf', 'Golf'),
                   match('name', 'green'))),
           sup('Lanco', cat('Golf', 'Tees, Markers & Divot Tools') ),
           sup('Norwood', cat('GOLF', 'TEE') )]],
        ] ],
     ['Kites',
      [match('name', 'kite')] ],
     ['Camping',
      [match('name', 'tent') ]],
     ['Outdoor Seating',
      [match('name', ['chair', 'recliner']),
       match(%w(name description), ['stadium seat', 'stadium cushion', 'stadium kushion', 'outdoor lounger', 'seat cushion', /chair.+fold/i]),
       all(match('name', %w(chair seat)), match('description', %w(outdoor beach sporting stadium))),
       exclude(match('name', 'stress reliever')),
       sup('Norwood', cat('OUTDOOR', 'CHAIRS') ),
       sup('Lanco',
           cat('Sun / Outdoors / Sports', 'Cushions'),
           cat('Sun / Outdoors / Sports', 'Seats') ) ] ],
     ['Excursion',
      [sup('Leeds', cat('Outdoor Living', 'Excursion') ) ] ],
    ] ],

 ['Stationery',
  [sup('Gemline',
       ['New', 'Clearance'].collect do |name|
         cat('Padfolios', name)
       end),
   sup('Hit Promotional Products', cat('Portfolios & Jotters') ),
   sup('The Magnet Group', cat('Bag Factory', 'Stationery & Writing') )
  ],[
     ['Jotters',
      [match('name', 'notepad'),
       match('name', 'jotter'),
       sup('Leeds',
           cat('Stationery', 'Jotters'),
           cat('Stationery', 'Notebooks')),
       sup('Norwood', cat('MEETING', 'JOTTERS') ),
       sup('Prime Line',
           all(cat('Computer Bags / Portfolios'),
               match('name', 'pad') ) ),
       sup('Lanco',
           cat('Journals / Portfolios', 'Notebooks'),
           cat('Journals / Portfolios', 'Memo Pads')),
       sup('High Caliber Line',
           match('name', 'notebook') ),
       sup('Bic Graphics',
           match('supplier_num', /^((NC4P57)|(NC57(ECO)?)|(NPP?57))$/),
           exclude(match('name', 'notepad'))),
       sup('Sweda', cat('Stationery', 'Jotters') )
      ]],
     ['Journals',
      [match('name', 'journal'),
       sup('Leeds',
           cat('Journalbooks', 'Bound'),
           cat('Journalbooks', 'Spiral') ),
       sup('Lanco', cat('Journals / Portfolios', 'Journal Books') ),
       sup('Prime Line', cat('Office', 'Journal Notebooks') ),
       sup('Bullet Line', cat('Stationery', 'Notebooks') ),
       sup('Sweda', cat('Stationery', 'Journals & Notebooks') ),
      ]],
     ['Padfolios & Writing Pads',
      [match('name', 'padfolio'),
       sup('Leeds', cat('Stationery', 'Padfolios & Writing Pads') ),
       sup('Gemline',
           cat('Padfolios', 'Writing Pads'),
           match('name', ['writing pad', 'tech organizer', 'e-organizer']) ),
       sup('Lanco', cat('Journals / Portfolios', 'Portfolios') ),
       sup('Norwood',
           cat('MEETING', 'PAD'),
           cat('MEETING', 'FOLDERS')),
       sup('Bullet Line', cat('Stationery', 'Portfolios') ),
       sup('Logomark', 
           cat('Letter Padfolios' ),
           cat('Zip Padfolios') ),
       sup('Sweda', cat('Stationery', 'Portfolios') ),
       sup('Starline', cat('Business', 'Portfolios/Padfolios') ),
       sup('Prime Line', cat('Desktop', 'Padfolios') ),
      ],[
         ['Jr. Padfolios',
          [match('name', 'jr', 1),
           sup('Norwood', cat('MEETING', 'JUNIORS') ),
           sup('Bic Graphics', match('supplier_num', 'SHAJ1') ),
           sup('Gemline', cat('Padfolios', 'Junior') ),
           sup('Logomark',
               cat('Mini Padfolios'),
               cat('Junior Padfolios') )
          ] ],
         ['Leather Padfolios',
          [sup('Gemline', cat('Padfolios', 'Leather') ),
          ]],
         ['Recycled Pads',
          [match(%w(name description), 'recycle', 1) ]],
        ] ],
     ['Planners',
      [sup('Leeds', cat('Stationery', 'Planners') ) ]],
     ['Ringbinders',
      [match('name', ['ringfolio', 'ringbinder']),
       sup('Leeds', cat('Stationery', 'Ringbinders') ),
       sup('Gemline', cat('Padfolios', 'Ringbinders') )]],
     ['Postcards & Greeting Cards',
      [sup('The Magnet Group', cat('SmartLine') ) ] ],
    ] ],

 ['Tools',
  [sup('Leeds',
       cat('Tools & Lighters', 'Tools') ),
   sup('PrimLine', cat('Tools') ),
   sup('Norwood', cat('AUTO', 'TOOLS') ),
   sup('High Caliber Line', cat('Tools') ),
   sup('Hit Promotional Products', cat('Carabiners, Tools, Lights & Keytags') ),
   sup('Crown Products',
       cat('Tools'),
       cat('Tools, Gifts') ),
   sup('Logomark', cat('Hand Tools') ),
   sup('Sweda', cat('Tools') ),
   sup('The Magnet Group', cat('Innovations', 'Tools') )
  ],[
     dup('Tools / Knives', 'Ice Scraper'),
     ['Bag Clips',
      [match('name', 'bag clip'),
       sup('Lanco', cat('Tools / Knives', 'Bag Clips') ),
       sup('Norwood',
           all(cat('HOUSEWARES', 'UTENSILS'),
               match('name', 'clip') ) ),
       sup('Bullet Line',
           all(cat('Desktop'),
               match('name', 'clip') ) )]],
     ['Bottle Openers',
      [match('name', 'bottle opener'),
       sup('High Caliber Line',
           cat('Bottle Openers'),
           match('description', 'bottle opener' )),
       sup('Lanco', cat('Tools / Knives', 'Bottle Opener') ),
       sup('Bullet Line', cat('Keytags & Badge Holders', 'Bottle Openers') ),
       sup('Logomark', cat('Bottle Openers') )
      ]],
     ['Jar Openers',
      [match('name', 'jar opener') ]],

     ['Flashlights',
      [match('name', /(^|\s+)LED(\s+|$)/),
       match(%w(name description), %w(flashlight fingerlight)),
       sup('High Caliber Line', cat('Flashlights') ),
       sup('Lanco', cat('Tools / Knives', 'Flashlights') ),
       sup('Prime Line', match('name', 'torch') ),
       sup('Norwood', cat('AUTO', 'FLASH') ),
       sup('Bullet Line', cat('Lighting', 'Flashlights') ),
       sup('Logomark', cat('Flashlights') ),
       sup('Sweda',
           cat('Flashlights', 'Metal'),
           cat('Flashlights', 'Plastic') ),
       sup('The Magnet Group', cat('Innovations', 'Flashlights') ),
      ],[
         ['Emergency Flashlights',
          [sup('Leeds', cat('Flashlights', 'Emergency & Safety Lights') ) ]],
         ['Everyday Flashlights',
          [sup('Leeds', cat('Flashlights', 'Everyday Lights') ) ]],
         ['Dynamo Flashlights',
          [sup('Leeds', cat('Flashlights', 'Dynamo Lights') ),
           sup('Sweda', cat('Flashlights', 'Dynamos') )
          ] ],
         ['LED Flashlights',
          [match('name', /(^|\s+)L\.?E\.?D\.?(\s+|$)/, 1),
           sup('Starline', cat('Flashlights', 'LED Flashlights') )
          ]],
         ['Specialty Flashlights',
          [sup('Leeds', cat('Flashlights', 'Specialty Lights') ) ]],
         ['Lanterns',
          [sup('Starline', cat('Flashlights', 'Lanterns') ) ] ]
        ] ],
     ['Knives',
      [match(%w(name description), %w(knive knife cutter)),
       exclude(match(%w(name description), /Cutter.+Buck/i)),
       sup('Lanco', cat('Tools / Knives', 'Knives') ),
       sup('Norwood', cat('AUTO', 'KNIVES') ),
       sup('Bullet Line', cat('Tools', 'Knives') ),
       sup('Logomark', cat('Knives') ),
       sup('Starline', cat('Tools', 'Knives') )
      ],[
         ['Wenger Knives',
          [sup('Leeds', cat('Tools & Lighters', 'Wenger Knives') ) ]],
        ] ],
     ['Lighters',
      [match('name', /(^|\s)lighter/),
      ],[
         ['Zippo Lighters',
          [sup('Leeds', cat('Tools & Lighters', 'Zippo Lighters') )]],
         ['BIC Lighters',
          [sup('Bic Graphics',
               match('supplier_num', /^((J\d{2})|((MP)?LTR))$/) )]],
        ] ],
     ['Pliers',
      [match('name', 'pliers', 1)
      ] ],
     ['Work Gloves',
      [sup('Starline', cat('Tools', 'Work Gloves') )
      ] ],
     ['Screwdrivers',
      [match(%w(name description), %w(screwdriver screw\ driver)),
       sup('Lanco',
           all(cat('Tools / Knives', 'Screwdriver & Tool Set'),
               match('name', 'screwdriver') ) ) ]],
     ['Tape Measures',
      [match(%w(name description), 'tape measure'),
       sup('Lanco', cat('Tools / Knives', 'Tape Measure') ),
       sup('Norwood', cat('AUTO', 'MEASURE') ),
       sup('Bullet Line', cat('Tools', 'Tape Measures') ),
       sup('Logomark', cat('Tape Measures') ),
       sup('Starline', cat('Tools', 'Measuring Tools') )
      ]],
     ['Tool Sets',
      [match('name', ['tool set', 'tool kit', 'gift set'], 1),
       sup('Leeds',
           all(cat('Tools & Lighters', 'Tools'),
               match('name', ['tool set', 'tool kit']) ) ),
       sup('Lanco',
           all(cat('Tools / Knives', 'Screwdriver & Tool Set'),
               match('name', 'set') ) ),
       sup('Gemline',
           all(cat('Gifts', 'Home Improvement'),
               match('name', %w(kit set)) ) ),
       sup('Logomark', cat('Tool Sets') ),
       sup('Starline',
           cat('Tools', 'Tool Sets/Bags'),
           exclude(match('name', 'bag')) )
      ]],
     ['Multi Tools',
      [match('name', 'multi-', 1),
       sup('Leeds',
           all(cat('Tools & Lighters', 'Tools'),
               match('name', 'multi-tool') ) ),
       sup('Lanco',
           all(cat('Tools / Knives', 'Screwdriver & Tool Set'),
               match('name', 'pocket tool')) ),
       sup('Bullet Line', cat('Tools', 'Multi-Function Tools') ),
       sup('Starline', cat('Tools', 'Multi Tools') )
      ],[
         ['Leatherman',
          [sup('Sweda', cat('BRANDS', 'Leatherman') ) ]],
        ] ],
     ['Locks',
      [match('name', ' lock') ]],
    ] ],

 ['Writing',
  [ sup('High Caliber Line', cat('Writing Instruments') ),
    sup('Norwood', cat('WRITE', 'PENCIL') ),
    sup('Hit Promotional Products', cat('Writing Instruments') ),
    sup('Crown Products', cat('Writing Instruments') ),
  ],[
     ['Highlighters',
      [match('name', 'highlighter', 1),
       match('description', ['hi-lighter', 'highlighters']),
       sup('High Caliber Line', cat('Writing Instruments', 'Highlighters, Markers and Acceso') ),
       sup('Lanco',
           cat('Writing Instruments', 'Highlighters'),
           cat('Office / Computer Essentials', 'Highlighters')),
       sup('Prime Line',
           cat('Writing Instruments', 'Highlighter Pens'),
           match('name', ['tri-liter', 'bi-liter']) ),
       sup('Norwood',
           all(match('name', ['highlighter', 'combo writer']),
               cat('WRITE', 'PENCIL') ) ),
       sup('Bullet Line', cat('Writing Instruments', 'Highlighters') ),
       sup('Bic Graphics',
           cat('Writing Instruments', 'Highlighter'),
           match('supplier_num', /^((BL)|(MRGE))/) ),
       sup('Logomark', cat('Highlighters') ),
       sup('Sweda', cat('Writing Instruments', 'Highlighters') )
       ]],
     ['Markers',
      [match('name', 'marker', 1),
       sup('Bic Graphics',
           cat('Writing Instruments', 'Marker'),
           match('supplier_num', /^MRP[GR]$/) ),
     ]],
     ['Pencils',
      [match('name', 'pencil'),
       sup('Gemline', cat('Writing Instruments', 'Pencils') ),
       sup('Bic Graphics',
           cat('Writing Instruments', 'Pencil'),
           match('supplier_num', /(^BP)|(PMR)|(PEVECO)/) ),
       sup('Logomark', cat('Pencils') ),
       exclude(sup('Ash City', always))
      ]],
     ['Pens',
      [match('name', /pens?($|\s)/i, 1),
       sup('Leeds', cat('Plastic Pens', 'Value Pens And Highlighters') ),
       sup('High Caliber Line',
           cat('Writing Instruments', 'Pens'),
           cat('Writing Instruments', 'Executive Pens') ),
       sup('Lanco',
           cat('Writing Instruments', 'Stick Pens'),
           cat('Writing Instruments', 'USA Made Pens') ),
       sup('Prime Line',
           match('name', %w(pen writer)) ),
       sup('Norwood',
           match('name', 'syringe pen'), # only 40017
           cat('WRITE', 'GIFTPEN'),
           cat('WRITE', 'PEN50'),
           cat('WRITE', 'PEN150')),
       sup('Bullet Line', cat('Writing Instruments', 'Plastic Pens') ),
       sup('Sweda',
           cat('Writing Instruments', 'Plastic'),
           cat('Writing Instruments', 'Metal') ),
       sup('The Magnet Group', cat('Innovations', 'Pens') ),
      ],[
         ['Carabiner Pens',
          [match(%w(name description), 'carabiner', 1),
           sup('Logomark', cat('Carabiners') ),
          ] ],
         ['Light Up Pens',
          [match('name', /(^|\s)light/, 1),
           sup('Bullet Line', cat('Writing Instruments', 'Light-up Pens') ),
           sup('Logomark', cat('Light Pens') ),
           sup('Sweda', cat('Writing Instruments', 'Light-Up & Laser') )
          ]],
         ['Pen Gift Boxes',
          [match('name', ['gift box', 'pen box'], 1),
           sup('Bullet Line', cat('Writing Instruments', 'Gift Boxes for Pens') ) ] ],
         ['Branded Pens',
          [sup('Leeds', cat('Metal Pens', 'Branded Pens') ) ]],
         ['Multi Function Pens',
          [match('name', %w(usb laser), 1),
           sup('Leeds', cat('Metal Pens', 'Multi Function Pens') ),
           sup('High Caliber Line', cat('Writing Instruments', 'Laser Pointers & Light Up') ),
           sup('Lanco', cat('Writing Instruments', 'Pens with Staple Remover') ),
           sup('Bic Graphics',
               match('supplier_num', /^((4C)|(4CL)|(B3)|(TWOS))$/) ),
           sup('Logomark', cat('Multi-Function Pens') )
          ]],
         ['Pen Sets',
          [sup('Leeds', cat('Metal Pens', 'Pen Sets') ),
           sup('Gemline', cat('Writing Instruments', 'Pen Sets') ),
           sup('Logomark',
               cat('Pen Sets'),
               cat('Rollerball Ballpoint Sets') )]],
         ['Scripto Plastic Pens',
          [sup('Leeds', cat('Plastic Pens', 'Scripto Plastic Pens') ) ]],

         ['Click Pens',
          [match('name', 'click', 1),
           match('name', 'click pen'),
           match('description', 'plunger action'), # Hit
           sup('Prime Line',
               match('description', ['click action', 'click-action'])),
           sup('Gemline', cat('Writing Instruments', 'Clicks') ),
           sup('Lanco', cat('Writing Instruments', 'Click Pens') ),
           sup('Bic Graphics',
               match('supplier_num', [/^(DC)?MC/, /^((CS)|(TS)|(TWP)|(CL))/]))
          ]],
         ['Roller Ball Pens',
          [match('name', 'roller', 1),
           match('name', ['rollerball', /Roller Ball/]),
           sup('Gemline',
               cat('Writing Instruments', 'Roller Balls'),
               cat('Writing Instruments', 'Roller Needle')),
           sup('Leeds', cat('Metal Pens', 'Roller Ball Pens') ),
           sup('Bic Graphics',
               cat('Writing Instruments', 'Rollerball'),
               match('supplier_num', /^((GR)|(T537R)|(XS)|(Z4)|(PLCCR))/) ),
           sup('Logomark',
               cat('Rollerball Pens'),
               cat('Rollerball Ballpoint Sets')) 
          ]],
         ['Ballpoint Pens',
          [match(%w(name description), 'ballpoint'),
           sup('Leeds', cat('Metal Pens', 'Ballpoint Pens') ),
           sup('Gemline', cat('Writing Instruments', 'Ballpoint') ),
           sup('Bic Graphics', cat('Writing Instruments', 'Ballpoint') ),
           sup('Logomark',
               cat('Ballpoint Pens'),
               cat('Rollerball Ballpoint Sets'))]],
         ['Two-Piece Stic Pens',
          [match('name', 'stick pen'),
           sup('Bic Graphics',
               match('supplier_num', [/^STYL/, /^RS/, /^BC/, 'ATS']) )
          ]],
         ['Gel Pens',
          [match('name', 'gel', 1),
           sup('Gemline', cat('Writing Instruments', 'Gel') ),
           sup('Bullet Line', cat('Writing Instruments', 'Gel Pens') ),
           sup('Bic Graphics',
               cat('Writing Instruments', 'Gel Pen'),
               match('supplier_num', 'GEL') ),
           sup('Sweda', cat('Writing Instruments', 'Gel') )
          ]],
         ['Metal Pens',
          [sup('Bullet Line',
               cat('Writing Instruments', 'Metal Pens'),
               cat('Writing Instruments', 'Metal Pen') ),
           sup('Prime Line', cat('Writing Instruments', 'Metal Pens') )
          ], [
              ['Aluminum Pens',
               [match('material', 'Aluminum', 2)
               ] ],
              ['Brass Pens',
               [match('material', 'brass', 2)
               ] ],
              ['Stainless Steel Pens',
               [match('material', 'stainless', 2),
                sup('Gemline',
                         cat('Writing Instruments', 'Stainless') ) ] ],
              ['Gold Plated Pens',
               [match('description', /\d{2}K gold/i),]],
             ] ],
         ['Twist Pens',
          [match(%w(name description), 'twist', 1),
           sup('Prime Line',
               match('description', 'twist-action')),
           sup('Gemline', cat('Writing Instruments', 'Twists') ),
           sup('Lanco', cat('Writing Instruments', 'Twist Pens') )]],
         ['Recycled Pens',
          [match(%w(name description), 'recycle', 1),
           sup('Gemline', cat('Writing Instruments', 'Recycled') ) ]],
         ['Specialty Pens',
          [sup('Lanco', cat('Writing Instruments', 'Specialty Pens') ) ]],
         ['Pen Holders & Cases',
          [sup('Lanco', cat('Writing Instruments', 'Pen Holder/Cases') ),
           sup('Norwood',
               all(match('name', %w(box pouch)),
                   cat('WRITE', 'GIFTPEN') ) )]],
         ['Eco Friendly Pens',
          [sup('High Caliber Line', cat('Writing Instruments', 'Eco Friendly Pens') ) ] ],
         ['Magnetic Pens',
          [match('name', 'magnet', 1),
           sup('The Magnet Group', cat('Innovations', 'Magnetic Pens') ) ] ],
        ] ],
    ] ],

 ['Other',
  [
  ],[
     ['Dog Collars & Leashes',
      [match('name', %w(dog\ collar leashe)),
       sup('High Caliber Line',
           cat('Dog Collars & Leashes'),
           cat('Lanyards', 'Dog Leashes Lanyards') ) ] ],
     ['Pet Accessories',
      [match('name', /(^|\s)Pets?($|\s)/i), ]],
     ['Light Ups',
      [sup('High Caliber Line', cat('Light Up') )
      ],[
         ['Light Up Pens',
          [match('name', 'pen', 1) ] ],
         ['Other Light Ups',
          [sup('High Caliber Line', cat('Light Up', 'Others') ) ]],
         ['Light Up Necklaces',
          [sup('High Caliber Line', cat('Light Necklaces') ) ]],
         ['Light Up Buttons',
          [match('name', 'button', 1)]],
        ]],
     ['Neoprene',
      [match('description', 'neoprene'),
       sup('High Caliber Line', cat('Neoprene') ) ]],
     ['Ribbons',
      sup('Lanco', cat('Badge Holders / Ribbons', 'Custom Imprinted Ribbons') ) ],
     ['Blankets',
      [match('name', 'blanket'),
       sup('Norwood', cat('OUTDOOR', 'BLANKETS') ),
       sup('Leeds', cat('Blankets', 'Blanket') ),
       sup('Prime Line', cat('Blankets') ),
       sup('Logomark', cat('Blankets') ),
       sup('Sweda', cat('Blankets') ),
       sup('The Magnet Group', cat('Bag Factory', 'Blankets') ),
       sup('Starline', cat('Lifestyles and Golf', 'Blankets') ),
      ] ],
     ['Whistles',
      [match('name', 'whistle') ]],
     ['Gardening',
      [match('name', 'garden') ]],
     ['Gift Tins',
      [sup('Logomark', cat('Gift Tins') ) ] ],
     ['Stopwatches & Timers',
      [sup('Sweda', cat('Stopwatches & Timers') ) ] ],
    ] ],

 ['Ecologically Friendly',
  [sup('High Caliber Line', cat('Eco Friendly Products') ),
   sup('Logomark', cat('Sustainable') )

  ],[
     ['Recycled',
      [sup('Gemline', cat('Living Green', 'Recycled') )
      ],[
         dup('Bags', 'Backpacks', 'Recycled Backpacks'),
         dup('Bags', 'Business Bags', 'Recycled Business Bags'),
         dup('Bags', 'Duffel Bags', 'Recycled Duffel Bags'),
         dup('Bags', 'Tote Bags', 'Recycled & Organic Totes'),
         dup('Coolers', 'Recycled Coolers'),
         dup('Housewares', 'Beverage & Bar', 'Recycled Bar Sets'),
         dup('Drinkware', 'Recycled Drinkware'),
         dup('Stationery', 'Jotters', 'Recycled Jotters'),
         dup('Stationery', 'Journals', 'Recycled Journals'),
         dup('Stationery', 'Padfolios & Writing Pads', 'Recycled Pads'),
         dup('Writing', 'Pens', 'Recycled Pens'),
        ]],
    ] ],
     
]
  end
end
