# -*- coding: utf-8 -*-
class NewCategoryTransform
  def apply_rules(record)
#    puts "Apply Rule: #{record['supplier_num']}"
    record['categories'] ||= []
    @rules.each do |rule, category|
      if res = rule.call(record, category)
        record['categories'] += res
        record['categories'].uniq!
      end
    end

    # Remove parent categories after all rules to work correct with exclude
    record['categories'].delete_if do |sub|
      record['categories'].find { |s| (s.length > sub.length) && (s[0...(sub.size)] == sub) }
    end

    if Rails.env.production?
      record['categories'] = [['Other']] if record['categories'].empty?
    else
      record['categories'] = record['categories'] + record['categories'].collect { |cat| ['YBySupplier', @supplier] + cat }

      unused_categories = record['supplier_categories'] - @used_categories   
      unused_categories << ['AAA'] if record['categories'].empty?
      unless unused_categories.uniq.empty?
        record['categories'] = record['categories'] + unused_categories.collect { |cat| ['XUnOrganized', @supplier] + cat }
      end

      record['categories'] = record['categories'] + (record['supplier_categories'] - unused_categories).collect { |cat| ['ZSuppliers', @supplier] + cat }
    end
  end

  attr_reader :supplier
  def initialize(supplier)
    @supplier = supplier
    @rules = []
    @used_categories = []
    process_category(data, [])
  end

private
  def process_category(records, parent_category)
    records.each do |name, rules, sub_records|
      category = parent_category + [name]
      [rules].flatten.compact.each { |r| @rules << [r, category] }
      process_category(sub_records, category) if sub_records
    end
  end

  def supplier(name, *rules)
    return nil unless name == @supplier
    rules.flatten.compact
  end

  def category(*cat)
    @used_categories << cat unless @used_categories.include?(cat)
    Proc.new do |record, match_category|
      [match_category] if record['supplier_categories'].find { |c| c[0...cat.length] == cat }
    end
  end

  def always(exclude = nil)
    Proc.new do |record, match_category|
      if exclude
        [match_category[0..(-1-exclude)]]
      else
        [match_category]
      end
    end
  end

  def match(properties, values, exclude = nil)
    properties = [properties].flatten
    values = [values].flatten.collect { |v| v.is_a?(String) ? v.downcase : v }
    Proc.new do |record, match_category|
      if exclude
        if exclude.is_a?(Integer)
          cat = match_category[0..(-1-exclude)]
        else
          cat = exclude
        end
        next nil unless record['categories'].find { |cs| cs[0...(cat.length)] == cat }
      end
#      puts "Match #{match_category.inspect} : #{properties.inspect} : #{values.inspect}"
      match = properties.find do |property|
        if record[property]
          val = record[property].downcase
        else
          list = record['variants'].collect { |v| v[property] || (v['properties'] && v['properties'][property]) }.compact.uniq
          next if list.empty?
          val = list.join(' ').downcase
        end
        res = values.find do |v|
          if v.is_a?(String)
            val.include?(v)
          else
            v === val
          end
        end
#        puts " \- #{property}: #{val.inspect} => #{res}"
        res
      end
      match ? [match_category] : nil
    end
  end

  def exclude(elements)
    Proc.new do |record, match_category|
      [elements].flatten.compact.each do |elem|
        if elem.call(record, match_category)
          record['categories'].delete_if { |cat| cat == match_category }
        end
      end
      nil
    end
  end

  def duplicate(src, field = 'categories')
    Proc.new do |record, match_category|
      ret = record[field].collect { |cat| (cat[0...(src.length)] == src) ? (match_category + cat[src.size..-1]) : nil }.compact
      next nil if ret.empty?
      @used_categories += ret
      ret
    end
  end

  def dup(*src)
    [src.last, [duplicate(src)]]
  end

  def all(*list)
    list = list.flatten.compact
    Proc.new do |record, match_category|
      result = nil
      list.find do |proc|
        not (result = proc.call(record, match_category))
      end
      result
    end
  end

  def data
[
  ['Apparel',
  [supplier('Ash City',
            category('Catalog', 'NESPORT')) # Kludge for 68627
  ],[
     ['Hats & Caps',
      [match('name', /(?:^| )hat(?:$| |\/)/),
       exclude(match('name', 'stress')), # Remove Stree Reliever
       supplier('High Caliber Line',
                category('Headwear', 'Regular') ),
       supplier('Norwood',
                category('OUTDOOR', 'HEADWEAR'),
                all(category('GOLF'),
                    match('name', 'cap') ) ),
       supplier('Bullet Line',
                category('Headwear', 'Structured/Constructed Caps'),
                category('Headwear', 'Unstructured/Unconstructed Caps') ),
       supplier('Ash City',
                all(category('Accessories'),
                    match('name', 'cap')))
      ],[
         ['Visors',
          [match('name', 'visor', 1),
           supplier('Bullet Line',
                    category('Headwear', 'Visors') ) ] ],
         ['Knit Caps',
          [match('name', 'knit', 1),
           supplier('Bullet Line',
                    category('Headwear', 'Knit Caps') ) ] ],
        ] ],
     ['Outerwear',
      [supplier('Ash City',
                category('Outerwear'), match('name', 'jacket') ) ],
      %w(Windvests Windshirts Insulated\ Seam-Sealed Teflon Soft\ Shells Leather Insulated Seam-Sealed Reversible\ Jackets Reversible\ Vests Workwear).collect do |name|
        [name, [supplier('Ash City', match('name', name.gsub(/s$/,''), 1))]]
      end + 
      [
       ['Performance Jackets',
        [supplier('Ash City',
                  all(match('name', 'jacket', 1),
                      match(%w(name material), 'performance', 1) ) ) ] ],
       ['Techno series',
        [supplier('Ash City',
                  match('description', 'EZAWAY', 1) ) ] ],
      ] ],
     ['Soft Shell',
      [supplier('Ash City',
                category('Soft Shell') ) ],
      [
       ['Performance Jackets',
        [supplier('Ash City',
                  all(match('name', 'jacket', 1),
                      match(%w(name material), 'performance', 1) ) ) ] ],
       ['Performance Vests',
        [supplier('Ash City',
                  all(match('name', 'vest', 1),
                      match(%w(name material), 'performance', 1) ) ) ] ],
      ] ],

     ['Fleece',
      [supplier('Ash City',
                category('Fleece') ),
       match('name', 'fleece')],
      %w(Vests Microfleece Vintage).collect do |name|
        [name, [supplier('Ash City', match('name', name.gsub(/s$/,''), 1))]]
      end + 
      [
       ['Microfleece',
        [supplier('Ash City',
                  match(%w(name material), 'microfleece', 1) ) ] ],
       ['Poly fleece',
        [supplier('Ash City',
                  match(%w(name material), 'polyester', 1) ) ] ],
       ['Interactive Fleece',
        [supplier('Ash City',
                  match('name', 'interactive', 1) ) ] ],
       ['Cotton/Poly Fleece',
        [supplier('Ash City',
                  all(match(%w(name material), 'cotton', 1),
                      match(%w(name material), 'polyester', 1) ) ) ] ],
       ['Bonded Fleece',
        [supplier('Ash City',
                  match('name', 'bonded', 1) ) ] ],
      ] ],
     ['Knits',
      [supplier('Ash City',
                category('Knits'), match('name', 'polo') ) ],
      %w(Jersey Pique Teflon Edry Textured Eperformance Jacquard Mercerized Interlock Micro\ pima).collect do |name|
        [name, [supplier('Ash City', match(%w(name material description), name, 1))]]
      end + 
      [
      ] ],
     ['Wovens',
      [supplier('Ash City',
                category('Wovens') ), ],
      %w(Easy\ care Primalux Twill Teflon Stretch Cotton Denim Service Vintage Wrinkle\ Free Wrinkle\ Resistant).collect do |name|
        [name, [supplier('Ash City', match(%w(name material description), name, 1))]]
      end + 
      [
       ['Silk blend',
        [supplier('Ash City',
                  match(%w(name material description), 'silk', 1) ) ] ],
      ] ],
     ['Active Wear',
      [supplier('Ash City',
                category('Active Wear') ) ],
      [
      ] ],
     ['Pants',
      [match('name', 'pants', 1)]],
     ['Safety',
      [supplier('Ash City',
                category('Safety') ) ],
      [
      ] ],
    ] ],
 ['Awards',
  [
  ],[
     ['Acrylics',
      [supplier('Norwood',
                category('AWARD', 'ACRYLIC') ) ] ],
     ['Art Glass',
      [supplier('Norwood',
                category('AWARD', 'ART') ) ] ],
     ['Awards & Plaques',
      [match('name', 'trophy'),
       supplier('Norwood',
                category('AWARD', 'AWARDS') ),
       supplier('Leeds',
            all(category('Awards', 'Awards'),
                match('name', 'award') ) ) ] ],
     ['Clocks',
      [supplier('Norwood',
                category('AWARD', 'CLOCKS') ) ] ],
#     ['Bases',
#      [supplier('Norwood',
#                category('AWARD', 'BASES') ) ] ],
#     ['Coasters & Beverage Ware',
#      [supplier('Norwood',
#                category('AWARD', 'COASTER') ) ] ],
     ['Image 3 Crystal(TM) Line',
      [supplier('Norwood',
                category('AWARD', 'IMAGE3') ) ] ],
     ['Specialty Gifts',
      [supplier('Norwood',
                category('AWARD', 'SPECIALTY') ) ] ],
     ['Vases',
      [supplier('Norwood',
                category('AWARD', 'VASE') ) ] ],
#     ['Trophies',
#      [supplier('Norwood',
#                category('AWARD', 'TROPHIES') ) ] ],
    ] ],
 ['Calendars',
  [
  ],[
     ['Appointment Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'APPT'),
                category('GV', 'GV_APPT') ) ]],
     ['Commercial Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'COMM') ) ]],
     ['Custom Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'CUSTOM') ) ]],
     ['Executive Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'EXEC'),
                category('GV', 'GV_BUSINESS') ) ]],
     ['Non-Dated Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'NODATE') ) ]],
     ['Nude Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'NUDE') ) ]],
     ['Planners',
      [supplier('Norwood',
                category('CALENDAR', 'PLANNER') ) ]],
     ['Pocket and Desk Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'POCKET'),
                category('GV', 'GV_MINI') ) ]],
     ['Stick up Calendars',
      [supplier('Norwood',
                category('CALENDAR', 'SUC') ) ]],

    ] ],

 ['Automobile',
  [supplier('Norwood', category('AUTO', 'AUTO'))
  ],[
     ['Auto Accessories',
      [match('name', ['roadside', 'visor']),
       supplier('Leeds',
                category('Safety & Auto', 'Auto Accessories') ),
       supplier('Gemline',
                category('Sport & Travel', 'Cargo') ),
       supplier('Gemline',
                all(category('Gifts', 'Safety/Auto'),
                    match('name', 'auto detail') ) ),
       supplier('High Caliber Line',
                category('Auto') ),
       supplier('Bullet Line',
                category('Travel, Health & Beauty', 'Automotive Accessories') ) ] ],
     ['Auto Organizers',
      [match('name', %w(organize contain), 1)
      ] ],
     ['Auto Safety     ',
      [supplier('Leeds',
                category('Safety & Auto', 'Auto Safety') ),
       supplier('Gemline',
                category('Gifts', 'Safety/Auto') ),
       supplier('Norwood',
                category('AUTO', 'HIGHWAY') ),
      ] ],
     ['Ice Scraper',
      [match('name', 'ice scraper'),
       supplier('Lanco',
                category('Tools / Knives', 'Ice Scraper') ) ]],
    ]],
 ['Bags',
  [supplier('Norwood',
            all(category('BAG', 'COMPBAG'),
                match('name', %w(bag brief))) ),
   supplier('High Caliber Line',
            category('Bags') ),
   supplier('Ash City',
            all(category('Accessories'),
                match('name', %w(bag pack portfolio tote brief)))),
   supplier('Prime Line',
            category('Bags'),
            exclude(match(%w(name description), 'cooler'))),
  ],[
     ['Backpacks',
      [match('name', %w(Backpack Daypack)),
       match('description', 'backpack', 1),
       supplier('Leeds',
                category('Backpacks', 'Backpacks')),
       supplier('Gemline',
                ['Under $15', '$15-$30', ' $30+', 'Sports', 'New', 'Clearance'].collect do |name|
                  category('Backpacks', name)
                end),
       supplier('Prime Line',
                category('Backpacks') ),
       supplier('Lanco',
                category('Bags / Containers', 'Backpacks')),
       supplier('Norwood',
                category('BAG', 'BACKPACK') ),
       supplier('High Caliber Line',
                all(category('Bags'),
                    match('name', 'backpack'))),
      ],[
         ['Cooler Backpacks',
          [match('name', 'cooler', 1)]],
         ['Computer Backpacks',
          [match('name', ['compu', 'laptop'], 1),
           supplier('Leeds',
                    category('Backpacks', 'Compu-Backpacks') ),
           supplier('Gemline',
                    category('Backpacks', 'Computer') ) ]],
         ['Checkpoint Friendly Backpacks',
          [supplier('Gemline',
                    category('Backpacks', 'Checkpoint-friendly') ) ] ],
         ['Drawstring & Cinch Backpacks',
          [match('name', %w(drawstring cinch), 1),
           supplier('Leeds',
                    category('Backpacks', 'Cinches')),
           supplier('Gemline',
                    category('Backpacks', 'Cinchpacks'),
                    all(category('Backpacks', 'Sports Backpacks'),
                        match('name', 'cinch') ) ),
           supplier('Bullet Line',
                    category('Bags', 'Drawstrings & Backpacks'),
                    category('Bags', 'Drawstrings and Backpacks')) ]],
         ['Hydration Backpacks',
          [match('name', 'hydrat', 1)]],
         ['Kid Friendly Backpacks',
          [supplier('Gemline',
                    category('Kid-friendly', 'Backpacks') ) ] ],
         ['Recycled Backpacks',
          [supplier('Leeds',
                    category('EcoSmart', 'Backpacks') ) ]],
         ['Sling Backpacks',
          [match('description', 'sling', 1),
           supplier('Leeds',
                    category('Backpacks', 'Slings')),
           supplier('Gemline',
                    category('Backpacks', 'Monopacks'),
                    all(category('Backpacks', 'Sports'),
                        match('name', 'sling') ) ) ]],
         ['Tote Backpacks',
          [match('name', 'tote', 1)]],
         ['Wheeled Backpacks',
          [match('name', %w(wheel roll), 1),
           supplier('Gemline',
                    category('Backpacks', 'Wheeled') )]],
         ['Womens Backpacks',
          [supplier('Gemline',
                    category('Women`s', 'Backpacks')),
           supplier('High Caliber Line',
                    all(category("Women´s Gifts"),
                        match('name', 'bag') ) ) ] ],
        ] ],
     ['Portfolios & Business Bags',
      [match('name', ['portfolio', /attache(?:\s|$)/, 'briefcase', 'brief case']),
       match('name', 'brief', 1),
       supplier('Leeds',
                category('Business Cases', 'Business Cases') ),
       supplier('Gemline',
                ['Clearance', 'New', 'Portfolios Under $10'].collect do |name|
                  category('Portfolios', name)
                end),
       supplier('Lanco',
                category('Bags / Containers', 'Business Cases')),
       supplier('Prime Line',
                all(category('Computer Bags / Portfolios'),
                    match('name', 'brief') ) ),
       supplier('Norwood',
                category('BAG', 'BRIEFCASES') ),
       supplier('Bullet Line',
                all(category('Bags', 'Briefcases & Laptop Cases'),
                    match('name', ['brief', 'messenger', 'document']) ) )
      ],[
         ['Computer Business Bags',
          [supplier('Leeds',
                    category('Business Cases', 'Compu-Cases'),
                    category('Business Cases', 'Compu-Messenger Bags') ),
           supplier('Gemline',
                    category('Portfolios', 'Computer Cases'),
                    category('Cirrus', 'Business Cases') ) ]],
         ['Messenger & Saddle Bags',
          [match('name', %w(messenger saddle), 2),
           match('name', 'messenger bag'),
           supplier('Leeds',
                    category('Business Cases', 'Messenger Bags'),
                    category('Business Cases', 'Compu-Messenger Bags') ),
           supplier('Gemline',
                    category('Portfolios', 'Saddlebags'),
                    category('Portfolios', 'Business'),
                    category('Portfolios', 'Messenger Bags') ) ]],
         ['Leather Business Bags',
          [match('name', 'lthr', 1), # Why doesn't this work?
           match('material', 'leather', 1),
           supplier('Gemline',
                    category('Portfolios', 'Leather Bags') ) ]],
         ['Recycled Business Bags',
          [match(%w(name description), 'recycle', 1),
           supplier('Leeds',
                    category('EcoSmart', 'Business Cases') ) ]],
         ['Wheeled Business Bags',
          [match('name', 'wheel', 1),
           supplier('Leeds',
                    category('Business Cases', 'Wheeled Business Cases') ) ]],
         ['Kid Friendly Portfolios',
          [supplier('Gemline',
                    category('Kid-friendly', 'Portfolios')) ]],
         ['Womens Portfolios',
          [supplier('Gemline',
                    category('Women`s', 'Portfolios')) ]],
         ['Vertical Bags',
          [supplier('Gemline',
                    category('Portfolios', 'Vertical Bags')) ]],
         ['Checkpoint Friendly Portfolios',
          [supplier('Gemline',
                    category('Portfolios', 'Checkpoint-friendly')) ]],
        ] ],
     ['Duffel Bags',
      [match('name', ['duffel', 'duffle']),
       supplier('Gemline',
                ['$15-$25', '$25+', 'Closeout Sport/Travel Bags', 'New Sport/Travel Bags', 'Under $15', 'Travel Bags'].collect do |name|
                  category('Sport & Travel', name)
                end),
       supplier('Lanco',
                category('Bags / Containers', 'Sport and Duffle Bags')),
       supplier('Norwood',
                category('BAG', 'DUFFELS')),
       supplier('Bullet Line',
                category('Bags', 'Duffels') )
      ],[
         ['Executive Duffel Bags',
          [supplier('Leeds',
                    category('Duffels', 'Executive') ) ]],
         ['Recycled Duffel Bags',
          [supplier('Leeds',
                    category('EcoSmart', 'Duffels') ) ]],
         ['Sport Duffel Bags',
          [match('name', %w(athletic fitness), 2), # for Prime Line
           match('name', 'Sport Duffel', 1),
           supplier('Leeds',
                    category('Duffels', 'Sport') ),
           supplier('Gemline',
                    category('Sport & Travel', 'Sport Bags'),
                    match('name', 'sport bag')),
           supplier('Norwood',
                    category('BAG', 'SPORT') )
          ],[['Kid Friendly Sport Bags',
              [supplier('Gemline',
                        category('Kid-friendly', 'Sport & Travel') ) ] ],
            ]],
         ['Wheeled Duffel Bags',
          [match('name', 'wheeled'),
           supplier('Leeds',
                    category('Duffels', 'Wheeled') ),
           supplier('Gemline',
                    category('Sport & Travel', 'Wheeled') ) ]]
        ] ],
     ['Golf Bags',
      [match('name', 'golf', 1),
       supplier('Leeds',
                all(category('Luggage & Golf', 'Golf'),
                    match('name', %w(bag duffel)) ) ),
       supplier('Norwood',
                all(match('name', %w(bag carrier)),
                    category('GOLF') ),
                match('name', ['stand bag', 'cart bag'])) ]],
     ['Luggage',
      [supplier('Leeds',
                category('Luggage & Golf', 'Luggage') ),
       supplier('Norwood',
                category('TRAVEL', 'LUGGAGE'),
                match('name', 'carry on') )]],
     ['Checkpoint Friendly Bags',
      [ ],
      [dup('Bags', 'Backpacks', 'Checkpoint Friendly Backpacks'),
       dup('Bags', 'Portfolios & Business Bags', 'Checkpoint Friendly Portfolios') ] ],
     ['Leather Bags',
      [match('material', 'leather', 1)]],
     ['Computer Bags',
      [match('name', ['computer case', 'computer bag', 'laptop bag', 'laptop case']),
       match('name', 'compu', 1),
       supplier('Prime Line',
                match('name', ['computer sleeve', 'laptop sleeve']) )
               
      ],[dup('Bags', 'Backpacks', 'Computer Backpacks'),
         ['Laptop Sleeves',
          [match('name', 'laptop sleeve'),
           supplier('Prime Line',
                    category('Laptop/Tablet Sleeves'))
          ]],
        ] ],
     ['Wheeled Bags',
      [match('name', 'wheel', 1),
       supplier('Gemline',
                category('Sport & Travel', 'Wheeled Bags') )
      ],[dup('Bags', 'Backpacks', 'Wheeled Backpacks'),
         dup('Bags', 'Business Bags', 'Wheeled Business Bags'),
         dup('Bags', 'Duffel Bags', 'Wheeled Duffel Bags')
        ] ],
     ['Tote Bags',
      [match('name', 'tote'),
       supplier('Leeds',
                category('Totes', 'Totes')),
       supplier('Gemline',
                ['New', 'Clearance', 'Totes 10+', 'Totes Under $10', 'Totes Under $5', 'Market Sets'].collect do |name|
                  category('Totes', name)
                end),
       supplier('Lanco',
                category('Bags / Containers', 'Tote Bags')),
       supplier('Prime Line',
                category('Totes')),
       supplier('Norwood',
                category('BAG', 'TOTE') ),
       supplier('Bullet Line',
                category('Bags', 'Totes'))
      ],[
         ['Business & Meeting Totes',
          [match(%w(name description), %w(business meeting computer laptop), 1),
           exclude(match('description', 'business card')) ] ],
         ['Cotton Canvas Totes',
          [match(%w(name description material), %w(cotton canvas), 1),
           supplier('Leeds',
                    category('Totes', 'Cotton') ),
           supplier('Gemline',
                    category('Totes', 'Canvas Bags'),
                    category('Living Green', 'Organic'))]],
         ['Jute Totes',
          [match(%w(name description material), %w(jute), 1),
           supplier('Prime Line',
                    all(category('Jute Bags'),
                        match('name', 'tote')))]],
         ['Non-woven Polypropylene Totes',
          [match('material', %w(poly non-woven non\ woven), 1),
           match(%w(name description), ['poly', 'pet plastic', 'non-woven'], 1),
           supplier('Leeds',
                    category('Totes', 'Non-Woven') ),
           supplier('Gemline',
                    category('Totes', 'Non-woven') ),
           supplier('Prime Line',
                    category('Non-Woven') )]],
         ['Shopper Totes',
          [match(%w(name description), %w(shopper grocery market), 2),
           supplier('Gemline',
                    category('Totes', 'Shoppers'))]],
         ['Cooler & Insulated Totes',
          [match(%w(name description), %w(cooler lunch six\ pack insulate), 2)]],
         ['Trade Show Totes',
          [match(%w(name description), %w(trade\ show tradeshow expo convention), 1),
           supplier('Gemline',
                    category('Totes', 'Expo'))]],
         ['Kid Friendly Totes',
          [supplier('Gemline',
                    category('Kid-friendly', 'Totes') ) ] ],
         ['Recycled & Organic Totes',
          [match(%w(name description), 'recycled', 1),
           supplier('Leeds',
                    category('Totes', 'EcoSmart'),
                    category('EcoSmart', 'Totes') ) ]],
         ['Backpack Totes',
          [match(%w(name description), 'backpack', 1)],
          [
           ['Drawstring Totes',
            [match(%w(name description), 'drawstring', 2),
             match('name', %w(cinch sling), ['Bags', 'Backpacks', 'Drawstring Backpacks'])]],
          ] ],
         ['Womens Totes',
          [match('name', 'gloss', 1),
           supplier('Gemline',
                    category('Women`s', 'Totes')) ]],
         ['Wine Totes',
          [match(%w(name description), 'wine', 1)]],
         ['Zippered Totes',
          [match(%w(name description), 'zipper', 1)]],
        ] ],
     ['Tool Bags',
      [match('name', ['tool', 'utility case'], 1),
       supplier('Gemline',
                all(category('Gifts', 'Home Improvement'),
                    match('name', %w(bag case))))]],
     ['Wine Bags',
      [match('name', 'Wine', 1),
       match('name', 'Wine Tote')]],
     ['Womens Bags',
      [supplier('Gemline',
                category('Women`s', 'Sport & Travel')) ]],
     ['Waist Pack',
      [match('name', ['waist pack', 'fanny pack']) ] ],
     ['Pouches',
      [match('name', 'pouch'),
       supplier('Lanco',
                category('Bags / Containers', 'Small Pouches & Bags'))] ],
     ['Amenity Cases',
      [match('name', 'toiletr'),
       supplier('Gemline',
                category('Sport & Travel', 'Amenity Cases') ),
       supplier('Bullet Line',
                all(category('Travel, Health & Beauty', 'Travel Accessories'),
                    match('name', ['amenity', 'travel']) ) ) ]],
    ] ],

 ['Candles, Bath & Body',
  [
  ],[
     ['Bath & Body Gift Sets',
      [supplier('Lanco',
                category('Candles / Bath / Body', 'Bath & Body Gift Sets') ) ]],
     ['Candles',
      [match('name', 'candle'),
       supplier('Lanco',
                category('Candles / Bath / Body', 'Candles') ) ]],
     ['Bath & Body Kits',
      [match('name', 'spa kit'),
       supplier('Lanco',
                category('Candles / Bath / Body', 'Bath & Body Kits') ) ]],
     ['Massagers',
      [match('name', 'massager') ]],
     ['Bath & Body Lotions',
      [supplier('Lanco',
                category('Candles / Bath / Body', 'Bath & Body Lotions') ) ]],
    ] ],

 ['Collections',
  [supplier('Gemline', duplicate(['Collections'], 'supplier_categories'))
  ],[
     ['Cleveland®',
      [supplier('Norwood', category('GOLF', 'CLEVE')) ]],
     ['Titleist®',
      [supplier('Norwood', category('GOLF', 'TITLEIST')) ]],
     ['Callaway®',
      [supplier('Norwood', category('GOLF', 'GALLAWAY')) ]],
     ['Wilson®',
      [supplier('Norwood', category('GOLF', 'WILSON')) ]],
     ['Gusto!',
      [supplier('Leeds',
                duplicate(['Gusto!'], 'supplier_categories'))]],
     ['Life in Motion', 
      [supplier('Gemline', duplicate(['Life in Motion'], 'supplier_categories') ) ]] ,
     ['Contours',
      [supplier('Gemline', duplicate(['Contour'], 'supplier_categories') ) ]] ,
     ['Cirrus',
      [supplier('Gemline', duplicate(['Cirrus'], 'supplier_categories'))]],
     ['Elements',
      [supplier('Gemline', duplicate(['Elements'], 'supplier_categories'))]],
     ['Equity',
      [supplier('Gemline', duplicate(['Equity'], 'supplier_categories'))]],
     ['Nike®',
      [match('name', 'nike'),
       supplier('Norwood', category('GOLF', 'NIKE')) ] ],
     ['Callaway®',
      [match('name', 'callaway'),
       supplier('Norwood', category('GOLF', 'CALLAWAY')) ] ],
     ['Built®',
      [supplier('Prime Line',
                category('BUILT')) ]]

    ] ],

 ['Computer Accessories',
  [supplier('Prime Line',
            category('Technology'),
            category('USBTechnology') ),
   supplier('Norwood',
            category('TECHNOLOGY', 'ELEC') ),
   supplier('Bullet Line',
            category('Desktop', 'Multi-Card Readers') ),
   supplier('LogoIncluded',
            category('Card Reader') )
  ],[
     ['Apple Accessories',
      [match('name', /iP(o|a)d/),
       supplier('LogoIncluded', category('Mobile / Apple Accessories')),
      ]],
     ['CD Products',
      [match('name', ['CD case', 'DVD case']),
       supplier('Lanco',
                category('Office / Computer Essentials', 'CD Products') ),]],
     ['Computer Accessory Kits',
      [match('name', 'computer accessories')]],
     ['Computer Brush',
      [match('name', 'computer brush'),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Computer Brush') ) ]],
     ['Cables & Cords',
      [match('name', %w(cable cord), 1),
       match('name', %w(phone\ cord)),
       match('name', /((usb)|(network)).+cable/i),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Modem Cord') ) ]],
     ['Computer Mice',
      [match('name', 'mouse ', 1),
       match('name', /mouse$/),
       supplier('Leeds',
                category('Technology', 'Mice') ),
       supplier('Norwood',
                all(match('name', ' mouse'),
                    category('OFFICE', 'TECHNOLOGY') ) ),
       supplier('Bullet Line',
                category('Desktop', 'Mice') ),
       supplier('LogoIncluded',
                category('Mouse') ) ]],
     ['Computer Mouse Pads',
      [match('name', ['mousepad', 'mouse pad']),
       supplier('Bullet Line',
                category('Desktop', 'Mouse Pads') ) ] ],
     ['Screen Cleaners',
      [match('name', 'screen cleaner'),
      supplier('LogoIncluded',
               category('Screen Cleaner') )] ],
     ['MP3 Players',
      [match('name', %w(mp3 mp4 iPod)),
       supplier('Leeds',
                category('Memory', 'Music & Media') ),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Mouse Pads') ),
       supplier('Prime Line',
                all(category('Mp3 / Radios'),
                    match(%w(name description), %w(mp3 iPod)) ) ),
       supplier('LogoIncluded',
                category('MP3 Player / MP4 Player') )]],
     ['Web Cams',
      [match('name', 'web cam')] ],
     ['Web Keys',
      [supplier('LogoIncluded',
                category('Web Key') )] ],
     ['WiFi Finders',
      [supplier('LogoIncluded',
                category('WiFi Finder') )] ],
     ['USB Hubs',
      [match('name', 'hub', 1),
       match('name', 'usb hub'),
       supplier('Leeds',
                category('Technology', 'USB Hubs') ),
       supplier('Norwood',
                all(match('name', ' hub'),
                    category('OFFICE', 'TECHNOLOGY') ) ),
       supplier('Bullet Line',
                category('Desktop', 'USB Hubs') ),
       supplier('LogoIncluded',
                category('USB Hub'))]],
     ['USB Accessories',
      [all(match('name', 'usb'),
           match('name', ['charger']) ),
       supplier('LogoIncluded',
                category('USB Accessories'),
                all(category('Tech Accessories'),
                    match(%w(name description), 'USB'))) ]],
     ['USB Flash Drives',
      [match('name', %w(flash memory mb gb), 1),
       supplier('Leeds',
                category('Memory', 'Flash Drives') ),
       supplier('Gemline',
                category('Gifts', 'USB Drives') ),
       supplier('Prime Line',
                category('USB Memory') ),
      ],[
         ['Pen USB Flash Drives',
          [match('name', 'pen', 1),
           supplier('Leeds',
                    category('Memory', 'Memory Pens') ),
           supplier('LogoIncluded',
                    category('Pen Drive') )]],
         ['Recycled Flash Drives',
          [match(%w(name description), 'recycle', 1),
           supplier('Leeds',
                    category('EcoSmart', 'Memory') ) ]],
        ] +
      ['128M', '256M', '512M', '1G', '2G', '4G', '8G', '16G', '32G'].collect do |name|
        ["#{name}B Flash Drives",
         [match('name', name, 1),
          supplier('LogoIncluded',
                   category('USB Drive'),
                   category('Wireless Presenter') )]]
      end
     ],
     ['Digital Photo Frames',
      [supplier('Leeds',
                category('Technology', 'Digital Photos') ),
       supplier('Prime Line',
                category('Digital Frames SALE')),
       supplier('Norwood',
                all(match('name', 'digital photo'),
                    category('OFFICE', 'TECHNOLOGY') ) ),
       supplier('Bullet Line',
                category('Desktop', 'Digital Photo Frames') ),
       supplier('LogoIncluded',
                category('Digital Photo Frame') )]],
    ] ],

 ['Desktop Accessories',
  [supplier('Leeds',
            category('Desktop', 'Accessories & Sets'),
            category('Desktop', 'Electronics & Clocks'),
            category('Desktop', 'Essentials'),
            category('Gusto', 'Work') ),
   supplier('Prime Line',
            category('Office'),
            category('Desk Helpers')),
   supplier('Norwood',
            category('GOLF', 'DESKFUN') ),
   supplier('Bullet Line',
            category('Desktop', 'Desk Accessories'),
            category('Desktop', 'Desktop Accessories') )
  ],[
     ['Calculators',
      [match('name', 'calculator'),
       supplier('High Caliber Line',
                category('Calculators') ),
       supplier('Prime Line',
                category('Calculators') ),
       supplier('Lanco',
                category('Calc / Clocks / Radios', 'Calculators') ),
       supplier('Bullet Line',
                category('Desktop', 'Calculators') ),
       ]],
     ['Clocks',
      [match('name', 'clock'),
       supplier('Prime Line',
                category('Clocks') ),
       supplier('Lanco',
                category('Calc / Clocks / Radios', 'Clocks') ),
       supplier('High Caliber Line',
                category('Clocks') ),
       supplier('Norwood',
                category('AWARD', 'CLOCKS') ),
       supplier('Bullet Line',
                category('Desktop', 'Clocks') ),
      ],[
         ['Travel Clocks',
          match(%w(name description), 'travel', 1),
          supplier('Leeds',
                   all(category('Travel Gifts', 'Clocks & Wallets'),
                       match('name', 'clock')) )]
        ]],
     ['Radios',
      [match('name', 'radio'),
       supplier('Prime Line',                
                match(%w(name description), %w(radio am/fm) ) ),
       supplier('Lanco',
                category('Calc / Clocks / Radios', 'Radios') ),
       supplier('Bullet Line',
                category('Fitness & Recreation', 'Radios') ) ]],
     ['Weather Station',
      [match('name', 'weather station')]],
     dup('Computer Accessories', 'Digital Photo Frames'),
     ['Picture Frames',
      [match('name', ['photo frame', 'picture frame']),
       match('name', 'frame', 1),
       supplier('Leeds',
                all(category('Desktop Gifts', 'Desktop Accessories'),
                    match('name', %w(photo frame)) ) ), 
       supplier('Norwood',
                category('OFFICE', 'PHOTO') ),
       supplier('High Caliber Line',
                category('Picture Frames') ),
       supplier('Prime Line',
                match('name', 'frame'))]],
     ['Photo Albums',
      [match('name', %w(photo\ album brag\ book)) ] ],
     ['Desktop Novelties',
      [supplier('Leeds',
                category('Desktop Gifts', 'Desktop Novelty'),
                category('Gusto', 'Connect')) ]],
     ['Ecologically Friendly Desktop',
      [supplier('Leeds',
                category('EcoSmart', 'Desktop') ) ] ],
     ['Recycled Desktop Accessories',
      [supplier('Leeds',
                all(category('EcoSmart', 'Desktop'),
                    match('name', 'recycled') ) ) ]],
     ['Desktop Technology',
      [supplier('Leeds',
                category('Technology', 'Desktop') ) ]],
     ['Letter Openers',
      [match('name', 'letter opener'),
       match('name', 'opener', 1),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Letter Opener') )]],
     ['Laser Pointers',
      [match('name', 'laser', 1),
       supplier('High Caliber Line',
                category('Laser Pointers') ),
       supplier('Bullet Line',
                category('Lighting', 'Laser Pointers'),
                category('Desktop', 'Laser Pointers') ),
       supplier('LogoIncluded',
                category('Wireless Presenter') )]],
     ['Mouse Pads',
      [match('name', ['mousepad', 'mouse pad']),
       supplier('Norwood',
                all(match('name', 'mousepad'),
                    category('OFFICE', 'TECHNOLOGY') ) )] ],
     dup('Computer Accessories', 'Computer Mice'),
     ['Bookmarks',
      [match('name', ['bookmark', 'book mark']) ] ],
     ['Speakers',
      [match('name', 'speaker'),
       supplier('Leeds',
                all(category('Technology', 'Music & Media'),
                    match(%w(name description), 'speaker') ) )] ],
     ['Headphones & Earbuds',
      [match('name', %w(headphones head\ phones earbuds earphones ear\ plugs ear\ phones)),
       supplier('Leeds',
                all(category('Technology', 'Music & Media'),
                    match('name', %w(headph ear)) ) ),
       supplier('LogoIncluded',
                category('Bluetooth Headset') ) ] ],
     ['Desktop Organizers',
      [match('name', ['desk caddy', 'desk organizer', 'pen caddy'])]],
     ['Card Holders',
      [match('name', 'card holder', 1),
       match(%w(name description), 'business card holder'),
       supplier('Prime Line',
                match('name', 'card case') ),
       supplier('High Caliber Line',
                all(category('Office'),
                    match('name', 'card holder') ) ),
       supplier('Bullet Line',
                match('name', 'card case') )] ],
     ['Note Holders',
      [match('name', ['note holder', 'memo holder', 'Post-it holder','note dispenser', 'sticky note', 'sticky flag']), #, 1),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Memo Holder'),
                category('Office / Computer Essentials', 'Memo Dispenser'),
                category('Journals / Portfolios', 'Sticky Holder')),
       supplier('Prime Line',
                all(category('Desk Helpers'),
                    match('name', 'note') ) ),
       supplier('High Caliber Line',
                all(category('Office'),
                    match('name', ' clip') ),
                match('name', 'note holder') ),
       supplier('Norwood',
                category('OFFICE', 'NOTES') ),
       supplier('Bullet Line',
                all(category('Desktop', 'Memo Holders/Clips'),
                    match('name', 'memo') ) ) ],
      [['Notenest & Note Clips',
        [match('name', 'clip', 1),
         match('name', ['notenest', 'memo clip']),
         supplier('Prime Line',
                  match('name', 'notenest') ) ] ],
       ['Memo Books',
        [match('name', ['memo book', 'message pad holder'], 2)]],
       ['Sticky Note Books',
        [match('name', 'sticky memo', 1),
         match('name', /stick.+((note)|(flag)).+book/i),
         supplier('Prime Line',
                  category('Sticky Books'))] ]
      ]],
     ['Paper Clips & Fasteners',
      [#match('name', 'paper clip'),
       supplier('Norwood',
                category('OFFICE', 'CLIP') )]],
     ['Paper Clip Holders',
      [match('name', ['clip dispenser', /paper.+clip.+dispens/i]),
       match('name', ['cache', 'clip holder', 'clip keeper'], 1),
       match(%w(name description), 'paper clip', 1),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Paper Clip Holder') ),
       supplier('Prime Line',
                match('name', 'cache') )]],
     ['Paperweights',
      [match('name', 'paperweight')]],
     ['Piggy Bank',
      [match('name', /(pig(gy)?)|(coin) bank/i)] ],
     ['Push Pins',
      [match('name', 'push pin')] ],
     ['Rulers',
      [match('name', 'ruler'),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Ruler') ) ]],
     ['Scissors',
      [match('name', 'scissor'),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Scissors') ) ]],
     ['Staplers',
      [match('name', 'stapler'),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Stapler') ) ]],
     ['Staple Removers',
      [match('name', 'staple remover'),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Staple Remover') ) ]],
     ['Tape Dispensers',
      [match('name', 'tape dispenser'),
       supplier('Lanco',
                category('Office / Computer Essentials', 'Tape Dispenser') ),
       supplier('High Caliber Line',
                all(category('Office'),
                    match('name', 'tape') ) )]],
     ['Magnets',
      [supplier('Norwood',
                category('OFFICE', 'MAGNET') ) ] ],
     ['Snow Globe',
      [match(%w(name description), ['snow globe', 'glitter globe']) ] ],
     ['Book Lights',
      [match('name', ['book light', 'book-light']),
       supplier('Bullet Line',
                category('Lighting', 'Book-Lights') ) ] ],
    ] ], 

 ['Coolers',
  [match('name', ['cooler', 'kooler']),
   supplier('Gemline',
            ['Closeout Coolers', 'Coolers 12+', 'New', 'Under $12'].collect do |name|
              category('Coolers', name)
            end),
   supplier('Lanco',
            category('Bags / Containers', 'Lunch Bag & Coolers')),
   supplier('Prime Line',
            category('Coolers - Ice'),
            all(category('Bags'),
                match(%w(name description), 'cooler'))),
   supplier('Norwood',
            category('BAG', 'COOLERS') ),
   supplier('High Caliber Line',
            all(category('Bags'),
                match('name', 'cooler'))),
   supplier('Bullet Line',
            category('Coolers', 'Rolling & Chair Coolers') )
  ],[
     ['Beverage Holders',
      [supplier('Leeds',
                category('Coolers', 'Beverage Holders') ) ]],
     ['Can Coolers',
      [match('name', 'can', 1)] ],
     ['Chair Coolers',
      [match('name', 'chair', 1) ] ],
     ['Event Coolers',
      [supplier('Leeds',
                category('Coolers', 'Event Coolers') ),
       supplier('Gemline',
                category('Coolers', 'Event') ) ]],
     ['Drink Coolers',
      [supplier('Norwood',
                category('OUTDOOR', 'HSCOOLERS') ) ] ],
     ['Food Storage Coolers',
      [supplier('Leeds',
                category('Coolers', 'Food Storage') ) ]],
     ['Kid Friendly Coolers',
      [supplier('Gemline',
                category('Kid-friendly', 'Coolers') ) ] ],
     ['Lunch Coolers',
      [match('name', 'lunch', 1),
       match('name', ['lunch kit', 'lunch bag']),
       supplier('Leeds',
                category('Coolers', 'Lunch Coolers') ),
       supplier('Gemline',
                category('Coolers', 'Lunch Bags') ),
       supplier('Bullet Line',
                category('Coolers', 'Lunch Coolers') ) ]],
     ['Recycled Coolers',
      [supplier('Leeds',
                category('EcoSmart', 'Food Storage') ) ]],
     ['Wheeled Coolers',
      [match('name', %w(wheel rolling), 1),
       supplier('Gemline',
                category('Coolers', 'Wheeled') )]],
     ['Wine Coolers',
      [duplicate(['Bags', 'Wine Bags']),
       match(%w(name description), 'wine', 1)]]
    ] ],
 ['Drinkware',
  [#match('name', %w(coffe))
   supplier('Prime Line',
            category('Drinkware') ),
   supplier('Norwood',
            category('DRINK', 'BOTTLE') ),
   supplier('Leeds',
            category('Drinkware', 'Gift Sets') ),
   supplier('High Caliber Line',
            category('Drinkware') ),
   supplier('Lanco',
            category('Drinkware', 'Cups') )
  ],[
     ['Aluminum Bottles',
      [match(%w(name description material), 'aluminum', 1),
       supplier('Leeds',
                category('Drinkware', 'Aluminum Bottles'),
                category('Drinkware', 'Aluminum Sports Bottles')),
       supplier('Lanco',
                category('Drinkware', 'Metal Bottles') ) ]],
     ['Stainless Bottles',
      [supplier('Leeds',
                category('Drinkware', 'Stainless Sport Bottles'))]],
     ['Can & Bottle Holders',
      [match('name', ['can holder', 'bottle holder', 'bottle insulator']),
       match('name', 'holder', 1),
       all(match('name', 'insulator'),
           match('description', 'drink') ),
       supplier('Lanco',
                category('Drinkware', 'Can & Bottle Holder') ),
       supplier('Norwood',
                category('DRINK', 'KOOZIE') ),
       supplier('High Caliber Line',
                all(category('Drinkware', 'Accessories'),
                    match('name', 'holder') ) ) ] ],
     ['Coasters', 
      [match('name', 'coaster'),
       supplier('Lanco',
                category('Drinkware', 'Coasters') ),
       supplier('Norwood',
                category('HOUSEWARES', 'COASTERS'))]],
     ['Jigger',
      [match('name', 'jigger')]],
     ['Ceramic',
      [match('name', 'ceramic', 1),
       supplier('Leeds',
                category('Drinkware', 'Ceramic') ),
       supplier('Bullet Line',
                category('Drinkware', 'Ceramics') ) ]],
     ['Drinkware Sets',
      [supplier('Leeds',
                category('Drinkware', 'Drinkware Sets') ),
       supplier('Norwood',
                category('DRINK', 'DRINKGIFT') ) ]],
     ['Insulated Bottles',
      [supplier('Leeds',
                category('Drinkware', 'Insulated Bottles') ),
       supplier('Bullet Line',
                category('Drinkware', 'Insulated Bottles') ), ]],
     ['Mugs & Tumblers',
      [match('name', %w(tumbler mug), 1),
       match('name', 'flask'),
       supplier('Leeds',
                category('Drinkware', 'Mugs & Tumblers') ),
       supplier('Lanco',
                category('Drinkware', 'Travel Mugs & Tumblers') ),
       supplier('Norwood',
                category('DRINK', 'METAL') ),
       supplier('High Caliber Line',
                match('name', 'Mug') ),
       supplier('Bullet Line',
                category('Drinkware', 'Tumblers'),
                category('Drinkware', 'Tumblers/Mugs') )
                
      ],[
         ['Desk Mugs',
          [supplier('Leeds',
                    category('Drinkware', 'Desk Mugs') )]],
         ['Ceramic Coffee Mugs',
          [match('name', 'coffee', 1),
           supplier('Lanco',
                    category('Drinkware', 'Mugs') ),
           supplier('Norwood',
                    category('DRINK', 'CERAMIC') )]],
        ]],
     ['Recycled Drinkware',
      [supplier('Leeds',
                category('EcoSmart', 'Drinkware') ) ]],
     ['Sport Bottles',
      [match('name', %w(bottle chill poly polly sports), 1),
       match('description', ['polyclear', 'sports bottle', 'squeeze bottle'], 1),
       supplier('Leeds',
                category('Drinkware', 'Plastic Sport Bottles') ),
       supplier('Lanco',
                category('Drinkware', 'Polycarbonate Bottles'),
                category('Drinkware', 'Sports Bottles')),
       supplier('Norwood',
                all(category('DRINK', 'BOTTLE'),
                    match('description', 'bottle') ) ),
       supplier('Bullet Line',
                category('Drinkware', 'Sports Bottles') ) ]],
     ['Wine Accessories',
      [match('name', 'wine')]],
     ['Glassware',
      [supplier('Norwood',
                category('DRINK', 'GLASS') ),
       supplier('Leeds',
                category('Drinkware', 'Glassware') )] ],
              
    ] ],
 ['Food Gifts',
  [
  ],[
     ['Candy',
      [match('name', %w(jelly\ bean skittles))] ],
     ['Gourmet Food Gifts',
      [supplier('Lanco',
                category('Food Gifts', 'Gourmet Food Gifts') ) ]],
     ['Chocolate Foil Wrapped Pieces',
      [supplier('Lanco',
                category('Food Gifts', 'Chocolate Foil Wrapped Pieces') ) ]],
     ['Chocolate Truffles',
      [supplier('Lanco',
                category('Food Gifts', 'Chocolate Truffles') ) ]],
     ['Boxes with Gourmet Fills',
      [supplier('Lanco',
                category('Food Gifts', 'Boxes with Gourmet Fills') ) ]],
     ['Mints',
      [match('name', 'mint'),
       supplier('Lanco',
                category('Food Gifts', 'Mints') ),
      supplier('High Caliber Line',
               category('Mints') )]],
     ['Coffee, Hot Chocolate, Ice Tea',
      [supplier('Lanco',
                category('Food Gifts', 'Coffee, Hot Chocolate, Ice Tea') ) ]],
     ['Candy Dispenser',
      [supplier('Lanco',
                category('Food Gifts', 'Candy Dispenser') ) ]],
     ['Novelty Chocolate',
      [supplier('Lanco',
                category('Food Gifts', 'Novelty Chocolate') ) ]],
     ['Chocolate Squares in Gift Sets',
      [supplier('Lanco',
                category('Food Gifts', 'Chocolate Squares in Gift Sets') ) ]],
     ['Bags with Gourmet Fills',
      [supplier('Lanco',
                category('Food Gifts', 'Bags with Gourmet Fills') ) ]],
     ['Chocolate Bars',
      [supplier('Lanco',
                category('Food Gifts', 'Chocolate Bars') ) ]],
     ['Custom Molded Chocolate',
      [supplier('Lanco',
                category('Food Gifts', 'Custom Molded Chocolate') ) ]],
     ['Filled Glass Apothecary Jar',
      [supplier('Lanco',
                category('Food Gifts', 'Filled Glass Apothecary Jar') ) ]],
     ['Gum',
      [supplier('Lanco',
                category('Food Gifts', 'Gum') ) ]],
     ['Bottled Water',
      [match('name', 'bottled water'),
       supplier('Lanco',
                category('Food Gifts', 'Bottled Water') ) ]],
     ['Tea Bags',
      [match('name', 'tea bag'),
       supplier('Lanco',
                category('Food Gifts', 'Tea Bags') ) ] ],
    ] ],
 ['Games & Toys',
  [supplier('Leeds',
            category('Recreation', 'Family & Travel Games'),
            category('Gusto', 'Play'),
            category('Games', 'Desktop'),
            category('Games', 'Home')),
   supplier('High Caliber Line',
            category('Toys & Games')),
   supplier('Prime Line',
            category('Toys Executive') ),
   supplier('Norwood',
            match('name', 'hockey'),
            category('GOLF', 'FUN'),
            category('GOLF', 'GAMES')),
   supplier('Lanco',
            category('Toys & Games', 'Toys') ),
  ],[
     ['Electronic Games',
      [match('name', 'electr', 1),
       match('description', ['electr', 'batteries', 'LCD'], 1)]],
     ['Outdoor Games',
      [match('name', ['ball'], 1),
       match('name', ['flying disc', 'flyer', 'kite', 'football', 'rocket', 'boomerang', 'basketball', 'soccer']),
       exclude(match('name', 'stress')),
       exclude(supplier('LogoIncluded', always)),
       supplier('High Caliber Line',
                match('name', ['super ball', 'flying star', 'paddle ball']) ),
       supplier('Gemline',
                category('Gifts', 'Outdoor Fun') ),
       supplier('Leeds',
                category('Games', 'Outdoor') ),
       supplier('Lanco',
                category('Toys & Games', 'Hacki Balls') ) ]],
     ['Mind Games',
      [match('name', %w(suduko sudoku brain perplex mind))
      ],[
         ['Puzzles',
          [match('name', 'puzzle'),
           supplier('Prime Line',
                    all(match('name','Magic'),
                        match('name', '&reg;'))) ]],
         ['Rubiks Cubes',
          [match('name', 'rubik'),
           match('name', 'rubi', 1),
           supplier('Prime Line',
                    category("Rubik's&reg; Cubes") ) ] ],
        ]],
     ['Magic',
      [supplier('High Caliber Line',
                category('Magic') ) ]],
     ['Travel Games',
      [supplier('Leeds',
                category('Games', 'Travel') ) ]],
     ['Stress Reliever',
      [match('name', 'stress', 1),
       match('name', 'stress reliever'),
       supplier('Leeds',
                category('Gusto', 'Live') ),
       supplier('Prime Line',
                category('Stress Relievers') ),
       supplier('Lanco',
                category('Toys & Games', 'Stress Balls & Shapes') ),
       supplier('Norwood',
                category('HEALTH', 'STRESS') ),
       supplier('Bullet Line',
                category('Desktop', 'Stress Relievers') )
      ] ],
     ['Dartboards',
      [match('name', 'dartboard') ]],
     ['Poker Sets',
      [match('name', 'poker') ]],
     ["Yo-Yo's",
      [match(%w(name description), ['Yo-Yo', 'Yo Yo', 'YoYo']),
       supplier('Lanco',
                category('Toys & Games', 'Yo-Yo\'s') )]],
    ] ],
 # Bad category
 ['Travel',
  [supplier('Leeds',
            category('Gusto', 'Voyage') ),
   supplier('Gemline',
            category('Gifts', 'Travel') ),
   supplier('High Caliber Line',
            category('Travel') )
  ],[
     ['Luggage Tags',
      [match('name', 'luggage'),
       supplier('Leeds',
                category('Travel Gifts', 'Luggage Tags') ),
       supplier('Lanco',
                category('Travel / Personal Care', 'Luggage Tags') ) ]],
     ['Travel Accessories',
      [supplier('Leeds',
                category('Travel Gifts', 'Accessories'),
                exclude(match('name', 'charge')))] ],
     ['Phone Chargers',
      [match('name', ['charger', 'charging']),
       supplier('Leeds',
                all(category('Travel Gifts', 'Accessories'),
                    match('name', 'charge'))),
       supplier('LogoIncluded',
                category('Solar Charger') )] ],
     ['Travel Clocks', duplicate(['Desktop Accessories', 'Clocks', 'Travel Clocks']) ],
     ['Travel Games', duplicate(['Games & Toys', 'Travel Games']) ],
     ['Travel Sets',
      supplier('Leeds',
               category('Travel Gifts', 'Gift Sets') ) ],
     ['Utility Kits',
      supplier('Leeds',
               category('Luggage & Golf', 'Utility Kits') ) ],
     ['Travel Technology',
      supplier('Leeds',
               category('Technology', 'Travel') ),
      supplier('LogoIncluded',
               category('Solar Charger'),
               category('Executive Kit'))],
    ] ],
 ['Housewares',
  [
   match('name', 'door knob'),
  ],[
     ['Boxes & Waterproof Containers',
      supplier('Lanco',
               category('Bags / Containers', 'Boxes / Waterproof Containers'))],
     ['BBQ & Picnic',
      [match('name', %w(grill bbq picnic)),
       supplier('Leeds',
                category('Outdoor Living', 'BBQ & Picnic') ),
       supplier('Norwood',
                category('HOUSEWARES', 'PICNIC2'),
                category('OUTDOOR', 'PICNIC') ),
       exclude(supplier('LogoIncluded', always)),
      ]],
     ['Beverage & Bar',
      [supplier('Leeds',
                category('Housewares', 'Beverage & Bar') )
      ],[
         ['Recycled Bar Sets',
          supplier('Leeds',
                   category('EcoSmart', 'Beverage & Bar') ) ]
        ]],
     ['Conserve',
      [supplier('Leeds',
                category('Housewares', 'Conserve') ) ]],
     ['Decorations',
      [supplier('Norwood',
                category('HOUSEWARES', 'DECO') ) ]],
     ['Food Storage',
      [supplier('Leeds',
                category('Housewares', 'Food Storage') ),
       supplier('Norwood',
                category('HOUSEWARES', 'FOOD') ),]],
     ['Wine & Cheese Collection',
      [supplier('Leeds',
                category('Housewares', 'Wine & Cheese Collection') ),
       supplier('Norwood',
                category('HOUSEWARES', 'WINE') ),]],
     ['Kitchen',
      [match(%w(name description), 'kitchen'),
       match('name', ['measuring cup', 'measuring spoon', 'pizza cutter', 'spatula', 'basting', 'dishwasher', 'silicone glove']),
       supplier('Norwood',
                category('HOUSEWARES', 'UTENSILS'))
      ],[
         ['Aprons',
          [match('name', 'apron')]],
         ['Thermometers',
          [match('name', 'thermometer', 1)]],
         ['Toasters',
          [match('name', 'toaster') ]],
        ]],
     ['Cutlery',
      [supplier('Leeds',
                category('Housewares', 'Cutlery') ) ]],
     ['Seasonal Housewares',
      [supplier('Leeds',
                category('Housewares', 'Seasonal') ) ]],
     ['Tabletop & Serving',
      [supplier('Leeds',
                category('Housewares', 'Tabletop & Serving') ) ]],
     ['Wine Collection',
      [supplier('Leeds',
                category('Housewares', 'Wine Collection') ) ]],
     ['Vases',
      [match('name', 'vase'),
       supplier('Norwood',
                category('AWARD', 'VASE') ) ] ],
    ] ],
 ['Health & Personal Care',
  [supplier('Gemline',
            category('Gifts', 'Fitness/Wellness') ),
   supplier('Norwood',
            match('name', 'growth chart'), # Only 40253
            all(category('HEALTH'),
                match('name', 'thermometer')), # Only 40014
            all(category('HEALTH'),
                match('name', ['flu', 'CPR'])), # Only 400693, 50049
            category('HEALTH', 'SPA') ),
   supplier('High Caliber Line',
            category('Healthy Living') ),
   supplier('Prime Line',
            category('Health Wellness'),
            category('Personal Care')),
  ],[
     ['First Aid Kits',
      [match('name', 'first aid'),
       supplier('Leeds',
                all(category('Outdoor Living', 'Excursion'),
                    match('name', 'first aid') ),
                category('Safety & Auto', 'Personal Safety') ),
       supplier('Lanco',
                category('Health', 'First Aid Kit') ),
       supplier('Norwood',
                category('HEALTH', 'FIRSTAID') )]],
     ['Bandage Dispensers',
      [match('name' ,['bandage caddy', 'bandage dispenser', 'bandage case']),
       supplier('Lanco',
                category('Health', 'Bandage Dispenser') ),
       supplier('Norwood',
                category('HEALTH', 'BANDAGE') )]],
     ['Sanitizers',
      [match('name', ['hand cleaner', 'hand sanitizers']),
       supplier('Lanco',
                category('Hand Sanitizers', 'Hand Sanitizers'),
                category('Candles / Bath / Body', 'Hand Sanitizers') ),
       supplier('High Caliber Line',
                category('Sanitizers') ),
       supplier('Prime Line',
                category('Hand Sanitizer') )
      ],[ ['Hand Sanitizers',
           [match('name', 'hand', 1)] ]
      ] ],
     ['Stain Removers',
      [match('name', 'stain remove'),
       supplier('Lanco',
                category('Travel / Personal Care', 'Stain Removers'))
      ] ],
     ['Pedometers',
      [match('name', ['pedometer', 'step-meter', 'step meter']),
       supplier('Leeds',
                all(category('Outdoor Living', 'Excursion'),
                    match('name', 'pedometer') ),
                category('Health & Wellness', 'Pedometers') ),
       supplier('High Caliber Line',
                category('Pedometer') ),
       supplier('Lanco',
                category('Travel / Personal Care', 'Pedometer') ),
       supplier('Bullet Line',
                category('Fitness & Recreation', 'Pedometers') ) ]],
     ['Fitness Sets',
      [match('name', %w(set kit), 1),
       match('name', %w(exercise fitness)),
       supplier('Leeds',
                category('Health, Safety & Auto', 'Fitness Sets') ) ]],
     ['Personal Wellness',
      [supplier('Leeds',
                category('Health & Wellness', 'Personal Wellness & Fitness') ) ]],
     ['Dental Products',
      [match('name', %w(floss toothbrush tooth\ brush toothpick))]],
     ['Pill Cases',
      [match(%w(name description), ['pill hold', 'pill case', 'pill box', 'pill tube', 'pill caddy']),
       supplier('Lanco',
                category('Health', 'Pill Cases') ),
       supplier('Norwood',
                category('HEALTH', 'PILLBOX') )]],
     ['Pill Cutters',
      [match('name', 'pill cut'),
       supplier('Lanco',
                category('Health', 'Pill Cutters') )]],
     ['Bug Repellant',
      [match('name', ['bug zapper', 'bug repellant']),
       supplier('Lanco',
                category('Sun / Outdoors / Sports', 'Bug Repellant') )
      ] ],
     ['Outlet Covers',
      [supplier('Lanco',
                category('Health', 'Outlet Cover') )]],
     ['Shoe Accessories',
      [match('name', %w(shoe callus)),
       supplier('Lanco',
                category('Travel / Personal Care', 'Shoe Items') ) ]],
     ['Soap',
      [match('name', 'soap') ] ],
     ['Wipes & Cleaning Cloths',
      [match('name', ['wipes', 'cleaning cloth', 'towelette']) ] ],
     ['Jump Rope',
      [match('name', 'jump rope') ] ],
     ['Fans',
      [match('name', 'mini fan'),
       supplier('Lanco',
                category('Travel / Personal Care', 'Fans') ),
       supplier('High Caliber Line',
                all(category('Toys & Games'),
                    match('name', 'fan') ) ),
       supplier('Bullet Line',
                category('Fitness & Recreation', 'Fans') ) ]],
     ['Mirrors',
      [match('name', 'mirror'),
       supplier('Lanco',
                category('Travel / Personal Care', 'Mirrors') ) ]],
     ['Lint Brushes',
      [match(%w(name description), ['lint brush', 'lint roller']),
       supplier('Lanco',
                category('Travel / Personal Care', 'Lint Brushes') ) ]],
     ['Brush & Combs',
      [supplier('Lanco',
                category('Travel / Personal Care', 'Brush & Combs') ) ]],
     ['Sewing Kits',
      [match('name', ['sewing kit', 'mending kit']),
       supplier('Lanco',
                category('Travel / Personal Care', 'Sewing Kits') ) ]],
     ['Dental Products',
      [supplier('Lanco',
                category('Travel / Personal Care', 'Dental Products') ) ]],

     ['Sun Kits',
      [supplier('Lanco',
                category('Sun / Outdoors / Sports', 'Sun Kits') ) ]],
     ['Lip Balm',
      [match('name', %w(lipbalm lip\ balm)),
       supplier('Lanco',
                category('Sun / Outdoors / Sports', 'Lipbalm') ) ]],
     ['Outdoor Kits',
      [supplier('Lanco',
                category('Sun / Outdoors / Sports', 'Outdoor Kits') ) ]],
     ['Sunblock',
      [match('name', %w(sunscreen sun\ screen sunblock sun\ block)),
       supplier('Lanco',
                category('Sun / Outdoors / Sports', 'Sunscreen') ),
       supplier('Norwood',
                category('HEALTH', 'SUN') ) ]],
     ['Lotions',
      [match('name', 'lotion') ] ],
     ['Manicure',
      [match('name', ['manicure', 'nail file', 'emery board', 'pedicure']) ]],

     ['Info Guide',
      [supplier('Norwood',
                category('HEALTH', 'INFOGUIDE')) ]],

    ] ],

 ['Personal Accessories',
  [
  ],[
     ['Umbrellas & Rainwear',
      [match('name', 'umbrella'),
       supplier('Leeds', duplicate(['Umbrellas'], 'supplier_categories')),
       supplier('Lanco',
                category('Sun / Outdoors / Sports', 'Umbrellas') ),
       supplier('Bullet Line',
                category('Fitness & Recreation', 'Umbrellas') ),
      ] ],
     ['PDAs & Phone Holders',
      [supplier('Lanco',
                category('Bags / Containers', 'PDA Holder') ),
       supplier('LogoIncluded',
                category('Phone Cases') ) ] ],
     ['Eyeglass Accessories',
      [],[
          ['Eyeglass Cases',
           [match('name', /((sun)|(eye)| )glass.+case/) ] ],
          ['Eyeglass Straps',
           [match('name', /((sun)|(eye)| )glass.+strap/) ] ],
          ['Eyeglass Clips',
           [match('name', /((sun)|(eye)| )glass.+clip/) ] ],
         ] ],
     ['Sun Glasses',
      [match('name', 'sunglasses'),
       exclude(match('name', 'case'))] ],
     ['Badge Holders',
      [match('name', %w(badge ident)),
       match('description', 'badge holder'),
       supplier('Lanco',
                category('Badge Holders / Ribbons', 'Badge Holders') ),
       supplier('High Caliber Line',
                category('Badge Holders'),
                category('Office', 'Badge Holders')),
       supplier('Norwood',
                category('OFFICE', 'BADGE') ),
       supplier('Bullet Line',
                category('Keytags & Badge Holders', 'Badge Holders') ) ]],
     ['Lanyards',
      [match('name', 'lanyard'),
       supplier('Lanco',
                category('Badge Holders / Ribbons', 'Badge Holder Accessories') ),
       supplier('High Caliber Line',
                category('Lanyards'),
                category('Lanyards', 'Econo Lanyards'))
      ],[
         ['Eco Friendly Lanyards',
          [supplier('High Caliber Line',
                category('Lanyards', 'Eco Friendly Lanyards') ) ] ]
        ] ],
     ['Dog Tags',
      [supplier('Lanco',
                category('Badge Holders / Ribbons', 'Dog Tags') )]],
     ['Carabiners',
      [supplier('Lanco',
                category('Carabiners / Key Chains', 'Carabiner') ),
       supplier('Leeds',
                category('Keychains, Keylights & Carabiners', 'Carabiners') ),
       supplier('High Caliber Line',
                category('Carabiners') ),
       supplier('Bullet Line',
                category('Keytags & Badge Holders', 'Carabiners'),
                category('Lighting', 'Carabiners') ) ]],
     ['Key Chains',
      [match(%w(name description), ['key chain', 'keychain', 'key holder', 'key tag']),
       supplier('High Caliber Line',
                category('Key Chains'),
                category('Key Chains', 'Alcraft Key Chains')),
       supplier('Prime Line',
                category('Key Holders') ),
       supplier('Lanco',
                category('Carabiners / Key Chains', 'Keychains') ),
       supplier('Norwood',
                category('AUTO', 'KEYCHAIN') ),
       supplier('Leeds',
                category('Keychains, Keylights & Carabiners', 'Keychains') ),
       supplier('Bullet Line',
                category('Keytags & Badge Holders', 'Key Rings'),
                category('Keytags & Badge Holders', 'Key Tags'))
      ],[
         ['Bottle Opener Key Chains',
          [match('name', 'opener', 1),
           supplier('Bullet Line',
                    all(category('Keytags & Badge Holders', 'Bottle Openers'),
                        match('name', 'key') ) ) ]],
         ['Key Chains with Light',
          [match('name', 'light', 1),
           supplier('Leeds',
                    category('Keychains, Keylights & Carabiners', 'Keylights') ),
           supplier('Bullet Line',
                    category('Lighting', 'Key-Lights') ) ] ],
         ['Flash Drive Key Chains',
          [supplier('LogoIncluded', match(%w(name description), ['key chain', 'keychain', 'key holder']))]],
        ] ],
     ['Wallets',
      [match('name', %w(wallet checkbook)),
       match('description', ['travel wallet', 'leather organizer', 'passport jacket']),
       supplier('Leeds',
                all(category('Travel Gifts', 'Clocks & Wallets'),
                    match('name', ['wallet', 'passport'])) ),
       supplier('Gemline',
                category('Business Accessories', 'Travel Wallets') ) ]],
     ['Money Clips',
      [match('name', ['money clip', 'money band'])] ],
     ['Wristbands',
      [match(%w(name description), [/wrist.*band/, 'bracelet']) ] ],
     ['Watches',
      [supplier('Leeds',
                category('Watches', 'Watches') )
      ],[
         ['Cutter & Buck Watches',
          [supplier('Leeds',
                    category('Watches', 'Cutter & Buck Watches') ) ]],
         ['Executive Watches',
          [supplier('Leeds',
                    category('Watches', 'Executive') ) ]],
         ['Watch Gift Sets',
          [supplier('Leeds',
                    category('Watches', 'Gift Sets') ) ]],
         ['Wenger Watches',
          [supplier('Leeds',
                    category('Watches', 'Wenger Watches') ) ]],
        ] ],
     dup('Travel', 'Personal Travel'),
     ['Womens Accessories',
      [supplier('Gemline',
                category('Women`s', 'Travis & Wells')) ]],
    ] ],

 ['Recreation',
  [supplier('Leeds',
            category('Gusto', 'Explore') ),
   supplier('High Caliber Line',
            category('Sports and Recreation') ),
   supplier('Bullet Line',
            category('Fitness & Recreation', 'Summer/Outdoor Items')),
  ],[
     ['Binoculars & Telescopes',
      [match('name', %w(binocular telescope monocular)),
       supplier('Leeds',
                category('Outdoor Living', 'Binoculars') ),
       supplier('High Caliber Line',
                category('Binoculars') ) ]],
     dup('Games & Toys', 'Outdoor Games'),
     dup('Health & Personal Care', 'First Aid Kits'),
     dup('Health & Personal Care', 'Pedometers'),     
     ['Compasses',
      [match('name', 'compass'),
       supplier('Leeds',
                all(category('Outdoor Living', 'Excursion'),
                    match('name', 'compass') ) ) ]],
     ['Beach ware',
      [match('name',%w(beach)),
       match('name', 'towel', 1),
       supplier('Leeds',
                category('Towels', 'Beach Towels') )]],
     ['Golf',
      [match('name', 'golf'),
       supplier('Leeds',
                category('Recreation', 'Golf') ) ,
       supplier('Norwood',
                category('GOLF') ),
      ],[
         ['Ladies Golf',
          [supplier('Norwood',
                    category('GOLF', 'LADIES') ) ] ],
         ['Golf Balls',
          [match('name', 'balls', 1),
           supplier('Lanco',
                    category('Golf', 'Golf Balls') ),
           supplier('Norwood',
                    category('GOLF', 'GOLFBALL') ) ] ],
         ['Golf Club',
          [supplier('Norwood',
                    category('GOLF', 'GOLFCLUB') ) ] ],
        ['Golf Kits',
          [match('name', 'kit', 1),
           match('name', 'putter'),
           supplier('Lanco',
                    category('Golf', 'Golf Kits') ),
           supplier('Norwood',
                    category('GOLF', 'EVENT') )]],
         ['Golf Tags',
          [match('name', 'tag', 1),
           supplier('Lanco',
                    category('Golf', 'Golf Tags') ) ]],
         ['Golf Towels',
          [match('name', 'towel', 1),
           supplier('Lanco',
                    category('Golf', 'Golf Towels') ),
           supplier('Leeds',
                    category('Towels', 'Golf Towels') )]],
         ['Tees, Ball Markers & Divot Tools',
          [match('name', ['tees', 'ball marker'], 1),
           match('name', 'divot'),
           supplier('Leeds',
                    all(category('Luggage & Golf', 'Golf'),
                        match('name', 'green'))),
           supplier('Lanco',
                    category('Golf', 'Tees, Markers & Divot Tools') ),
           supplier('Norwood',
                    category('GOLF', 'TEE') )]],
        ] ],
     ['Kites',
      [match('name', 'kite')] ],
     ['Camping',
      [match('name', 'tent') ]],
     ['Outdoor Seating',
      [match('name', ['chair', 'recliner']),
       match(%w(name description), ['stadium seat', 'stadium cushion', 'stadium kushion', 'outdoor lounger', 'seat cushion', /chair.+fold/i]),
       all(match('name', %w(chair seat)), match('description', %w(outdoor beach sporting stadium))),
       exclude(match('name', 'stress reliever')),
       supplier('Norwood',
                category('OUTDOOR', 'CHAIRS') ),
       supplier('Lanco',
                category('Sun / Outdoors / Sports', 'Cushions'),
                category('Sun / Outdoors / Sports', 'Seats') ) ] ],
     ['Excursion',
      [supplier('Leeds',
                category('Outdoor Living', 'Excursion') ) ] ],
    ] ],

 ['Stationery',
  [supplier('Gemline',
            ['New Padfolios', 'Padfolios $10 - $20', 'Padfolios 20+', 'Padfolios Under $10', 'Closeout Padfolios'].collect do |name|
              category('Padfolios', name)
            end)
  ],[
     ['Jotters',
      [match('name', 'notepad'),
       match('name', 'jotter'),
       supplier('Leeds',
                category('Stationery', 'Jotters'),
                category('Stationery', 'Notebooks')),
       supplier('Norwood',
                category('MEETING', 'JOTTERS') ),
       supplier('Prime Line',
                all(category('Computer Bags / Portfolios'),
                    match('name', 'pad') ) ),
       supplier('Lanco',
                category('Journals / Portfolios', 'Notebooks'),
                category('Journals / Portfolios', 'Memo Pads')),
       supplier('High Caliber Line',
                match('name', 'notebook') )
      ],[
         ['Recycled Jotters',
          [supplier('Leeds',
                    all(category('EcoSmart', 'Jotters & Journals'),
                        match('name', %w(pad jotter))) ) ] ],
        ]],
     ['Journals',
      [match('name', 'journal'),
       supplier('Leeds',
                category('JournalBooks', 'Bound'),
                category('JournalBooks', 'Spiral') ),
       supplier('Lanco',
                category('Journals / Portfolios', 'Journal Books') ),
       supplier('Prime Line',
                category('Notebooks | Journals') ),
       supplier('Bullet Line',
                category('Stationery', 'Spiral Notebooks') )
      ],[
         ['Recycled Journals',
          [supplier('Leeds',
                    all(category('EcoSmart', 'Jotters & Journals'),
                        match('name', 'journal')) ) ] ],
        ]],
     ['Padfolios & Writing Pads',
      [match('name', 'padfolio'),
       supplier('Leeds',
                category('Stationery', 'Padfolios & Writing Pads') ),
       supplier('Gemline',
                category('Padfolios', 'Writing Pads'),
                match('name', ['writing pad', 'tech organizer', 'e-organizer']) ),
       supplier('Lanco',
                category('Journals / Portfolios', 'Portfolios') ),
       supplier('Norwood',
                category('MEETING', 'PAD'),
                category('MEETING', 'FOLDERS')),
      ],[
         ['Jr. Padfolios',
          [match('name', 'jr', 1),
           supplier('Norwood',
                category('MEETING', 'JUNIORS') ) ] ],
         ['Kid Friendly Padfolios',
          [supplier('Gemline',
                    category('Kid-friendly', 'Padfolios') ) ] ],
         ['Leather Padfolios',
          [supplier('Gemline',
                    category('Padfolios', 'Leather') ) ]],
         ['Recycled Pads',
          [match(%w(name description), 'recycle', 1),
           supplier('Leeds',
                    category('EcoSmart', 'Padfolios & Writing Pads') ) ]],
        ] ],
     ['Planners',
      [supplier('Leeds',
                category('Stationery', 'Planners') ) ]],
     ['Ringbinders',
      [match('name', ['ringfolio', 'ringbinder']),
       supplier('Leeds',
                category('Stationery', 'Ringbinders') ),
       supplier('Gemline',
                category('Padfolios', 'Ringbinders') )]],
    ] ],

 ['Tools',
  [supplier('Leeds',
            category('Tools & Lighters', 'Tools'),
            category('Gusto', 'Construct') ),
   supplier('PrimLine',
            category('Tools') ),
   supplier('Norwood',
            category('AUTO', 'TOOLS') ),
   supplier('High Caliber Line',
            category('Tools') )
  ],[
     dup('Tools / Knives', 'Ice Scraper'),
     ['Bag Clips',
      [match('name', 'bag clip'),
       supplier('Lanco',
                category('Tools / Knives', 'Bag Clips') ),
       supplier('Norwood',
                all(category('HOUSEWARES', 'UTENSILS'),
                    match('name', 'clip') ) ),
       supplier('Bullet Line',
                all(category('Desktop', 'Memo Holders/Clips'),
                    match('name', 'clip') ) )]],
     ['Bottle Openers',
      [match('name', 'bottle opener'),
       supplier('High Caliber Line',
                category('Bottle Openers'),
                match('description', 'bottle opener' )),
       supplier('Lanco',
                category('Tools / Knives', 'Bottle Opener') ),
       supplier('Bullet Line',
                category('Keytags & Badge Holders', 'Bottle Openers') ) ]],
     ['Jar Openers',
      [match('name', 'jar opener') ]],

     ['Flashlights',
      [match(%w(name description), %w(flashlight fingerlight)),
       supplier('High Caliber Line',
                category('Flashlights') ),
       supplier('Lanco',
                category('Tools / Knives', 'Flashlights') ),
       supplier('Prime Line',
                match('name', 'torch') ),
       supplier('Norwood',
                category('AUTO', 'FLASH') ),
       supplier('Bullet Line',
                category('Lighting', 'Flashlights'),
                category('Travel, Health & Beauty', 'Flashlights') ),

      ],[
         ['Emergency Flashlights',
          [supplier('Leeds',
                    category('Flashlights', 'Emergency & Safety') ) ]],
         ['Everyday Flashlights',
          [supplier('Leeds',
                    category('Flashlights', 'Everyday') ) ]],
         ['Dynamo Flashlights',
          [supplier('Leeds',
                    category('Flashlights', 'Dynamo') ),
           supplier('Bullet Line',
                    category('Lighting', 'Wind-Up Flashlights') )]],
         ['LED Flashlights',
          [match('name', ['LED', 'L.E.D.'], 1) ]],
         ['Specialty Flashlights',
          [supplier('Leeds',
                    category('Flashlights', 'Specialty') ) ]],

        ] ],
     ['Knives',
      [match(%w(name description), %w(knive knife cutter)),
       supplier('Lanco',
                category('Tools / Knives', 'Knives') ),
       supplier('Norwood',
                category('AUTO', 'KNIVES') ),
       supplier('Bullet Line',
                category('Tools', 'Knives') ),
      ],[
         ['Wenger Knives',
          [supplier('Leeds',
                    category('Tools & Lighters', 'Wenger Knives') ) ]],
        ] ],
     ['Lighters',
      [match('name', 'lighter'),
      ],[
         ['Zippo Lighters',
          [supplier('Leeds',
                    category('Tools & Lighters', 'Zippo Lighters') )]],
        ] ],
     ['Pliers',
      [match('name', 'pliers', 1)
      ] ],
     ['Screwdrivers',
      [match(%w(name description), %w(screwdriver screw\ driver)),
       supplier('Lanco',
                all(category('Tools / Knives', 'Screwdriver & Tool Set'),
                    match('name', 'screwdriver') ) ) ]],
     ['Tape Measures',
      [match(%w(name description), 'tape measure'),
       supplier('Lanco',
                category('Tools / Knives', 'Tape Measure') ),
       supplier('Norwood',
                category('AUTO', 'MEASURE') ),
       supplier('Bullet Line',
                category('Tools', 'Tape Measures') )]],
     ['Tool Sets',
      [match('name', ['tool set', 'tool kit', 'gift set'], 1),
       supplier('Leeds',
                all(category('Tools & Lighters', 'Tools'),
                    match('name', ['tool set', 'tool kit']) ) ),
       supplier('Lanco',
                all(category('Tools / Knives', 'Screwdriver & Tool Set'),
                    match('name', 'set') ) ),
       supplier('Gemline',
                all(category('Gifts', 'Home Improvement'),
                    match('name', %w(kit set)) ) ) ]],
     ['Multi Tools',
      [match('name', 'multi-', 1),
       supplier('Leeds',
                all(category('Tools & Lighters', 'Tools'),
                    match('name', 'multi-tool') ) ),
       supplier('Lanco',
                all(category('Tools / Knives', 'Screwdriver & Tool Set'),
                    match('name', 'pocket tool')) ),
       supplier('Bullet Line',
                category('Tools', 'Knives'),
                category('Tools', 'Multi-Function Tools') ), ]],
     ['Locks',
      [match('name', ' lock') ]],
    ] ],

 ['Writing',
  [ supplier('High Caliber Line',
             category('Writing Instruments') )
  ],[
     ['Highlighters',
      [match('name', 'highlighter', 1),
       match('description', ['hi-lighter', 'highlighters']),
       supplier('High Caliber Line',
                category('Writing Instruments', 'Highlighters, Markers and Acceso') ),
       supplier('Lanco',
                category('Writing Instruments', 'Highlighters'),
                category('Office / Computer Essentials', 'Highlighters')),
       supplier('Prime Line',
                match('name', ['tri-liter', 'bi-liter']) ),
       supplier('Norwood',
                all(match('name', ['highlighter', 'combo writer']),
                    category('WRITE', 'PENCIL') ) )]],
     ['Markers',
      match('name', 'marker', 1) ],
     ['Pencils',
      [match('name', 'pencil'),
       supplier('Norwood',
                all(match('name', 'pencil'),
                    category('WRITE', 'PENCIL') ) ),
       supplier('Gemline',
                category('Writing Instruments', 'Pencils') ) ]],
     ['Pens',
      [supplier('Leeds',
                category('Pens-Plastic', 'Value Pens & Highlighters') ),
       supplier('Gemline',
                ['Pens $3-$5', 'Pens $5-$10', 'Pens 10+', 'Pens under $3'].collect do |name|
                  category('Writing Instruments', name)
                end),
       supplier('High Caliber Line',
                category('Writing Instruments', 'Pens'),
                category('Writing Instruments', 'Executive Pens') ),
       supplier('Lanco',
                category('Writing Instruments', 'Stick Pens') ),
       supplier('Prime Line',
                match('name', %w(pen writer)) ),
       supplier('Norwood',
                match('name', 'syringe pen'), # only 40017
                category('WRITE', 'GIFTPEN'),
                category('WRITE', 'PEN50'),
                category('WRITE', 'PEN150')),
       supplier('Bullet Line',
                category('Writing Instruments', 'Plastic Pens') ),
                
      ],[
         ['Light Up Pens',
          [match('name', 'light', 1),
           supplier('Bullet Line',
                    category('Writing Instruments', 'Light-Up Pens') ) ] ],
         ['Pen Gift Boxes',
          [match('name', ['gift box', 'pen box'], 1),
           supplier('Bullet Line',
                    category('Writing Instruments', 'Gift Boxes for Pens') ) ] ],
         ['Branded Pens',
          [supplier('Leeds',
                    category('Pens-Metal', 'Branded') ) ]],
         ['Multi Function Pens',
          [match('name', %w(usb laser), 1),
           supplier('Leeds',
                    category('Pens-Metal', 'Multi-Function') ),
           supplier('High Caliber Line',
                    category('Writing Instruments', 'Laser Pointers & Light Up') ),
           supplier('Lanco',
                    category('Writing Instruments', 'Pens with Staple Remover') )]],
         ['Pen Sets',
          [supplier('Leeds',
                    category('Pens-Metal', 'Gift Sets') ),
           supplier('Gemline',
                    category('Writing Instruments', 'Pen Sets') ) ]],
         ['Scripto Plastic Pens',
          [supplier('Leeds',
                    category('Pens-Plastic', 'Scripto') ) ]],

         ['Click Pens',
          [match('name', 'click', 1),
           supplier('Prime Line',
                    match('description', ['click action', 'click-action'])),
           supplier('Gemline',
                    category('Writing Instruments', 'Clicks') ),
           supplier('Lanco',
                    category('Writing Instruments', 'Click Pens') )]],
         ['Roller Ball Pens',
          [match('name', 'roller', 1),
           match('name', 'rollerball'),
           supplier('Gemline',
                    category('Writing Instruments', 'Roller Balls'),
                    category('Writing Instruments', 'Roller Needle')),
           supplier('Leeds',
                    category('Pens-Metal', 'Roller Ball') )]],
         ['Ballpoint Pens',
          [match(%w(name description), 'ballpoint'),
           supplier('Leeds',
                    category('Pens-Metal', 'Ballpoint') ),
           supplier('Gemline',
                    category('Writing Instruments', 'Ballpoint') ) ]],
         ['Gel Pens',
          [match('name', 'gel', 1),
           supplier('Gemline',
                    category('Writing Instruments', 'Gel') ),
           supplier('Bullet Line',
                    category('Writing Instruments', 'Gel Pens') ) ] ],
         ['Metal Pens',
          [supplier('Bullet Line',
                    category('Writing Instruments', 'Metal Pens') )
          ], [
              ['Aluminum Pens',
               [match('material', 'Aluminum', 2)
               ] ],
              ['Brass Pens',
               [match('material', 'brass', 2)
               ] ],
              ['Stainless Steel Pens',
               [match('material', 'stainless', 2),
                supplier('Gemline',
                         category('Writing Instruments', 'Stainless') ) ] ],
             ] ],
         ['Twist Pens',
          [match('name', 'twist', 1),
           supplier('Prime Line',
                    match('description', 'twist-action')),
           supplier('Gemline',
                    category('Writing Instruments', 'Twists') )]],
         ['Recycled Pens',
          [match(%w(name description), 'recycle', 1),
           supplier('Gemline',
                    category('Writing Instruments', 'Recycled') ),
           supplier('Leeds',
                    category('EcoSmart', 'Pens')) ]],
         ['Specialty Pens',
          [supplier('Lanco',
                    category('Writing Instruments', 'Specialty Pens') ) ]],
         ['Pen Holders & Cases',
          [supplier('Lanco',
                    category('Writing Instruments', 'Pen Holder/Cases') ),
           supplier('Norwood',
                    all(match('name', %w(box pouch)),
                        category('WRITE', 'GIFTPEN') ) )]],
         ['Eco Friendly Pens',
          [supplier('High Caliber Line',
                    category('Writing Instruments', 'Eco Friendly Pens') ) ] ],
        ] ],
    ] ],

 ['Other',
  [
  ],[
     ['Dog Collars & Leashes',
      [match('name', %w(dog\ collar leashe)),
       supplier('High Caliber Line',
                category('Dog Collars & Leashes'),
                category('Lanyards', 'Dog Leashes Lanyards') ) ] ],
     ['Pet Accessories',
      [match('name', 'pet'), ]],
     ['Light Ups',
      [supplier('High Caliber Line',
                category('Light Up') )
      ],[
         ['Light Up Pens',
          [match('name', 'pen', 1) ] ],
         ['Other Light Ups',
          [supplier('High Caliber Line',
                    category('Light Up', 'Others') ) ]],
         ['Light Up Necklaces',
          [supplier('High Caliber Line',
                    category('Light Necklaces') ) ]],
         ['Light Up Buttons',
          [match('name', 'button', 1)]],
        ]],
     ['Neoprene',
      [match('description', 'neoprene'),
       supplier('High Caliber Line',
                category('Neoprene') ) ]],
     ['Ribbons',
      supplier('Lanco',
               category('Badge Holders / Ribbons', 'Custom Imprinted Ribbons') ) ],
     ['Blankets',
      [match('name', 'blanket'),
       supplier('Norwood',
               category('OUTDOOR', 'BLANKETS') ),
       supplier('Leeds',
                category('Outdoor Living', 'Blankets') ),
       supplier('Prime Line',
                category('Blankets') ) ] ],
     ['Combo Products',
      [supplier('Prime Line',
                category('Combos') ) ]],
     ['Whistles',
      [match('name', 'whistle') ]],
     ['Electronics Cases',
      [all(match('name', 'case'),
           match('name', %w(ipod nano camera)))]],
     ['Gardening',
      [match('name', 'garden') ]],                
    ] ],

 ['Ecologically Friendly',
  [supplier('High Caliber Line',
            category('Eco Friendly Products') ),
   supplier('Gemline',
            category('Eco-Choice', 'New Eco-Choice'),
            category('Eco-Choice', 'Under $10'),
            category('Eco-Choice', '$10+')),

  ],[
     ['Organic',
      [supplier('Gemline',
                category('Eco-Choice', 'Organic')) ]],
     ['Growables',
      supplier('Leeds',
               category('Desktop', 'Growables'),
               category('EcoSmart', 'Growables') ) ],
     ['Gusto',
      supplier('Leeds',
               category('Gusto', 'Conserve') ) ],
     ['Recycled',
      [supplier('Gemline',
                category('Eco-Choice', 'Recycled') ),
      ],[
         dup('Bags', 'Backpacks', 'Recycled Backpacks'),
         dup('Bags', 'Business Bags', 'Recycled Business Bags'),
         dup('Bags', 'Duffel Bags', 'Recycled Duffel Bags'),
         dup('Bags', 'Tote Bags', 'Recycled & Organic Totes'),
         dup('Coolers', 'Recycled Coolers'),
         dup('Housewares', 'Beverage & Bar', 'Recycled Bar Sets'),
         dup('Drinkware', 'Recycled Drinkware'),
         dup('Stationery', 'Jotters', 'Recycled Jotters'),
         dup('Stationery', 'Journals', 'Recycled Journals'),
         dup('Stationery', 'Padfolios & Writing Pads', 'Recycled Pads'),
         dup('Writing', 'Pens', 'Recycled Pens'),
        ]],
    ] ],
     
]
  end
end
