# -*- coding: utf-8 -*-
class NewCategoryTransform
  def remove_sub_dups(list)
    list.delete_if do |sub|
      list.find { |s| (s.length > sub.length) && (s[0...(sub.size)] == sub) }
    end
  end

  def apply_rules(pd)
    remove_sub_dups(pd.supplier_categories)
    pd.categories = []
    @rules.each do |rule, category|
      if res = rule.call(pd, category)
        pd.categories = (pd.categories + res).uniq
      end
    end

    # Remove parent categories after all rules to work correct with exclude
    remove_sub_dups(pd['categories'])

    if Rails.env.production?
      pd.categories = [['Other']] if pd.categories.empty?
    else
      pd.categories += pd.categories.collect { |cat| ['YBySupplier', @supplier] + cat }

      unused_categories = (pd.supplier_categories - @used_categories).collect { |cat| cat.collect { |s| s.gsub('/', 'slash') } }
      unused_categories << ['AAA'] if pd.categories.empty?
      unless unused_categories.uniq.empty?
        pd.categories += unused_categories.collect { |cat| ['XUnOrganized', @supplier] + cat }
      end

      pd.categories += (pd.supplier_categories - unused_categories).collect { |cat| ['ZSuppliers', @supplier] + cat }
    end
  end

  attr_reader :supplier
  def initialize(supplier)
    @supplier = supplier
    @rules = []
    @used_categories = []
    process_category(data, [])
  end

private
  def process_category(records, parent_category)
    records.each do |name, rules, sub_records|
      category = parent_category + [name]
      [rules].flatten.compact.each { |r| @rules << [r, category] }
      process_category(sub_records, category) if sub_records
    end
  end

  def sup(name, *rules)
    return nil unless name == @supplier
    rules.flatten.compact
  end

  def cat(*cat)
    Proc.new do |record, match_category|
      @used_categories << cat unless @used_categories.include?(cat)
      [match_category] if record['supplier_categories'].find { |c| c[0...cat.length] == cat }
    end
  end

  def always(exclude = nil)
    Proc.new do |record, match_category|
      if exclude
        [match_category[0..(-1-exclude)]]
      else
        [match_category]
      end
    end
  end

  def match(properties, values, exclude = nil)
    properties = [properties].flatten
    values = [values].flatten.collect { |v| v.is_a?(String) ? v.downcase : v }
    Proc.new do |record, match_category|
      if exclude
        if exclude.is_a?(Integer)
          cat = match_category[0..(-1-exclude)]
        else
          cat = exclude
        end
        next nil unless record.categories.find { |cs| cs[0...(cat.length)] == cat }
      end
#      puts "Match #{match_category.inspect} : #{properties.inspect} : #{values.inspect}"
      match = properties.find do |property|
        if record[property]
          val = record[property]
        else
          list = record.variants.collect { |v| v[property] || (v.properties[property]) }.compact.uniq
          next if list.empty?
          val = list.join(' ')
        end
        res = values.find do |v|
          if v.is_a?(String)
            val.downcase.include?(v)
          else
            v === val
          end
        end
#        puts " \- #{property}: #{val.inspect} => #{res}"
        res
      end
      match ? [match_category] : nil
    end
  end

  def exclude(elements)
    Proc.new do |record, match_category|
      [elements].flatten.compact.each do |elem|
        if elem.call(record, match_category)
          record.categories.delete_if { |cat| cat == match_category }
        end
      end
      nil
    end
  end

  def duplicate(src, field = 'categories')
    Proc.new do |record, match_category|
      ret = record[field].collect { |cat| (cat[0...(src.length)] == src) ? (match_category + cat[src.size..-1]) : nil }.compact
      next nil if ret.empty?
      @used_categories += ret
      ret
    end
  end

  def dup(*src)
    [src.last, [duplicate(src)]]
  end

  def all(*list)
    list = list.flatten.compact
    Proc.new do |record, match_category|
      result = nil
      list.find do |proc|
        not (result = proc.call(record, match_category))
      end
      result
    end
  end

  def data
[
  ['Apparel',
  [sup('Ash City', cat('Catalog', 'NESPORT')) # Kludge for 68627
  ],[
     ['Hats & Caps',
      [match('name', /(?:^| )hat(?:$| |\/)/),
       exclude(match('name', ['stress', 'keychain', 'hat clip'])),
       sup('High Caliber Line', cat('Headwear', 'Regular') ),
       sup('Norwood',
           cat('OUTDOOR', 'HEADWEAR'),
           all(cat('GOLF'),
               match('name', 'cap') ) ),
       sup('Ash City',
           all(cat('Accessories'),
               match('name', 'cap'))),
       sup('Hit Promotional Products', cat('Headwear') ),
       sup('Sweda', cat('Headwear') )
      ],[
         ['Visors',
          [match('name', 'visor', 1), ] ],
         ['Knit Caps',
          [match('name', 'knit', 1) ] ],
        ] ],
     ['Outerwear',
      [sup('Ash City',
           cat('Outerwear'),
           match('name', 'jacket') ) ],
      %w(Windvests Windshirts Insulated\ Seam-Sealed Teflon Soft\ Shells Leather Insulated Seam-Sealed Reversible\ Jackets Reversible\ Vests Workwear).collect do |name|
        [name, [sup('Ash City', match('name', name.gsub(/s$/,''), 1))]]
      end + 
      [
       ['Performance Jackets',
        [sup('Ash City',
             all(match('name', 'jacket', 1),
                 match(%w(name material), 'performance', 1) ) ) ] ],
       ['Techno series',
        [sup('Ash City',
             match('description', 'EZAWAY', 1) ) ] ],
      ] ],
     ['Soft Shell',
      [sup('Ash City', cat('Soft Shell') ) ],
      [
       ['Performance Jackets',
        [sup('Ash City',
             all(match('name', 'jacket', 1),
                 match(%w(name material), 'performance', 1) ) ) ] ],
       ['Performance Vests',
        [sup('Ash City',
             all(match('name', 'vest', 1),
                 match(%w(name material), 'performance', 1) ) ) ] ],
      ] ],
     
     ['Fleece',
      [sup('Ash City', cat('Fleece') ),
       match('name', 'fleece')],
      %w(Vests Microfleece Vintage).collect do |name|
        [name, [sup('Ash City', match('name', name.gsub(/s$/,''), 1))]]
      end + 
      [
       ['Microfleece',
        [sup('Ash City',
             match(%w(name material), 'microfleece', 1) ) ] ],
       ['Poly fleece',
        [sup('Ash City',
             match(%w(name material), 'polyester', 1) ) ] ],
       ['Interactive Fleece',
        [sup('Ash City',
             match('name', 'interactive', 1) ) ] ],
       ['Cotton/Poly Fleece',
        [sup('Ash City',
             all(match(%w(name material), 'cotton', 1),
                 match(%w(name material), 'polyester', 1) ) ) ] ],
       ['Bonded Fleece',
        [sup('Ash City',
             match('name', 'bonded', 1) ) ] ],
      ] ],
     ['Knits',
      [sup('Ash City',
           cat('Knits'),
           match('name', 'polo') ) ],
      %w(Jersey Pique Teflon Edry Textured Eperformance Jacquard Mercerized Interlock Micro\ pima).collect do |name|
        [name, [sup('Ash City', match(%w(name material description), name, 1))]]
      end + 
      [
      ] ],
     ['Wovens',
      [sup('Ash City',
           cat('Wovens') ), ],
      %w(Easy\ care Primalux Twill Teflon Stretch Cotton Denim Service Vintage Wrinkle\ Free Wrinkle\ Resistant).collect do |name|
        [name, [sup('Ash City', match(%w(name material description), name, 1))]]
      end + 
      [
       ['Silk blend',
        [sup('Ash City',
             match(%w(name material description), 'silk', 1) ) ] ],
      ] ],
     ['Active Wear',
      [sup('Ash City', cat('Active Wear') ) ],
      [
      ] ],
     ['Pants',
      [match('name', 'pants', 1)]],
     ['Safety',
      [sup('Ash City', cat('Safety') ) ],
      [
      ] ],
    ] ],
 ['Awards',
  [
  ],[
     ['Acrylics',
      [sup('Norwood', cat('AWARD', 'ACRYLIC') ) ] ],
     ['Art Glass',
      [sup('Norwood', cat('AWARD', 'ART') ),
       sup('Logomark', cat('Crystal Awards') ),
       sup('The Magnet Group', cat('Crystal', 'Art Glass') )
      ] ],
     ['Awards & Plaques',
      [match('name', 'trophy'),
       sup('Norwood', cat('AWARD', 'AWARDS') ),
       sup('Leeds',
           all(cat('Awards', 'Awards'),
               match('name', 'award') ) ),
       sup('Logomark',
           cat('Crystal Awards'),
           cat('Metal and Wood Awards') ),
       sup('The Magnet Group', cat('Crystal', 'Optically Perfect Awards') )
      ],[ 
         ['Dichroic Awards',
          [match(%w(name description), 'dichroic', 1),
           sup('The Magnet Group', cat('Crystal', 'Dichroic Awards') )
          ]],
         ['Star Awards',
          [match('name', 'star', 1),
           sup('The Magnet Group', cat('Crystal', 'Optically Perfect Award Stars') )
          ]],
         ['Globe Awards',
          [match('name', 'globe', 1),
           sup('The Magnet Group', cat('Crystal', 'Optically Perfect Award Globes') )
          ]],
         ['Glass Awards',
          [match(%w(name description material), 'glass', 1),
           sup('The Magnet Group', cat('Crystal', 'Glass Awards') )
          ]],
         ['Jade Glass Awards',
          [match(%w(name description material), 'glass', 1),
           sup('The Magnet Group', cat('Crystal', 'Jade Glass') )
          ]],
         ['Wood Awards',
          [match(%w(name description material), 'wood', 1),
           sup('The Magnet Group', cat('Crystal', 'Wood and Glass Awards') )
          ]],
        ] ],
     ['Clocks',
      [sup('Norwood', cat('AWARD', 'CLOCKS') ) ] ],
#     ['Bases',
#      [sup('Norwood', cat('AWARD', 'BASES') ) ] ],
#     ['Coasters & Beverage Ware',
#      [sup('Norwood', cat('AWARD', 'COASTER') ) ] ],
     ['3D Lasered Crystal',
      [sup('Norwood', cat('AWARD', 'IMAGE3') ),
       sup('The Magnet Group', cat('Crystal', '3D Lasered') )
      ] ],
     ['Specialty Gifts',
      [sup('Norwood', cat('AWARD', 'SPECIALTY') ) ] ],
     ['Vases',
      [sup('Norwood', cat('AWARD', 'VASE') ),
       sup('The Magnet Group', cat('Crystal', 'Vases') )
      ] ],
#     ['Trophies',
#      [sup('Norwood',
#                cat('AWARD', 'TROPHIES') ) ] ],
    ] ],
 ['Calendars',
  [
  ],[
     ['Calendars by Industry', [],
      { 'Agriculture' => %w(4000 4400 1851 3204 1900 5323 7047),
        'Real Estate' => %w(7001 7039 8335 2508 1503 7549 4251),
        'Religious' => %w(1653 1654 1650 2503 2509 3304),
        'Construction' => %w(1600 6100 6101 6102 6103 6104 6105 3206 2302 4425),
        'Utilities' => %w(1722 4101 4152 6702 6100 6101 6102 6103 6104 6105 6201),
        'Manufacturing' => %w(3108 6201 6602 8150 6100 6101 6102 6103 6104 6105 6251),
        'Hospitality' => %w(7231 7025 7229 5323 5351 8228),
        'Insurance' => %w(7039 7001 8125 4251 3110 8335),
        'Health Care' => %w(1301 8371 4251 1400 1403 5323 8203),
        'Retail' => %w(2201 3011 8228 1600 1717 2103),
        'Financial' => %w(7039 7001 4101 4251 8335 4152),
        'Automotive' => %w(1855 1850 5324 3200 1862 3011 7037),
        'Food Industry' => %w(1301 4151 8371 8229 7031 1300 1303),
        'Education' => %w(8153 8320 8330 8350 7569 7303 8960 6350),
      }.collect do |name, nums|
        ["#{name} Calendars",
         [sup('Norwood', match('supplier_num', Regexp.new('^'+nums.join('|')+'$') ) ) ] ]
      end
     ],
     ['Appointment Calendars',
      [sup('Norwood',
           cat('CALENDAR', 'APPT'),
           cat('GV', 'GV_APPT') ) ]],
     ['Commercial Calendars',
      [sup('Norwood', cat('CALENDAR', 'COMM') ) ]],
     ['Custom Calendars',
      [sup('Norwood', cat('CALENDAR', 'CUSTOM') ) ]],
     ['Executive Calendars',
      [sup('Norwood',
           cat('CALENDAR', 'EXEC'),
           cat('GV', 'GV_BUSINESS') ) ]],
     ['Non-Dated Calendars',
      [sup('Norwood', cat('CALENDAR', 'NODATE') ) ]],
     ['Nude Calendars',
      [sup('Norwood', cat('CALENDAR', 'NUDE') ) ]],
     ['Planners',
      [sup('Norwood', cat('CALENDAR', 'PLANNER') ) ]],
     ['Pocket and Desk Calendars',
      [sup('Norwood',
           cat('CALENDAR', 'POCKET'),
           cat('GV', 'GV_MINI') ) ]],
     ['Stick up Calendars',
      [sup('Norwood', cat('CALENDAR', 'SUC') ) ]],
     ['Perpetual Calendars',
      [sup('Logomark', cat('Perpetual Calendars') ) ] ],
    ] ],

 ['Automobile',
  [sup('Norwood', cat('AUTO', 'AUTO'))
  ],[
     ['Auto Accessories',
      [match('name', ['roadside', 'auto visor']),
       match('description', 'car visor'),
       sup('Leeds', cat('Safety & Auto', 'Auto Accessories') ),
       sup('Gemline', cat('Sport & Travel', 'Cargo') ),
       sup('Gemline',
           all(cat('Gifts', 'Safety/Auto'),
               match('name', 'auto detail') ) ),
       sup('High Caliber Line', cat('Auto') ),
       sup('Bullet Line', cat('Travel, Health & Beauty', 'Automotive Accessories') ),
       sup('Crown Products', cat('Auto Accessories') ),
       sup('Logomark', cat('Auto Accessories') ),
      ] ],
     ['Auto Organizers',
      [match('name', %w(organize contain), 1)
      ] ],
     ['Auto Safety     ',
      [sup('Leeds', cat('Safety & Auto', 'Auto Safety') ),
       sup('Gemline', cat('Gifts', 'Safety/Auto') ),
       sup('Norwood', cat('AUTO', 'HIGHWAY') ),
      ] ],
     ['Ice Scraper',
      [match('name', 'ice scraper'),
       sup('Lanco', cat('Tools / Knives', 'Ice Scraper') ) ]],
    ]],
 ['Bags',
  [sup('Norwood',
       all(cat('BAG', 'COMPBAG'),
           match('name', %w(bag brief))) ),
   sup('High Caliber Line', cat('Bags') ),
   sup('Ash City',
       all(cat('Accessories'),
           match('name', %w(bag pack portfolio tote brief)))),
   sup('Prime Line',
       cat('Bags'),
       exclude(match(%w(name description), 'cooler'))),
   sup('Hit Promotional Products',
       cat('Bags, Totes & Koolers'),
       exclude(match('name', 'kool')) ),
   sup('Crown Products',
       cat('Bags'),
       cat('Bags, Bags') ),
   sup('Sweda', cat('Bags') )
  ],[
     ['Backpacks',
      [match('name', %w(Backpack Daypack Sports\ Pack)),
       match('description', 'backpack', 1),
       sup('Leeds', cat('Backpacks', 'Backpacks')),
       sup('Gemline',
           ['Under $15', '$15-$30', ' $30+', 'Sports', 'New', 'Clearance'].collect do |name|
             cat('Backpacks', name)
           end),
       sup('Prime Line', cat('Backpacks') ),
       sup('Lanco', cat('Bags / Containers', 'Backpacks')),
       sup('Norwood', cat('BAG', 'BACKPACK') ),
       sup('High Caliber Line',
           all(cat('Bags'),
               match('name', 'backpack'))),
       sup('Logomark', cat('Backpacks and Slings') ),
       sup('Sweda', cat('Bags', 'Backpacks') ),
       sup('The Magnet Group', cat('Bag Factory', 'Backpacks') )
      ],[
         ['Cooler Backpacks',
          [match('name', 'cooler', 1)]],
         ['Computer Backpacks',
          [match('name', ['compu', 'laptop'], 1),
           sup('Leeds', cat('Backpacks', 'Compu-Backpacks') ),
           sup('Gemline', cat('Backpacks', 'Computer') ),
          ]],
         ['Checkpoint Friendly Backpacks',
          [sup('Gemline', cat('Backpacks', 'Checkpoint-friendly') )
          ]],
         ['Drawstring & Cinch Backpacks',
          [match('name', %w(drawstring cinch), 1),
           match('description', 'drawstring closure', 1),
           sup('Leeds', cat('Backpacks', 'Cinches')),
           sup('Gemline',
               cat('Backpacks', 'Cinchpacks'),
               all(cat('Backpacks', 'Sports Backpacks'),
                   match('name', 'cinch') ) ),
           sup('Bullet Line', cat('Bags', 'Drawstrings & Backpacks')) ]],
         ['Hydration Backpacks',
          [match('name', 'hydrat', 1)]],
         ['Kid Friendly Backpacks',
          [sup('Gemline', cat('Kid-friendly', 'Backpacks') ) ] ],
         ['Recycled Backpacks',
          [sup('Leeds', cat('EcoSmart', 'Backpacks') ) ]],
         ['Sling Backpacks',
          [match('description', 'sling', 1),
           sup('Leeds', cat('Backpacks', 'Slings')),
           sup('Gemline',
               cat('Backpacks', 'Monopacks'),
               all(cat('Backpacks', 'Sports'),
                   match('name', 'sling') ) ) ]],
         ['Tote Backpacks',
          [match('name', 'tote', 1)]],
         ['Wheeled Backpacks',
          [match('name', %w(wheel roll), 1),
           sup('Gemline', cat('Backpacks', 'Wheeled') )]],
         ['Womens Backpacks',
          [sup('Gemline', cat('Women`s', 'Backpacks')),
           sup('High Caliber Line',
               all(cat("Women´s Gifts"),
                   match('name', 'bag') ) ) ] ],
        ] ],
     ['Portfolios & Business Bags',
      [match('name', ['portfolio', /attache(?:\s|$)/, 'briefcase', 'brief case']),
       match('name', 'brief', 1),
       sup('Leeds', cat('Business Cases', 'Business Cases') ),
       sup('Gemline',
           ['Clearance', 'New', 'Portfolios Under $10'].collect do |name|
             cat('Portfolios', name)
           end),
       sup('Lanco', cat('Bags / Containers', 'Business Cases')),
       sup('Prime Line',
           all(cat('Computer Bags / Portfolios'),
               match('name', 'brief') ) ),
       sup('Norwood', cat('BAG', 'BRIEFCASES') ),
       sup('Bullet Line',
           all(cat('Bags', 'Briefcases & Laptop Cases'),
               match('name', ['brief', 'messenger', 'document']) ) ),
       sup('Logomark', cat('Briefcases') ),
       sup('Sweda', cat('Bags', 'Messenger & Laptop') ),
       sup('The Magnet Group', cat('Bag Factory', 'Business Cases') ),
      ],[
         ['Computer Business Bags',
          [sup('Leeds',
               cat('Business Cases', 'Compu-Cases'),
               cat('Business Cases', 'Compu-Messenger Bags') ),
           sup('Gemline',
               cat('Portfolios', 'Computer Cases'),
               cat('Cirrus', 'Business Cases') ) ]],
         ['Messenger & Saddle Bags',
          [match('name', %w(messenger saddle), 2),
           match('name', 'messenger bag'),
           sup('Leeds',
               cat('Business Cases', 'Messenger Bags'),
               cat('Business Cases', 'Compu-Messenger Bags') ),
           sup('Gemline',
               cat('Portfolios', 'Saddlebags'),
               cat('Portfolios', 'Business'),
               cat('Portfolios', 'Messenger Bags') ),
           sup('Logomark', cat('Shoulder Bags') )
          ]],
         ['Leather Business Bags',
          [match('name', 'lthr', 1), # Why doesn't this work?
           match('material', 'leather', 1),
           sup('Gemline', cat('Portfolios', 'Leather Bags') ),
           sup('Logomark',
               all(cat('Leather Bags'),
                   match('name', 'brief') ) ),
          ]],
         ['Recycled Business Bags',
          [match(%w(name description), 'recycle', 1),
           sup('Leeds', cat('EcoSmart', 'Business Cases') ) ]],
         ['Wheeled Business Bags',
          [match('name', 'wheel', 1),
           sup('Leeds', cat('Business Cases', 'Wheeled Business Cases') ) ]],
         ['Kid Friendly Portfolios',
          [sup('Gemline', cat('Kid-friendly', 'Portfolios')) ]],
         ['Womens Portfolios',
          [sup('Gemline', cat('Women`s', 'Portfolios')) ]],
         ['Vertical Bags',
          [sup('Gemline', cat('Portfolios', 'Vertical Bags')) ]],
         ['Checkpoint Friendly Portfolios',
          [sup('Gemline', cat('Portfolios', 'Checkpoint-friendly')) ]],
        ] ],
     ['Duffel Bags',
      [match('name', ['duffel', 'duffle']),
       sup('Gemline',
           ['$15-$25', '$25+', 'Closeout Sport/Travel Bags', 'New Sport/Travel Bags', 'Under $15', 'Travel Bags'].collect do |name|
             cat('Sport & Travel', name)
           end),
       sup('Lanco', cat('Bags / Containers', 'Sport and Duffle Bags')),
       sup('Norwood', cat('BAG', 'DUFFELS')),
       sup('Bullet Line', cat('Bags', 'Duffels') ),
       sup('Logomark', cat('Duffel Bags') ),
       sup('Sweda', cat('Bags', 'Duffels') )
      ],[
         ['Executive Duffel Bags',
          [sup('Leeds', cat('Duffels', 'Executive') ) ]],
         ['Recycled Duffel Bags',
          [sup('Leeds', cat('EcoSmart', 'Duffels') ) ]],
         ['Sport Duffel Bags',
          [match('name', %w(athletic fitness), 2), # for Prime Line
           match('name', 'Sport Duffel', 1),
           sup('Leeds', cat('Duffels', 'Sport') ),
           sup('Gemline',
               cat('Sport & Travel', 'Sport Bags'),
               match('name', 'sport bag')),
           sup('Norwood', cat('BAG', 'SPORT') )
          ],[['Kid Friendly Sport Bags',
              [sup('Gemline',
                   cat('Kid-friendly', 'Sport & Travel') ) ] ],
            ]],
         ['Wheeled Duffel Bags',
          [match('name', 'wheeled'),
           sup('Leeds', cat('Duffels', 'Wheeled') ),
           sup('Gemline', cat('Sport & Travel', 'Wheeled') ) ]]
        ]],
     ['Golf Bags',
      [match('name', 'golf', 1),
       sup('Leeds',
           all(cat('Luggage & Golf', 'Golf'),
               match('name', %w(bag duffel)) ) ),
       sup('Norwood',
           all(match('name', %w(bag carrier)),
               cat('GOLF') ),
           match('name', ['stand bag', 'cart bag'])) ]],
     ['Luggage',
      [sup('Leeds', cat('Luggage & Golf', 'Luggage') ),
       sup('Norwood',
           cat('TRAVEL', 'LUGGAGE'),
           match('name', 'carry on') ),
       sup('Logomark', cat('Luggage') ),
      ]],
     ['Checkpoint Friendly Bags',
      [ ],
      [dup('Bags', 'Backpacks', 'Checkpoint Friendly Backpacks'),
       dup('Bags', 'Portfolios & Business Bags', 'Checkpoint Friendly Portfolios') ] ],
     ['Leather Bags',
      [match('material', 'leather', 1),
       sup('Logomark', cat('Leather Bags') )
      ]],
     ['Computer Bags',
      [match('name', ['computer case', 'computer bag', 'laptop bag', 'laptop case']),
       match('name', 'compu', 1),
       sup('Prime Line', match('name', ['computer sleeve', 'laptop sleeve']) ),
       sup('Logomark', cat('Computer Cases') ),
               
      ],[dup('Bags', 'Backpacks', 'Computer Backpacks'),
         ['Laptop Sleeves',
          [match('name', 'laptop sleeve'),
           sup('Prime Line', cat('Laptop/Tablet Sleeves'))
          ]],
        ] ],
     ['Wheeled Bags',
      [match('name', 'wheel', 1),
       sup('Gemline', cat('Sport & Travel', 'Wheeled Bags') )
      ],[dup('Bags', 'Backpacks', 'Wheeled Backpacks'),
         dup('Bags', 'Business Bags', 'Wheeled Business Bags'),
         dup('Bags', 'Duffel Bags', 'Wheeled Duffel Bags')
        ] ],
     ['Tote Bags',
      [match('name', 'tote'),
       sup('Leeds', cat('Totes', 'Totes')),
       sup('Gemline',
           ['New', 'Clearance', 'Totes 10+', 'Totes Under $10', 'Totes Under $5', 'Market Sets'].collect do |name|
             cat('Totes', name)
           end),
       sup('Lanco', cat('Bags / Containers', 'Tote Bags')),
       sup('Prime Line', cat('Totes')),
       sup('Norwood', cat('BAG', 'TOTE') ),
       sup('Bullet Line', cat('Bags', 'Totes') ),
       sup('Logomark', cat('Tote and Shoppers') ),
       sup('Sweda', cat('Bags', 'Totes') ),
       sup('The Magnet Group', cat('Bag Factory', 'Totes') )
      ],[
         ['Business & Meeting Totes',
          [match(%w(name description), %w(business meeting computer laptop), 1),
           exclude(match('description', 'business card')) ] ],
         ['Cotton Canvas Totes',
          [match(%w(name description material), %w(cotton canvas), 1),
           sup('Leeds', cat('Totes', 'Cotton') ),
           sup('Gemline',
               cat('Totes', 'Canvas Bags'),
               cat('Living Green', 'Organic'))]],
         ['Jute Totes',
          [match(%w(name description material), %w(jute), 1),
           sup('Prime Line',
               all(cat('Jute Bags'),
                   match('name', 'tote')))]],
         ['Non-woven Polypropylene Totes',
          [match('material', %w(poly non-woven non\ woven), 1),
           match(%w(name description), ['poly', 'pet plastic', 'non-woven'], 1),
           sup('Leeds', cat('Totes', 'Non-Woven') ),
           sup('Gemline', cat('Totes', 'Non-woven') ),
           sup('Prime Line', cat('Non-Woven') )]],
         ['Shopper Totes',
          [match(%w(name description), %w(shopper grocery market), 2),
           sup('Gemline', cat('Totes', 'Shoppers'))]],
         ['Cooler & Insulated Totes',
          [match(%w(name description), %w(cooler lunch six\ pack insulate), 2)]],
         ['Trade Show Totes',
          [match(%w(name description), %w(trade\ show tradeshow expo convention), 1),
           sup('Gemline', cat('Totes', 'Expo'))]],
         ['Kid Friendly Totes',
          [sup('Gemline', cat('Kid-friendly', 'Totes') ) ] ],
         ['Recycled & Organic Totes',
          [match(%w(name description), 'recycled', 1),
           sup('Leeds',
               cat('Totes', 'EcoSmart'),
               cat('EcoSmart', 'Totes') ) ]],
         ['Backpack Totes',
          [match(%w(name description), 'backpack', 1)],
          [
           ['Drawstring Totes',
            [match(%w(name description), 'drawstring', 2),
             match('name', %w(cinch sling), ['Bags', 'Backpacks', 'Drawstring Backpacks'])]],
          ] ],
         ['Womens Totes',
          [match('name', 'gloss', 1),
           sup('Gemline', cat('Women`s', 'Totes')) ]],
         ['Zippered Totes',
          [match(%w(name description), 'zipper', 1)]],
        ] ],
     ['Tool Bags',
      [match('name', ['tool', 'utility case'], 1),
       sup('Gemline',
           all(cat('Gifts', 'Home Improvement'),
               match('name', %w(bag case))))]],
     ['Wine Bags',
      [match(%w(name description), 'wine', 1),
       match('name', ['wine kit', 'wine tote', /wine.+holder/i])]],
     ['Womens Bags',
      [sup('Gemline', cat('Women`s', 'Sport & Travel')) ]],
     ['Waist Pack',
      [match('name', ['waist pack', 'fanny pack']) ] ],
     ['Pouches',
      [match('name', 'pouch'),
       sup('Lanco', cat('Bags / Containers', 'Small Pouches & Bags'))] ],
     ['Amenity Cases',
      [match('name', 'toiletr'),
       sup('Gemline', cat('Sport & Travel', 'Amenity Cases') ),
       sup('Bullet Line',
           all(cat('Travel, Health & Beauty', 'Travel Accessories'),
               match('name', ['amenity', 'travel']) ) ),
       sup('Norwood', cat('TRAVEL', 'UTILITY') )
      ]],
    ] ],

 ['Candles, Bath & Body',
  [
  ],[
     ['Bath & Body Gift Sets',
      [sup('Lanco', cat('Candles / Bath / Body', 'Bath & Body Gift Sets') ) ]],
     ['Candles',
      [match('name', 'candle'),
       sup('Lanco', cat('Candles / Bath / Body', 'Candles') ) ]],
     ['Bath & Body Kits',
      [match('name', 'spa kit'),
       sup('Lanco', cat('Candles / Bath / Body', 'Bath & Body Kits') ) ]],
     ['Massagers',
      [match('name', 'massager') ]],
     ['Bath & Body Lotions',
      [sup('Lanco', cat('Candles / Bath / Body', 'Bath & Body Lotions') ) ]],
    ] ],

 ['Collections',
  [sup('Gemline', duplicate(['Collections'], 'supplier_categories'))
  ],[
     ['Cleveland®',
      [sup('Norwood', cat('GOLF', 'CLEVE')) ]],
     ['Titleist®',
      [sup('Norwood', cat('GOLF', 'TITLEIST')) ]],
     ['Callaway®',
      [match('name', 'callaway'),
       sup('Norwood', cat('GOLF', 'CALLAWAY')),
       sup('Sweda', cat('BRANDS', 'Callaway Golf') )
      ]],
     ['Wilson®',
      [sup('Norwood', cat('GOLF', 'WILSON')) ]],
     ['Gusto!',
      [sup('Leeds', duplicate(['Gusto!'], 'supplier_categories'))]],
     ['Life in Motion', 
      [sup('Gemline', duplicate(['Life in Motion'], 'supplier_categories') ) ]] ,
     ['Contours',
      [sup('Gemline', duplicate(['Contour'], 'supplier_categories') ) ]] ,
     ['Cirrus',
      [sup('Gemline', duplicate(['Cirrus'], 'supplier_categories'))]],
     ['Elements',
      [sup('Gemline', duplicate(['Elements'], 'supplier_categories'))]],
     ['Equity',
      [sup('Gemline', duplicate(['Equity'], 'supplier_categories'))]],
     ['Nike®',
      [match('name', 'nike'),
       sup('Norwood', cat('GOLF', 'NIKE')) ] ],
     ['Built®',
      [sup('Prime Line', cat('BUILT')) ]]
    ] ],

 ['Computer Accessories',
  [match('name', 'Computer Accessory'),
   sup('Prime Line',
       cat('Technology'),
       cat('USBTechnology') ),
   sup('Norwood', cat('TECHNOLOGY', 'ELEC') ),
   sup('LogoIncluded', cat('Card Reader') ),
   sup('Logomark', cat('Computer Accessories') )
  ],[
     ['Apple Accessories',
      [match('name', /iP(o|a)d/),
       sup('LogoIncluded', cat('Mobile / Apple Accessories')),
      ]],
     ['CD Products',
      [match('name', ['CD case', 'DVD case']),
       sup('Lanco', cat('Office / Computer Essentials', 'CD Products') ),]],
     ['Computer Accessory Kits',
      [match('name', 'computer accessories')]],
     ['Computer Brush',
      [match('name', 'computer brush'),
       sup('Lanco', cat('Office / Computer Essentials', 'Computer Brush') ) ]],
     ['Cables & Cords',
      [match('name', %w(cable cord), 1),
       match('name', %w(phone\ cord)),
       match('name', /((usb)|(network)).+cable/i),
       sup('Lanco', cat('Office / Computer Essentials', 'Modem Cord') ) ]],
     ['Computer Mice',
      [match('name', 'mouse ', 1),
       match('name', /mouse($|\s)/),
       sup('Leeds', cat('Technology', 'Mice') ),
       sup('Norwood',
           all(match('name', ' mouse'),
               cat('TECHNOLOGY', 'OTHERTECH'), ) ),
       sup('LogoIncluded', cat('Mouse') ),
       sup('Sweda', cat('Computer', 'Mouse') )
      ]],
     ['Computer Keyboards / Keypads',
      [match('name', ['keyboard', 'keypad']),
      ]],
     ['Computer Mouse Pads',
      [match('name', ['mousepad', 'mouse pad']), 
       sup('Norwood',
           all(match('name', 'mousepad'),
               cat('OFFICE', 'TECHNOLOGY') ) ),
       sup('Bic Graphics',
           match('supplier_num', /^((MPC?\d)|(MPSH)|(MPFR))/) ),
      ] ],
     ['Screen Cleaners',
      [match('name', 'screen cleaner'),
       match('description', /screen.+?brush/i),
       sup('LogoIncluded', cat('Screen Cleaner') )] ],
     ['MP3 Players',
      [match('name', %w(mp3 mp4) + [/(^|\s)ipod(\s|$)/i]),
       sup('Leeds', cat('Memory', 'Music & Media') ),
       sup('Lanco', cat('Office / Computer Essentials', 'Mouse Pads') ),
       sup('Prime Line',
           all(cat('Mp3 / Radios'),
               match(%w(name description), %w(mp3 iPod)) ) ),
       sup('LogoIncluded', cat('MP3 Player / MP4 Player') )]],
     ['Web Cams',
      [match('name', 'web cam')] ],
     ['Web Keys',
      [sup('LogoIncluded', cat('Web Key') )] ],
     ['WiFi Finders',
      [sup('LogoIncluded', cat('WiFi Finder') )] ],
     ['Tablet Accessories',
      [
      ],[['iPad Accessories',
          [match('name', 'iPad')]],
         ['Tablet Cases, Stands & Sleeves',
          [all(match('name', %w(case stand sleeve holder)),
               match(%w(name description), %w(tablet iPad)))
          ]],
         ['Screen Stylus',
          [all(match('name', 'stylus'),
               match('description', ['screen', 'ipad', 'iphone']))
          ]],
        ] ],
     ['Camera & Phone Holders',
      [all(match('name', 'case'),
           match('name', %w(ipod nano camera))),
       match('name', ['device holder', /phone.+?case/i])]],
     ['USB Hubs',
      [match('name', 'hub', 1),
       match('name', /usb.+hub/i),
       sup('Leeds', cat('Technology', 'USB Hubs') ),
       sup('Norwood',
           all(match('name', ' hub'),
               cat('OFFICE', 'TECHNOLOGY') ) ),
       sup('LogoIncluded', cat('USB Hub')),
       sup('Sweda', cat('Computer', 'Hubs') )
      ]],
     ['USB Accessories',
      [all(match('name', 'usb'),
           match('name', ['charger']) ),
       all(match('name', ['sd card', 'card reader']),
           match(%w(name description), 'USB')),
       sup('LogoIncluded',
           cat('USB Accessories'),
           cat('SD Cards  Readers'),
           all(cat('Tech Accessories'),
               match(%w(name description), 'USB'))) ]],
     ['USB Flash Drives',
      [match('name', %w(flash memory mb gb), 1),
       sup('Leeds', cat('Memory', 'Flash Drives') ),
       sup('Gemline', cat('Gifts', 'USB Drives') ),
       sup('Prime Line', cat('USB Memory') ),
       sup('Logomark', cat('USB Drives') ),
       sup('LogoIncluded', cat('USB Drive') )
      ],[
         ['Pen USB Flash Drives',
          [match('name', 'pen', 1),
           sup('Leeds', cat('Memory', 'Memory Pens') ),
           sup('LogoIncluded', cat('Pen Drive') )]],
         ['Recycled Flash Drives',
          [match(%w(name description), 'recycle', 1),
           sup('Leeds', cat('EcoSmart', 'Memory') ) ]],
        ] +
      ['128M', '256M', '512M', '1G', '2G', '4G', '8G', '16G', '32G'].collect do |name|
        ["#{name}B Flash Drives",
         [match('name', name, 1),
          sup('LogoIncluded',
              match('memory', name) ) ]]
      end
     ],
     ['Digital Photo Frames',
      [sup('Leeds', cat('Technology', 'Digital Photos') ),
       sup('Prime Line', cat('Digital Frames SALE')),
       sup('Norwood',
           all(match('name', 'digital photo'),
               cat('OFFICE', 'TECHNOLOGY') ) ),
       sup('LogoIncluded', cat('Digital Photo Frame') ),
       sup('Sweda', cat('Computer', 'Digital Picture Frames') )
      ]],
    ] ],

 ['Desktop Accessories',
  [sup('Leeds',
       cat('Desktop', 'Accessories & Sets'),
       cat('Desktop', 'Electronics & Clocks'),
       cat('Desktop', 'Essentials'),
       cat('Gusto', 'Work') ),
   sup('Prime Line',
       cat('Office'),
       cat('Desk Helpers')),
   sup('Norwood',
       cat('GOLF', 'DESKFUN'),
       cat('OFFICE', 'DESKACC')),
   sup('Bullet Line', cat('Desktop', 'Desktop Accessories') ),
   sup('Hit Promotional Products',cat('Desk, Office & Electronics') ),
   sup('Logomark', cat('Desk and Office Accessories') )
  ],[
     ['Calculators',
      [match('name', 'calculator'),
       sup('High Caliber Line', cat('Calculators') ),
       sup('Prime Line', cat('Calculators') ),
       sup('Lanco', cat('Calc / Clocks / Radios', 'Calculators') ),
       sup('Hit Promotional Products',
           match('name', 'calc') ),
       sup('Logomark', cat('Calculators') ),
       sup('Sweda',
           cat('Calculators', 'Desktop'),
           cat('Calculators', 'Handheld') ),
       ] ],
     ['Clocks',
      [match('name', 'clock'),
       sup('Prime Line', cat('Clocks') ),
       sup('Lanco', cat('Calc / Clocks / Radios', 'Clocks') ),
       sup('High Caliber Line', cat('Clocks') ),
       sup('Norwood', cat('AWARD', 'CLOCKS') ),
       sup('Logomark',
           cat('Desk Clocks'),
           cat('Clocks with Photo Frames'),
           cat('Watch Clocks') ),
       sup('Sweda',
           cat('Clocks', 'Desktop'),
           cat('Clocks', 'Wall Clocks'),
           cat('Clocks', 'Travel Alarm') ),
       sup('The Magnet Group',
           cat('Clocks', 'Elegant Clocks'),
           cat('Clocks', 'Clock/Frame Combos'),
           cat('Innovations', 'Clocks') ),
       sup('The Magnet Group', cat('Clocks') )
      ],[
         ['Acrylic Clocks',
          [match(%w(name description material), 'acrylic', 1),
           sup('The Magnet Group', cat('Clocks', 'Acrylic Clocks') )
          ] ],
         ['Brass Clocks',
          [match(%w(name description material), 'brass', 1),
           sup('The Magnet Group', cat('Clocks', 'Brass Clocks') )
          ] ],
         ['Gimble Clocks',
          [match(%w(name description), %w(gimble twist), 1),
           sup('The Magnet Group', cat('Clocks', 'Gimble Clocks') )
          ] ],
         ['Glass Clocks',
          [match(%w(name description material), 'glass', 1),
           sup('The Magnet Group', cat('Clocks', 'Glass Clocks') )
          ] ],
         ['Marble Clocks',
          [match(%w(name description material), 'marble', 1),
           sup('The Magnet Group', cat('Clocks', 'Marble Clocks') )
          ] ],
         ['Wood Clocks',
          [match(%w(name description material), 'wood', 1),
           sup('The Magnet Group', cat('Clocks', 'Wood Clocks') )
          ] ],
         ['Silver Clocks',
          [match(%w(name description material), 'silver', 1),
           sup('The Magnet Group',
               all(cat('Clocks', 'Silver and Unique Clocks'),
                   match(%w(name description material), 'silver') ) ),
          ] ],
         ['Unique Clocks',
          [sup('The Magnet Group',
               cat('Clocks', 'Silver and Unique Clocks'),
               exclude(match(%w(name description material), 'silver') ) ),
          ] ],
         ['Travel Clocks',
          [match(%w(name description), 'travel', 1),
           sup('Leeds',
               all(cat('Travel Gifts', 'Clocks & Wallets'),
                   match('name', 'clock')) ),
           sup('Logomark', cat('Travel Clocks') ),
          ] ] ] ],
     ['Pen Stands and Holders',
      [sup('Logomark', cat('Pen Stands and Holders') ) ] ],
     ['Radios',
      [match('name', 'radio'),
       sup('Prime Line',                
           match(%w(name description), %w(radio am/fm) ) ),
       sup('Lanco', cat('Calc / Clocks / Radios', 'Radios') ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Radios') ),
       sup('Logomark', cat('Radios') )
      ]],
     ['Weather Station',
      [match('name', 'weather station'),
       sup('Logomark', cat('Weather Stations') )]],
     dup('Computer Accessories', 'Digital Photo Frames'),
     ['Picture Frames',
      [match('name', ['photo frame', 'picture frame']),
       match('name', 'frame', 1),
       sup('Leeds',
           all(cat('Desktop Gifts', 'Desktop Accessories'),
               match('name', %w(photo frame)) ) ), 
       sup('Norwood', cat('OFFICE', 'PHOTO') ),
       sup('High Caliber Line', cat('Picture Frames') ),
       sup('Prime Line',
           match('name', 'frame')),
       sup('Logomark',
           cat('Photo Frames'),
           cat('Clocks with Photo Frames') ),
       sup('Sweda',
           cat('Photo Frames'),
           cat('Picture Frames') ),
       sup('The Magnet Group',
           cat('Clocks', 'Clock/Frame Combos'),
           cat('Innovations', 'Frames'),
           cat('Innovations', 'Acrylic Frames'),
           cat('Innovations', 'Metal Displays and Frames')),
      ]],
     ['Photo Albums',
      [match('name', %w(photo\ album brag\ book)) ] ],
     ['Desktop Novelties',
      [sup('Leeds',
           cat('Desktop Gifts', 'Desktop Novelty'),
           cat('Gusto', 'Connect')) ]],
     ['Ecologically Friendly Desktop',
      [sup('Leeds', cat('EcoSmart', 'Desktop') ) ] ],
     ['Recycled Desktop Accessories',
      [sup('Leeds',
           all(cat('EcoSmart', 'Desktop'),
               match('name', 'recycled') ) ) ]],
     ['Desktop Technology',
      [sup('Leeds', cat('Technology', 'Desktop') ) ]],
     ['Letter Openers',
      [match('name', ['letter opener', 'slitter']),
       match('name', 'opener', 1),
       sup('Lanco', cat('Office / Computer Essentials', 'Letter Opener') ),
       sup('Logomark', cat('Letter Openers') )
      ]],
     ['Laser Pointers',
      [match('name', 'laser', 1),
       match('name', 'laser pointer'),
       sup('High Caliber Line', cat('Laser Pointers') ),
       sup('Bullet Line', cat('Lighting', 'Laser Pointers') ),
       sup('LogoIncluded', cat('Wireless Presenter') ),
       sup('Logomark', cat('Laser Pointers') )]],
     dup('Computer Accessories', 'Computer Mice'),
     ['Bookmarks',
      [match('name', ['bookmark', 'book mark']) ] ],
     ['Speakers',
      [match('name', 'speaker'),
       sup('Leeds',
           all(cat('Technology', 'Music & Media'),
               match(%w(name description), 'speaker') ) )] ],
     ['Headphones & Earbuds',
      [match('name', %w(headphones head\ phones earbuds earphones ear\ plugs ear\ phones)),
       sup('Leeds',
           all(cat('Technology', 'Music & Media'),
               match('name', %w(headph ear)) ) ),
       sup('LogoIncluded', cat('Bluetooth Headset') ),
       sup('Bullet Line', cat('Technology', 'Media') )
      ] ],
     ['Desktop Organizers',
      [match('name', ['desk caddy', 'desk organizer', 'pen caddy'])]],
     ['Card Holders',
      [match('name', 'card holder', 1),
       match(%w(name description), 'business card holder'),
       sup('Prime Line',
           match('name', 'card case') ),
       sup('High Caliber Line',
           all(cat('Office'),
               match('name', 'card holder') ) ),
       sup('Bullet Line',
           match('name', 'card case') ),
       sup('Logomark',
           cat('Business Card Holders') ),
       sup('The Magnet Group',
           cat('Innovations', 'Pocket Items'),
           exclude(match(%w(name description), ['money clip', 'cloth']) ) ),
      ] ],
     ['Note Holders',
      [match('name', ['note holder', 'memo holder', 'memo stack', 'Post-it holder','note dispenser', 'sticky note', 'sticky flag']), #, 1),
       sup('Lanco',
           cat('Office / Computer Essentials', 'Memo Holder'),
           cat('Office / Computer Essentials', 'Memo Dispenser'),
           cat('Journals / Portfolios', 'Sticky Holder')),
       sup('Prime Line',
           all(cat('Desk Helpers'),
               match('name', 'note') ) ),
       sup('High Caliber Line',
           all(cat('Office'),
               match('name', ' clip') ),
           match('name', 'note holder') ),
       sup('Norwood', cat('OFFICE', 'NOTES') ),
       sup('Bullet Line', cat('Sticky Notes', 'Office Accessories') ),
       sup('Logomark', cat('Memo Holders') ),
       sup('The Magnet Group',
           all(cat('Innovations', 'Paper Clip, Tape & Note Dispense'),
               match('name', 'note dispenser') ) )
      ],[
         ['Notenest & Note Clips',
          [match('name', 'clip', 1),
           match('name', ['notenest', 'memo clip']),
           sup('Prime Line',
               match('name', 'notenest') ),
           sup('Hit Promotional Products',
               match('name', 'clip', 2) ),
           sup('The Magnet Group', cat('Innovations', 'Power Clips') )
          ] ],
         ['Memo Books',
          [match('name', ['memo book', 'message pad holder'], 2)]],
         ['Sticky Note Books',
          [match('name', ['sticky memo', 'sticky flags', 'sticky note'], 1),
           match('name', /stick.+((note)|(flag)).+book/i),
           sup('Prime Line', cat('Sticky Books')),
           sup('Bullet Line', cat('Sticky Notes', 'Booklets & Notebooks') ),
           sup('Bic Graphics',
               match('supplier_num', /^((MFP?B)|(PFBD)|(PF[CN]))$/) ) ] ]
        ]],
     ['Notepads',
      [],
      [['Adhesive Cubes',
        [sup('Bic Graphics',
             match('supplier_num', /^SNC\d/)) ]],
       ['Adhesive Notepads',
        [sup('Bic Graphics',
             match('supplier_num', /^((V?P\d)|(SND\d))|(B4A6A150)/)) ]],
       ['Non-Adhesive Notepads',
        [sup('Bic Graphics',
             match('supplier_num', /^NS\d/)) ]],
       ['Non-Adhesive Cubes',
        [sup('Bic Graphics',
             match('supplier_num', /^((NC2)|(V?NC3)|(VNC4[AB]$))/)) ]],

      ]],
     ['Paper Clips & Fasteners',
      [#match('name', 'paper clip'),
       sup('Norwood',
           cat('OFFICE', 'CLIP') ),
       sup('The Magnet Group',
           all(cat('Innovations', 'Paper Clip, Tape & Note Dispense'),
               match('name', 'paper clip') ) )
      ]],
     ['Paper Clip Holders',
      [match('name', ['clip dispenser', /paper.+clip.+((dispens)|(holder))/i]),
       match('name', ['cache', 'clip holder', 'clip keeper'], 1),
       match(%w(name description), 'paper clip', 1),
       sup('Lanco', cat('Office / Computer Essentials', 'Paper Clip Holder') ),
       sup('Prime Line',
           match('name', 'cache') )]],
     ['Paperweights',
      [match('name', 'paperweight'),
       sup('The Magnet Group', cat('Crystal', 'Paperweights and Crystal Boxes') )
      ]],
     ['Piggy Bank',
      [match(%w(name description), /(pig(gy)?)|(coin) bank/i),
       all(match('name', 'bank'), match(%w(name description), 'coin')),
       exclude(match('name', 'stress') ),
      ] ],
     ['Push Pins',
      [match('name', 'push pin')] ],
     ['Rulers',
      [match('name', 'ruler'),
       sup('Lanco', cat('Office / Computer Essentials', 'Ruler') ) ]],
     ['Scissors',
      [match('name', 'scissor'),
       sup('Lanco', cat('Office / Computer Essentials', 'Scissors') ) ]],
     ['Staplers',
      [match('name', 'stapler'),
       sup('Lanco', cat('Office / Computer Essentials', 'Stapler') ),
       sup('Lanco', cat('Writing Instruments', 'Stapler') ),
       sup('The Magnet Group', cat('Innovations', 'Staplers') )
      ]],
     ['Staple Removers',
      [match('name', 'staple remover'),
       sup('Lanco', cat('Writing Instruments', 'Staple Remover') ) ]],
     ['Tape Dispensers',
      [match('name', 'tape dispenser'),
       sup('Lanco', cat('Office / Computer Essentials', 'Tape Dispenser') ),
       sup('High Caliber Line',
           all(cat('Office'),
               match('name', 'tape') ) )]],
     ['Magnets',
      [sup('Norwood', cat('OFFICE', 'MAGNET') ),
       sup('The Magnet Group', cat('Innovations', 'Dots and Springs') ),
       sup('The Magnet Group', cat('Magnets') ) ## TEMPORARY
      ],
      [['Business Card Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG[EJ]?BC/) ),
         sup('The Magnet Group',
             cat('Magnets', 'Business Card Magnets'),
             cat('Magnets', 'Business Card Magnets - Unique') )
        ]],
       ['Stock Shape Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGSS/) ) ]],
       ['Custom Shape Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG((CS)|(SE))/) ) ]],
       ['Dry Erase Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG[DS]E/) ) ]],
       ['Picture Frame Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGSPF/) ),
         sup('The Magnet Group', cat('Magnets', 'Picture Frames') )
        ]],
       ['Calendar & Schedule Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MG((CL)|(SCH))/) ),
         sup('The Magnet Group',
             cat('Magnets', 'Calendars'),
             cat('Magnets', 'Schedule Magnets') )
        ]], 
       ['Mood Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^(MG((FM)|(M[AM])))$/) ) ]], 
       ['Car Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGCAR/) ),
         sup('The Magnet Group', cat('Magnets', 'Car Signs') )
        ]], 
       ['Paper Magnets',
        [sup('Bic Graphics',
             match('supplier_num', /^MGECO/) ) ]], 
      ]],
     ['Snow Globe',
      [match(%w(name description), ['snow globe', 'glitter globe']) ] ],
     ['Book Lights',
      [match('name', ['book light', 'book-light']),
       sup('Bullet Line', cat('Lighting', 'Book Lights') ) ] ],
     ['Pencil Sharpeners',
      [match('name', 'pencil sharpener')] ],
    ] ], 

 ['Coolers',
  [match('name', ['cooler', 'kooler']),
   sup('Gemline',
       ['Closeout Coolers', 'Coolers 12+', 'New', 'Under $12'].collect do |name|
         cat('Coolers', name)
       end),
   sup('Lanco', cat('Bags / Containers', 'Lunch Bag & Coolers')),
   sup('Prime Line',
       cat('Coolers - Ice'),
       all(cat('Bags'),
           match(%w(name description), 'cooler'))),
   sup('Norwood', cat('BAG', 'COOLERS') ),
   sup('High Caliber Line',
       all(cat('Bags'),
           match('name', 'cooler'))),
   sup('Bullet Line', cat('Coolers', 'Rolling & Chair Coolers') ), 
   sup('Hit Promotional Products',
       all(cat('Bags, Totes & Koolers'),
           match('name', 'kool') ) ),
   sup('Crown Products', cat('Coolers') ),
   sup('Logomark', cat('Coolers') ),
   sup('Sweda', cat('Bags', 'Coolers') ),
   sup('The Magnet Group', cat('Bag Factory', 'Coolers') )
  ],[
     ['Beverage Holders',
      [sup('Leeds', cat('Coolers', 'Beverage Holders') ) ]],
     ['Can Coolers',
      [match('name', 'can', 1)] ],
     ['Chair Coolers',
      [match('name', 'chair', 1) ] ],
     ['Event Coolers',
      [sup('Leeds', cat('Coolers', 'Event Coolers') ),
       sup('Gemline', cat('Coolers', 'Event') ) ]],
     ['Drink Coolers',
      [sup('Norwood', cat('OUTDOOR', 'HSCOOLERS') ) ] ],
     ['Food Storage Coolers',
      [sup('Leeds', cat('Coolers', 'Food Storage') ) ]],
     ['Kid Friendly Coolers',
      [sup('Gemline', cat('Kid-friendly', 'Coolers') ) ] ],
     ['Lunch Coolers',
      [match('name', 'lunch', 1),
       match('name', ['lunch kit', 'lunch bag']),
       sup('Leeds', cat('Coolers', 'Lunch Coolers') ),
       sup('Gemline', cat('Coolers', 'Lunch Bags') ),
       sup('Bullet Line', cat('Coolers', 'Lunch Coolers') ),
       sup('Sweda', cat('Bags', 'Lunch Bags') )
      ] ],
     ['Recycled Coolers',
      [sup('Leeds', cat('EcoSmart', 'Food Storage') ) ]],
     ['Wheeled Coolers',
      [match('name', %w(wheel rolling), 1),
       sup('Gemline', cat('Coolers', 'Wheeled') ),
       sup('Logomark', cat('Rolling Bags') )
      ]],
     ['Refrigerators',
      [sup('Logomark', cat('Refrigerators') ) ] ],
     ['Wine Coolers',
      [duplicate(['Bags', 'Wine Bags']),
       match(%w(name description), 'wine', 1)]]
    ] ],
 ['Drinkware',
  [#match('name', %w(coffe))
   sup('Prime Line', cat('Drinkware') ),
   sup('Norwood', cat('DRINK', 'BOTTLE') ),
   sup('Leeds', cat('Drinkware', 'Gift Sets') ),
   sup('High Caliber Line', cat('Drinkware') ),
   sup('Lanco', cat('Drinkware', 'Cups') ),
   sup('Hit Promotional Products', cat('Plastic & Metal Drinkware') ),
   sup('Crown Products', cat('Drinkware') ),
   sup('Logomark',
       cat('Water Bottles and Flasks'),
       cat('Executive Drinkware') ),
   sup('Sweda',
       cat('Drinkware', 'Water Bottles'),
       cat('Drinkware', 'Water Bottles (Plastic)') )
  ],[
     ['Aluminum Bottles',
      [match(%w(name description material), 'aluminum', 1),
       sup('Leeds',
           cat('Drinkware', 'Aluminum Bottles'),
           cat('Drinkware', 'Aluminum Sport Bottles')),
       sup('Lanco',
           cat('Drinkware', 'Metal Bottles') ) ]],
     ['Stainless Bottles',
      [sup('Leeds', cat('Drinkware', 'Stainless Sport Bottles')),
       sup('Sweda', cat('Drinkware', 'Vacuum Bottles') )
      ]],
     ['Can & Bottle Holders',
      [match(%w(name description), ['can holder', 'bottle holder', 'bottle insulator']),
       match('name', 'holder', 1),
       all(match('name', 'insulator'),
           match('description', 'drink') ),
       sup('Lanco', cat('Drinkware', 'Can & Bottle Holder') ),
       sup('Norwood', cat('DRINK', 'KOOZIE') ),
       sup('High Caliber Line',
           all(cat('Drinkware', 'Accessories'),
               match('name', 'holder') ) ),
       sup('Hit Promotional Products',
           all(cat('Leisure'),
               match('name', 'Kan') ) ),
       sup('Logomark', cat('Bottle Holders') )
      ] ],
     ['Coasters', 
      [match('name', 'coaster'),
       sup('Lanco', cat('Drinkware', 'Coasters') ),
       sup('Norwood',
           cat('HOUSEWARES', 'COASTERS'),
           cat('AWARD', 'COASTERS') ),
       sup('Hit Promotional Products',
           exclude(match('name', 'mug') ) ),
       sup('Logomark', cat('Coasters') )]],
     ['Jigger',
      [match('name', 'jigger')]],
     ['Ceramic',
      [match('name', 'ceramic', 1),
       sup('Leeds', cat('Drinkware', 'Ceramic') ),
       sup('Bullet Line', cat('Drinkware', 'Ceramics') ),
       sup('Hit Promotional Products', cat('Ceramics') ),
      ]],
     ['Drinkware Sets',
      [sup('Leeds', cat('Drinkware', 'Drinkware Sets') ),
       sup('Norwood', cat('DRINK', 'DRINKGIFT') )
      ]],
     ['Insulated Bottles',
      [sup('Leeds', cat('Drinkware', 'Insulated Bottles') ) ]],
     ['Mugs & Tumblers',
      [match('name', %w(tumbler mug), 1),
       match('name', 'flask'),
       sup('Leeds', cat('Drinkware', 'Mugs & Tumblers') ),
       sup('Lanco', cat('Drinkware', 'Travel Mugs & Tumblers') ),
       sup('Norwood', cat('DRINK', 'METAL') ),
       sup('High Caliber Line',
           match('name', 'Mug') ),
       sup('Bullet Line', cat('Drinkware', 'Mugs & Tumblers') ),
       sup('Logomark',
           cat('Mugs'),
           cat('Tumblers') ),
       sup('Sweda', cat('Drinkware', 'Travel Mugs') )
      ],[
         ['Desk Mugs',
          [sup('Leeds', cat('Drinkware', 'Desk Mugs') )]],
         ['Ceramic Coffee Mugs',
          [match('name', 'coffee', 1),
           sup('Lanco', cat('Drinkware', 'Mugs') ),
           sup('Norwood', cat('DRINK', 'CERAMIC') )]],
        ]],
     ['Recycled Drinkware',
      [sup('Leeds', cat('EcoSmart', 'Drinkware') ) ]],
     ['Sport Bottles',
      [match('name', %w(bottle chill poly polly sports), 1),
       match('description', ['polyclear', 'sports bottle', 'squeeze bottle'], 1),
       sup('Leeds', cat('Drinkware', 'Plastic Sport Bottles') ),
       sup('Lanco',
           cat('Drinkware', 'Polycarbonate Bottles'),
           cat('Drinkware', 'Sports Bottles')),
       sup('Norwood',
           all(cat('DRINK', 'BOTTLE'),
               match('description', 'bottle') ) ),
       sup('Bullet Line', cat('Drinkware', 'Sports Bottles') ) ]],
     ['Wine Accessories',
      [match('name', 'wine'),
       sup('Logomark', cat('Wine Accessories') ) ]],
     ['Glassware',
      [sup('Norwood', cat('DRINK', 'GLASS') ),
       sup('Leeds', cat('Drinkware', 'Glassware') )] ],
     ['Specialty Drinkware',
      [sup('Bullet Line', cat('Drinkware', 'Specialty Drinkware'))
      ]],
    ] ],
 ['Food Gifts',
  [
  ],[
     ['Lollipop',
      [sup('The Magnet Group', cat('Innovations', 'Make It Pop!') ) ] ],
     ['Candy',
      [match('name', %w(jelly\ bean skittles))] ],
     ['Gourmet Food Gifts',
      [sup('Lanco', cat('Food Gifts', 'Gourmet Food Gifts') ) ]],
     ['Chocolate Foil Wrapped Pieces',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Foil Wrapped Pieces') ) ]],
     ['Chocolate Truffles',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Truffles') ) ]],
     ['Boxes with Gourmet Fills',
      [sup('Lanco', cat('Food Gifts', 'Boxes with Gourmet Fills') ) ]],
     ['Mints',
      [match('name', 'mint'),
       exclude(match('name', 'balm') ),
       sup('Lanco', cat('Food Gifts', 'Mints') ),
      sup('High Caliber Line',
          cat('Mints') )]],
     ['Coffee, Hot Chocolate, Ice Tea',
      [sup('Lanco', cat('Food Gifts', 'Coffee, Hot Chocolate, Ice Tea') ) ]],
     ['Candy Dispenser',
      [sup('Lanco', cat('Food Gifts', 'Candy Dispenser') ) ]],
     ['Novelty Chocolate',
      [sup('Lanco', cat('Food Gifts', 'Novelty Chocolate') ) ]],
     ['Chocolate Squares in Gift Sets',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Squares in Gift Sets') ) ]],
     ['Bags with Gourmet Fills',
      [sup('Lanco', cat('Food Gifts', 'Bags with Gourmet Fills') ) ]],
     ['Chocolate Bars',
      [sup('Lanco', cat('Food Gifts', 'Chocolate Bars') ) ]],
     ['Custom Molded Chocolate',
      [sup('Lanco', cat('Food Gifts', 'Custom Molded Chocolate') ) ]],
     ['Filled Glass Apothecary Jar',
      [sup('Lanco', cat('Food Gifts', 'Filled Glass Apothecary Jar') ) ]],
     ['Gum',
      [sup('Lanco', cat('Food Gifts', 'Gum') ) ]],
     ['Bottled Water',
      [match('name', 'bottled water'),
       sup('Lanco', cat('Food Gifts', 'Bottled Water') ) ]],
     ['Tea Bags',
      [match('name', 'tea bag'),
       sup('Lanco', cat('Food Gifts', 'Tea Bags') ) ] ],
     ['Elopes',
      [match('name', 'elopes'),
       sup('Lanco', cat('Food Gifts', 'Elopes') ) ] ],
    ] ],
 ['Games & Toys',
  [sup('Leeds',
       cat('Recreation', 'Family & Travel Games'),
       cat('Gusto', 'Play'),
       cat('Games', 'Desktop'),
       cat('Games', 'Home')),
   sup('High Caliber Line', cat('Toys & Games')),
   sup('Prime Line', cat('Toys Executive') ),
   sup('Norwood',
       match('name', 'hockey'),
       cat('GOLF', 'FUN'),
       cat('GOLF', 'GAMES'),
       cat('FUN', 'GAMES') ),
   sup('Lanco',
       cat('Toys & Games', 'Toys'),
       cat('Tradeshow', 'Toys') ),
   sup('Logomark', cat('Executive Games') )
  ],[
     ['Electronic Games',
      [match('name', 'electr', 1),
       match('description', ['electr', 'batteries', 'LCD'], 1)]],
     ['Outdoor Games',
      [match('name', ['ball'], 1),
       match('name', ['flying disc', 'flyer', 'kite', 'football', 'rocket', 'boomerang', 'basketball', 'soccer']),
       exclude(match('name', %w(stress pen scripto))),
       exclude(sup('LogoIncluded', always)),
       sup('High Caliber Line',
           match('name', ['super ball', 'flying star', 'paddle ball']) ),
       sup('Gemline', cat('Gifts', 'Outdoor Fun') ),
       sup('Leeds', cat('Games', 'Outdoor') ),
       sup('Lanco', cat('Toys & Games', 'Hacki Balls') ),
       sup('Hit Promotional Products',
           all(cat('Leisure'),
               match('name', %w(ball disk disc rocket rope) ) ) ), ]],
     ['Mind Games',
      [match('name', %w(suduko sudoku brain perplex mind))
      ],[
         ['Puzzles',
          [match('name', 'puzzle'),
           sup('Prime Line',
               all(match('name','Magic'),
                   match('name', '&reg;'))) ]],
         ['Rubiks Cubes',
          [match(%w(name description), 'rubik'),
           match('name', 'rubi', 1),
           sup('Prime Line',
                    cat("Rubik's&reg; Cubes") ) ] ],
        ]],
     ['Decision Makers',
      [sup('Logomark', cat('Decision Makers') ) ] ],
     ['Magic',
      [sup('High Caliber Line', cat('Magic') ) ]],
     ['Travel Games',
      [sup('Leeds', cat('Games', 'Travel') ) ]],
     ['Stress Reliever',
      [match('name', 'stress', 1),
       match('name', 'stress reliever'),
       sup('Leeds', cat('Gusto', 'Live') ),
       sup('Prime Line', cat('Stress Relievers') ),
       sup('Lanco',
           cat('Toys & Games', 'Stress Balls & Shapes'),
           cat('Tradeshow', 'Stress Balls & Shapes')),
       sup('Norwood', cat('HEALTH', 'STRESS') ),
       sup('Bullet Line', cat('Stress Relievers', 'Stress Relievers') ),
       sup('Hit Promotional Products',
           all(cat('Stress Relievers & Unique Specia'),
               match('name', 'stress') ) ),
       exclude(match('name', %w(pen scripto))),
      ] ],
     ['Dartboards',
      [match('name', 'dartboard') ]],
     ['Poker Sets',
      [match('name', 'poker') ]],
     ["Yo-Yo's",
      [match(%w(name description), ['Yo-Yo', 'Yo Yo', 'YoYo']),
       sup('Lanco', cat('Toys & Games', 'Yo-Yo\'s') )]],
    ] ],
 # Bad category
 ['Travel',
  [sup('Leeds', cat('Gusto', 'Voyage') ),
   sup('Gemline', cat('Gifts', 'Travel') ),
   sup('High Caliber Line', cat('Travel') ),
   sup('Crown Products', cat('Travel') )
  ],[
     ['Luggage Tags',
      [match('name', 'luggage'),
       sup('Leeds', cat('Travel Gifts', 'Luggage Tags') ),
       sup('Lanco', cat('Travel / Personal Care', 'Luggage Tags') ),
       sup('Logomark', cat('Luggage Tags') ),
       sup('The Magnet Group', cat('Innovations', 'Luggage Tags') )
      ] ],
     ['Travel Accessories',
      [sup('Leeds',
           cat('Travel Gifts', 'Accessories'),
           exclude(match('name', 'charge'))),
       sup('Bullet Line', cat('Travel, Health & Beauty', 'Travel Accessories') ),
       sup('Logomark', cat('Travel Accessories') )
      ] ],
     ['Phone Chargers',
      [match('name', ['charger', 'charging']),
       sup('Leeds',
           all(cat('Travel Gifts', 'Accessories'),
               match('name', 'charge'))),
       sup('LogoIncluded', cat('Solar Charger') )] ],
     ['Travel Clocks', duplicate(['Desktop Accessories', 'Clocks', 'Travel Clocks']) ],
     ['Travel Games', duplicate(['Games & Toys', 'Travel Games']) ],
     ['Travel Sets',
      sup('Leeds', cat('Travel Gifts', 'Gift Sets') ) ],
     ['Utility Kits',
      sup('Leeds', cat('Luggage & Golf', 'Utility Kits') ) ],
     ['Travel Technology',
      sup('Leeds', cat('Technology', 'Travel') ),
      sup('LogoIncluded',
          cat('Solar Charger'),
          cat('Executive Kit'))],
    ] ],
 ['Housewares',
  [
   match('name', 'door knob'),
  ],[
     ['Boxes & Waterproof Containers',
      sup('Lanco', cat('Bags / Containers', 'Boxes / Waterproof Containers'))],
     ['BBQ & Picnic',
      [match('name', %w(grill bbq picnic)),
       sup('Leeds', cat('Outdoor Living', 'BBQ & Picnic') ),
       sup('Norwood',
           cat('HOUSEWARES', 'PICNIC2'),
           cat('OUTDOOR', 'PICNIC') ),
       exclude(sup('LogoIncluded', always)),
       sup('Logomark',
           cat('BBQ Sets'),
           cat('Picnic') )
      ]],
     ['Beverage & Bar',
      [sup('Leeds', cat('Housewares', 'Beverage & Bar') ),
       sup('Logomark', cat('Bar Accessories') )
      ],[
         ['Recycled Bar Sets',
          sup('Leeds', cat('EcoSmart', 'Beverage & Bar') ) ]
        ]],
     ['Conserve',
      [sup('Leeds', cat('Housewares', 'Conserve') ) ]],
     ['Decorations',
      [sup('Norwood', cat('HOUSEWARES', 'DECO') ) ]],
     ['Food Storage',
      [sup('Leeds', cat('Housewares', 'Food Storage') ),
       sup('Norwood', cat('HOUSEWARES', 'FOOD') ),]],
     ['Wine & Cheese Collection',
      [sup('Leeds', cat('Housewares', 'Wine & Cheese Collection') ),
       sup('Norwood', cat('HOUSEWARES', 'WINE') ),]],
     ['Kitchen',
      [match(%w(name description), 'kitchen'),
       match('name', ['measuring cup', 'measuring spoon', 'pizza cutter', 'spatula', 'basting', 'dishwasher', 'silicone glove', 'cream scoop', 'oven mitt', 'pot holder']),
       sup('Norwood', cat('HOUSEWARES', 'UTENSILS'))
      ],[
         ['Aprons',
          [match('name', 'apron')]],
         ['Thermometers',
          [match('name', 'thermometer', 1)]],
         ['Toasters',
          [match('name', 'toaster') ]],
        ]],
     ['Cutlery',
      [sup('Leeds', cat('Housewares', 'Cutlery') ) ]],
     ['Seasonal Housewares',
      [sup('Leeds', cat('Housewares', 'Seasonal') ) ]],
     ['Tabletop & Serving',
      [sup('Leeds', cat('Housewares', 'Tabletop & Serving') ) ]],
     ['Wine Collection',
      [sup('Leeds', cat('Housewares', 'Wine Collection') ) ]],
     ['Vases',
      [match('name', 'vase'),
       sup('Norwood', cat('AWARD', 'VASE') ) ] ],
     ['Ornaments',
      [sup('The Magnet Group', cat('Crystal', 'Ornaments') ) ] ],
    ] ],
 ['Health & Personal Care',
  [sup('Gemline',
       cat('Gifts', 'Fitness/Wellness') ),
   sup('Norwood',
            match('name', 'growth chart'), # Only 40253
       all(cat('HEALTH'),
           match('name', 'thermometer')), # Only 40014
       all(cat('HEALTH'),
           match('name', ['flu', 'CPR'])), # Only 400693, 50049
       cat('HEALTH', 'SPA') ),
   sup('High Caliber Line', cat('Healthy Living') ),
   sup('Prime Line',
       cat('Health Wellness'),
       cat('Personal Care')),
   sup('Hit Promotional Products', cat('Amenities') ),
   sup('Logomark', cat('Health and Fitness') )          
  ],[
     ['First Aid Kits',
      [match('name', 'first aid'),
       sup('Leeds',
           all(cat('Outdoor Living', 'Excursion'),
               match('name', 'first aid') ),
           cat('Safety & Auto', 'Personal Safety') ),
       sup('Lanco', cat('Health', 'First Aid Kit') ),
       sup('Norwood', cat('HEALTH', 'FIRSTAID') )]],
     ['Bandage Dispensers',
      [match('name' ,['bandage caddy', 'bandage dispenser', 'bandage case']),
       sup('Lanco', cat('Health', 'Bandage Dispenser') ),
       sup('Norwood', cat('HEALTH', 'BANDAGE') )]],
     ['Sanitizers',
      [match('name', ['hand cleaner', 'hand sanitizer']),
       sup('Lanco',
           cat('Hand Sanitizers', 'Hand Sanitizers'),
           cat('Candles / Bath / Body', 'Hand Sanitizers') ),
       sup('High Caliber Line', cat('Sanitizers') ),
       sup('Prime Line', cat('Hand Sanitizer') )
      ],[ ['Hand Sanitizers',
           [match('name', 'hand', 1)] ]
        ] ],
     ['Stain Removers',
      [match('name', 'stain remove'),
       sup('Lanco', cat('Travel / Personal Care', 'Stain Removers'))
      ] ],
     ['Pedometers',
      [match('name', ['pedometer', 'step-meter', 'step meter']),
       sup('Leeds',
           all(cat('Outdoor Living', 'Excursion'),
               match('name', 'pedometer') ),
           cat('Health & Wellness', 'Pedometers') ),
       sup('High Caliber Line', cat('Pedometer') ),
       sup('Lanco', cat('Travel / Personal Care', 'Pedometer') ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Pedometers') ),
       sup('Sweda', cat('Pedometers') )
      ] ],
     ['Fitness Sets',
      [all(match('name', %w(set kit), 1),
           match('name', %w(exercise fitness)) ),
       sup('Leeds', cat('Health, Safety & Auto', 'Fitness Sets') ) ]],
     ['Personal Wellness',
      [sup('Leeds', cat('Health & Wellness', 'Personal Wellness & Fitness') ) ]],
     ['Dental Products',
      [match('name', %w(floss toothbrush tooth\ brush toothpick))]],
     ['Pill Cases',
      [match(%w(name description), ['pill hold', 'pill case', 'pill box', 'pill tube', 'pill caddy']),
       sup('Lanco', cat('Health', 'Pill Cases') ),
       sup('Norwood', cat('HEALTH', 'PILLBOX') )]],
     ['Pill Cutters',
      [match('name', 'pill cut'),
       sup('Lanco', cat('Health', 'Pill Cutters') )]],
     ['Bug Repellant',
      [match('name', ['bug zapper', 'bug repellant']),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Bug Repellant') )
      ] ],
     ['Outlet Covers',
      [sup('Lanco', cat('Health', 'Outlet Cover') )]],
     ['Shoe Accessories',
      [match('name', %w(shoe callus)),
       sup('Lanco', cat('Travel / Personal Care', 'Shoe Items') ) ]],
     ['Soap',
      [match('name', 'soap') ] ],
     ['Wipes & Cleaning Cloths',
      [match('name', ['wipes', 'cleaning cloth', 'towelette']) ] ],
     ['Jump Rope',
      [match('name', 'jump rope') ] ],
     ['Fans',
      [match('name', ['mini fan', 'hand fan', 'personal fan']),
       sup('Lanco', cat('Travel / Personal Care', 'Fans') ),
       sup('High Caliber Line',
           all(cat('Toys & Games'),
               match('name', 'fan') ) ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Fans') ),
       sup('Sweda', cat('Unique', 'Fans') )
      ]],
     ['Mirrors',
      [match('name', 'mirror'),
       sup('Lanco', cat('Travel / Personal Care', 'Mirrors') ) ]],
     ['Lint Brushes',
      [match(%w(name description), ['lint brush', 'lint roller']),
       sup('Lanco', cat('Travel / Personal Care', 'Lint Brushes') ) ]],
     ['Brush & Combs',
      [sup('Lanco', cat('Travel / Personal Care', 'Brush & Combs') ) ]],
     ['Sewing Kits',
      [match('name', ['sewing kit', 'mending']),
       sup('Lanco', cat('Travel / Personal Care', 'Sewing Kits') ) ]],
     ['Dental Products',
      [sup('Lanco', cat('Travel / Personal Care', 'Dental Products') ) ]],
     ['Sun Kits',
      [sup('Lanco', cat('Sun / Outdoors / Sports', 'Sun Kits') ) ]],
     ['Lip Balm',
      [match('name', %w(lipbalm lip\ balm)),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Lipbalm') ) ]],
     ['Outdoor Kits',
      [sup('Lanco', cat('Sun / Outdoors / Sports', 'Outdoor Kits') ) ]],
     ['Sunblock',
      [match('name', %w(sunscreen sun\ screen sunblock sun\ block)),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Sunscreen') ),
       sup('Norwood', cat('HEALTH', 'SUN') ) ]],
     ['Lotions',
      [match('name', 'lotion') ] ],
     ['Manicure',
      [match('name', ['manicure', 'nail file', 'emery board', 'pedicure']) ]],

     ['Info Guide',
      [sup('Norwood', cat('HEALTH', 'INFOGUIDE')) ]],

    ] ],

 ['Personal Accessories',
  [
  ],[
     ['Umbrellas & Rainwear',
      [match('name', 'umbrella'),
       sup('Leeds', duplicate(['Umbrellas'], 'supplier_categories')),
       sup('Lanco', cat('Sun / Outdoors / Sports', 'Umbrellas') ),
       sup('Bullet Line', cat('Fitness & Recreation', 'Umbrellas') ),
       sup('Sweda', cat('Umbrellas') ),
      ],[
         ['London Fog',
          [sup('Sweda', cat('BRANDS', 'London Fog') ) ]],
        ] ],
     ['PDAs & Phone Holders',
      [match('name', ['phone holder', 'phone stand']),
       sup('Lanco', cat('Bags / Containers', 'PDA Holder') ),
       sup('LogoIncluded', cat('Phone Cases') ) ] ],
     ['Eyeglass Accessories',
      [],[
          ['Eyeglass Cases',
           [match('name', /((sun)|(eye)| )glass.+case/) ] ],
          ['Eyeglass Straps',
           [match('name', /((sun)|(eye)| )glass.+strap/) ] ],
          ['Eyeglass Clips',
           [match('name', /((sun)|(eye)| )glass.+clip/) ] ],
         ] ],
     ['Sun Glasses',
      [match('name', 'sunglasses'),
       exclude(match('name', 'case'))] ],
     ['Badge Holders',
      [match('name', %w(badge ident)),
       match('description', 'badge holder'),
       exclude(match('name', 'bag')),
       sup('Lanco', cat('Badge Holders / Ribbons', 'Badge Holders') ),
       sup('High Caliber Line',
           cat('Badge Holders'),
           cat('Office', 'Badge Holders')),
       sup('Norwood', cat('OFFICE', 'BADGE') ),
       sup('Bullet Line', cat('Key Tags & Badge Holders', 'Badge Holders') ),
       sup('Logomark', cat('Badge Holders') ),
       exclude(match('name', 'lanyard'))]],
     ['Lanyards',
      [match('name', 'lanyard'),
       sup('Lanco', cat('Badge Holders / Ribbons', 'Badge Holder Accessories') ),
       sup('High Caliber Line',
           cat('Lanyards'),
           cat('Lanyards', 'Econo Lanyards'))
      ],[
         ['Eco Friendly Lanyards',
          [sup('High Caliber Line', cat('Lanyards', 'Eco Friendly Lanyards') ) ] ]
        ] ],
     ['Dog Tags',
      [sup('Lanco', cat('Badge Holders / Ribbons', 'Dog Tags') )]],
     ['Carabiners',
      [match('name', 'carabiner'),
       sup('Lanco', cat('Carabiners / Key Chains', 'Carabiner') ),
       sup('Leeds', cat('Keychains, Keylights & Carabiners', 'Carabiners') ),
       sup('High Caliber Line', cat('Carabiners') ),
       sup('Bullet Line',
           cat('Key Tags & Badge Holders', 'Carabiners'),
           cat('Lighting', 'Carabiners') ),
       sup('The Magnet Group', cat('Innovations', 'Carabiners') )
      ]],
     ['Key Chains',
      [match(%w(name description), ['key chain', 'keychain', 'key holder', 'key tag', 'key ring']),
       sup('High Caliber Line',
           cat('Key Chains'),
           cat('Key Chains', 'Alcraft Key Chains')),
       sup('Prime Line', cat('Key Holders') ),
       sup('Lanco',
           cat('Carabiners / Key Chains', 'Keychains'),
           cat('Tools / Knives', 'Keychains') ),
       sup('Norwood', cat('AUTO', 'KEYCHAIN') ),
       sup('Leeds', cat('Keychains, Keylights & Carabiners', 'Keychains') ),
       sup('Bullet Line',
           cat('Stress Relievers', 'Stress Reliever Keychains'),
           cat('Key Tags & Badge Holders', 'Key Tags')),
       sup('Crown Products', cat('Key Chains') ),
       sup('Logomark', cat('Key Rings') ),
       sup('Sweda',
           cat('Key Tags'),
           cat('Keychains') ),
       sup('The Magnet Group',
           cat('Innovations', 'Keytags'),
           cat('Innovations', 'Keychains') )
      ],[
         ['Bottle Opener Key Chains',
          [match('name', 'opener', 1),
           sup('Bullet Line', cat('Key Tags & Badge Holders', 'Bottle Openers') ) ]],
         ['Key Chains with Light',
          [match('name', 'light', 1),
           match('name', /LED.+?light.+?key/i),
           exclude(match('name', 'limelight')),
           sup('Leeds', cat('Keychains, Keylights & Carabiners', 'Keylights') ),
           sup('Bullet Line', cat('Lighting', 'Key Lights') ),
           sup('The Magnet Group', cat('Innovations', 'Key Lights') )
          ] ],
         ['Flash Drive Key Chains',
          [sup('LogoIncluded', match(%w(name description), ['key chain', 'keychain', 'key holder']))]],
        ] ],
     ['Wallets',
      [match('name', %w(wallet checkbook)),
       match('description', ['travel wallet', 'leather organizer', 'passport jacket']),
       sup('Leeds',
           all(cat('Travel Gifts', 'Clocks & Wallets'),
               match('name', ['wallet', 'passport'])) ),
       sup('Gemline', cat('Business Accessories', 'Travel Wallets') ),               
      ]],
     ['Money Clips',
      [match('name', ['money clip', 'money band']),
       sup('Logomark', cat('Money Clips') )
      ] ],
     ['Wristbands',
      [match(%w(name description), [/wrist.*band/, 'bracelet']) ] ],
     ['Watches',
      [sup('Leeds',  ),
       sup('Logomark',
           cat('Classic Watches'),
           cat('Fashion Watches') ),
      ],[
         ['Cutter & Buck Watches',
          [sup('Leeds', cat('Watches', 'Cutter & Buck Watches') ) ]],
         ['Executive Watches',
          [sup('Leeds', cat('Watches', 'Executive') ),
           sup('Sweda', cat('Watches', 'Analog Executive') ), ]],
         ['Watch Gift Sets',
          [sup('Leeds', cat('Watches', 'Gift Sets') ) ]],
         ['Wenger Watches',
          [sup('Leeds', cat('Watches', 'Wenger Watches') ) ]],
         ['Sport Watches',
          [match('name', 'sport', 1),
           sup('Logomark', cat('Sport Watches') ),
           sup('Sweda',
               cat('Watches', 'Analog Sport'),
               cat('Watches', 'Digital') ),
          ] ],
        ] ],
     dup('Travel', 'Personal Travel'),
     ['Womens Accessories',
      [sup('Gemline', cat('Women`s', 'Travis & Wells')) ]],
    ] ],

 ['Recreation',
  [sup('Leeds', cat('Gusto', 'Explore') ),
   sup('High Caliber Line', cat('Sports and Recreation') ),
   sup('Bullet Line', cat('Fitness & Recreation', 'Summer & Outdoor Items')),
  ],[
     ['Binoculars & Telescopes',
      [match('name', %w(binocular telescope monocular)),
       sup('Leeds', cat('Outdoor Living', 'Binoculars') ),
       sup('High Caliber Line', cat('Binoculars') ),
       sup('Sweda', cat('Binoculars') )
      ] ],
     dup('Games & Toys', 'Outdoor Games'),
     dup('Health & Personal Care', 'First Aid Kits'),
     dup('Health & Personal Care', 'Pedometers'),     
     ['Compasses',
      [match('name', 'compass'),
       sup('Leeds',
           all(cat('Outdoor Living', 'Excursion'),
               match('name', 'compass') ) ) ]],
     ['Beach ware',
      [match('name',%w(beach)),
       match('name', 'towel', 1),
       sup('Leeds', cat('Towels', 'Beach Towels') )]],
     ['Golf',
      [match('name', 'golf'),
       sup('Leeds', cat('Recreation', 'Golf') ) ,
       sup('Norwood', cat('GOLF') ),
       sup('Crown Products', cat('Golf') ),
       sup('Logomark', cat('Golf Gifts' ) )
      ],[
         ['Ladies Golf',
          [sup('Norwood', cat('GOLF', 'LADIES') ) ] ],
         ['Golf Balls',
          [match('name', 'balls', 1),
           sup('Lanco', cat('Golf', 'Golf Balls') ),
           sup('Norwood', cat('GOLF', 'GOLFBALL') ) ] ],
         ['Golf Club',
          [sup('Norwood', cat('GOLF', 'GOLFCLUB') ) ] ],
        ['Golf Kits',
          [match('name', 'kit', 1),
           match('name', 'putter'),
           sup('Lanco', cat('Golf', 'Golf Kits') ),
           sup('Norwood', cat('GOLF', 'EVENT') )]],
         ['Golf Tags',
          [match('name', 'tag', 1),
           sup('Lanco', cat('Golf', 'Golf Tags') ) ]],
         ['Golf Towels',
          [match('name', 'towel', 1),
           sup('Lanco', cat('Golf', 'Golf Towels') ),
           sup('Leeds', cat('Towels', 'Golf Towels') )]],
         ['Tees, Ball Markers & Divot Tools',
          [match('name', ['tees', 'ball marker'], 1),
           match('name', 'divot'),
           sup('Leeds',
               all(cat('Luggage & Golf', 'Golf'),
                   match('name', 'green'))),
           sup('Lanco', cat('Golf', 'Tees, Markers & Divot Tools') ),
           sup('Norwood', cat('GOLF', 'TEE') )]],
        ] ],
     ['Kites',
      [match('name', 'kite')] ],
     ['Camping',
      [match('name', 'tent') ]],
     ['Outdoor Seating',
      [match('name', ['chair', 'recliner']),
       match(%w(name description), ['stadium seat', 'stadium cushion', 'stadium kushion', 'outdoor lounger', 'seat cushion', /chair.+fold/i]),
       all(match('name', %w(chair seat)), match('description', %w(outdoor beach sporting stadium))),
       exclude(match('name', 'stress reliever')),
       sup('Norwood', cat('OUTDOOR', 'CHAIRS') ),
       sup('Lanco',
           cat('Sun / Outdoors / Sports', 'Cushions'),
           cat('Sun / Outdoors / Sports', 'Seats') ) ] ],
     ['Excursion',
      [sup('Leeds', cat('Outdoor Living', 'Excursion') ) ] ],
    ] ],

 ['Stationery',
  [sup('Gemline',
       ['New Padfolios', 'Padfolios $10 - $20', 'Padfolios 20+', 'Padfolios Under $10', 'Closeout Padfolios'].collect do |name|
         cat('Padfolios', name)
       end),
   sup('Hit Promotional Products', cat('Portfolios & Jotters') ),
   sup('The Magnet Group', cat('Bag Factory', 'Stationery & Writing') )
  ],[
     ['Jotters',
      [match('name', 'notepad'),
       match('name', 'jotter'),
       sup('Leeds',
           cat('Stationery', 'Jotters'),
           cat('Stationery', 'Notebooks')),
       sup('Norwood', cat('MEETING', 'JOTTERS') ),
       sup('Prime Line',
           all(cat('Computer Bags / Portfolios'),
               match('name', 'pad') ) ),
       sup('Lanco',
           cat('Journals / Portfolios', 'Notebooks'),
           cat('Journals / Portfolios', 'Memo Pads')),
       sup('High Caliber Line',
           match('name', 'notebook') ),
       sup('Bic Graphics',
           match('supplier_num', /^((NC4P57)|(NC57(ECO)?)|(NPP?57))$/),
           exclude(match('name', 'notepad'))),
       sup('Sweda', cat('Stationery', 'Jotters') )
      ],[
         ['Recycled Jotters',
          [sup('Leeds',
               all(cat('EcoSmart', 'Jotters & Journals'),
                   match('name', %w(pad jotter))) ) ] ],
        ]],
     ['Journals',
      [match('name', 'journal'),
       sup('Leeds',
           cat('JournalBooks', 'Bound'),
           cat('JournalBooks', 'Spiral') ),
       sup('Lanco', cat('Journals / Portfolios', 'Journal Books') ),
       sup('Prime Line', cat('Notebooks | Journals') ),
       sup('Bullet Line', cat('Stationery', 'Notebooks') ),
       sup('Sweda', cat('Stationery', 'Journals & Notebooks') ),
      ],[
         ['Recycled Journals',
          [sup('Leeds',
               all(cat('EcoSmart', 'Jotters & Journals'),
                   match('name', 'journal')) ) ] ],
        ]],
     ['Padfolios & Writing Pads',
      [match('name', 'padfolio'),
       sup('Leeds', cat('Stationery', 'Padfolios & Writing Pads') ),
       sup('Gemline',
           cat('Padfolios', 'Writing Pads'),
           match('name', ['writing pad', 'tech organizer', 'e-organizer']) ),
       sup('Lanco', cat('Journals / Portfolios', 'Portfolios') ),
       sup('Norwood',
           cat('MEETING', 'PAD'),
           cat('MEETING', 'FOLDERS')),
       sup('Bullet Line', cat('Stationery', 'Portfolios') ),
       sup('Logomark', cat('Letter Padfolios' ) ),
       sup('Sweda', cat('Stationery', 'Portfolios') )
      ],[
         ['Jr. Padfolios',
          [match('name', 'jr', 1),
           sup('Norwood', cat('MEETING', 'JUNIORS') ),
           sup('Bic Graphics', match('supplier_num', 'SHAJ1') ),
           sup('Logomark',
               cat('Mini Padfolios'),
               cat('Junior Padfolios') )
          ] ],
         ['Kid Friendly Padfolios',
          [sup('Gemline', cat('Kid-friendly', 'Padfolios') ) ] ],
         ['Leather Padfolios',
          [sup('Gemline', cat('Padfolios', 'Leather') ),
          ]],
         ['Recycled Pads',
          [match(%w(name description), 'recycle', 1),
           sup('Leeds', cat('EcoSmart', 'Padfolios & Writing Pads') ) ]],
        ] ],
     ['Planners',
      [sup('Leeds', cat('Stationery', 'Planners') ) ]],
     ['Ringbinders',
      [match('name', ['ringfolio', 'ringbinder']),
       sup('Leeds', cat('Stationery', 'Ringbinders') ),
       sup('Gemline', cat('Padfolios', 'Ringbinders') )]],
     ['Postcards & Greeting Cards',
      [sup('The Magnet Group', cat('SmartLine') ) ] ],
    ] ],

 ['Tools',
  [sup('Leeds',
       cat('Tools & Lighters', 'Tools'),
       cat('Gusto', 'Construct') ),
   sup('PrimLine', cat('Tools') ),
   sup('Norwood', cat('AUTO', 'TOOLS') ),
   sup('High Caliber Line', cat('Tools') ),
   sup('Hit Promotional Products', cat('Carabiners, Tools, Lights & Keytags') ),
   sup('Crown Products',
       cat('Tools'),
       cat('Tools, Gifts') ),
   sup('Logomark', cat('Hand Tools') ),
   sup('Sweda', cat('Tools') ),
   sup('The Magnet Group', cat('Innovations', 'Tools') )
  ],[
     dup('Tools / Knives', 'Ice Scraper'),
     ['Bag Clips',
      [match('name', 'bag clip'),
       sup('Lanco', cat('Tools / Knives', 'Bag Clips') ),
       sup('Norwood',
           all(cat('HOUSEWARES', 'UTENSILS'),
               match('name', 'clip') ) ),
       sup('Bullet Line',
           all(cat('Desktop'),
               match('name', 'clip') ) )]],
     ['Bottle Openers',
      [match('name', 'bottle opener'),
       sup('High Caliber Line',
           cat('Bottle Openers'),
           match('description', 'bottle opener' )),
       sup('Lanco', cat('Tools / Knives', 'Bottle Opener') ),
       sup('Bullet Line', cat('Keytags & Badge Holders', 'Bottle Openers') ),
       sup('Logomark', cat('Bottle Openers') )
      ]],
     ['Jar Openers',
      [match('name', 'jar opener') ]],

     ['Flashlights',
      [match('name', /(^|\s+)LED(\s+|$)/),
       match(%w(name description), %w(flashlight fingerlight)),
       sup('High Caliber Line', cat('Flashlights') ),
       sup('Lanco', cat('Tools / Knives', 'Flashlights') ),
       sup('Prime Line', match('name', 'torch') ),
       sup('Norwood', cat('AUTO', 'FLASH') ),
       sup('Bullet Line', cat('Lighting', 'Flashlights') ),
       sup('Logomark', cat('Flash Lights') ),
       sup('Sweda',
           cat('Flashlights', 'Metal'),
           cat('Flashlights', 'Plastic') ),
       sup('The Magnet Group', cat('Innovations', 'Flashlights') ),
      ],[
         ['Emergency Flashlights',
          [sup('Leeds', cat('Flashlights', 'Emergency & Safety') ) ]],
         ['Everyday Flashlights',
          [sup('Leeds', cat('Flashlights', 'Everyday') ) ]],
         ['Dynamo Flashlights',
          [sup('Leeds', cat('Flashlights', 'Dynamo') ),
           sup('Sweda', cat('Flashlights', 'Dynamos') )
          ] ],
         ['LED Flashlights',
          [match('name', /(^|\s+)L\.?E\.?D\.?(\s+|$)/, 1) ]],
         ['Specialty Flashlights',
          [sup('Leeds', cat('Flashlights', 'Specialty') ) ]],
        ] ],
     ['Knives',
      [match(%w(name description), %w(knive knife cutter)),
       exclude(match(%w(name description), /Cutter.+Buck/i)),
       sup('Lanco', cat('Tools / Knives', 'Knives') ),
       sup('Norwood', cat('AUTO', 'KNIVES') ),
       sup('Bullet Line', cat('Tools', 'Knives') ),
       sup('Logomark', cat('Knives') )
      ],[
         ['Wenger Knives',
          [sup('Leeds', cat('Tools & Lighters', 'Wenger Knives') ) ]],
        ] ],
     ['Lighters',
      [match('name', /(^|\s)lighter/),
      ],[
         ['Zippo Lighters',
          [sup('Leeds', cat('Tools & Lighters', 'Zippo Lighters') )]],
         ['BIC Lighters',
          [sup('Bic Graphics',
               match('supplier_num', /^((J\d{2})|((MP)?LTR))$/) )]],
        ] ],
     ['Pliers',
      [match('name', 'pliers', 1)
      ] ],
     ['Screwdrivers',
      [match(%w(name description), %w(screwdriver screw\ driver)),
       sup('Lanco',
           all(cat('Tools / Knives', 'Screwdriver & Tool Set'),
               match('name', 'screwdriver') ) ) ]],
     ['Tape Measures',
      [match(%w(name description), 'tape measure'),
       sup('Lanco', cat('Tools / Knives', 'Tape Measure') ),
       sup('Norwood', cat('AUTO', 'MEASURE') ),
       sup('Bullet Line', cat('Tools', 'Tape Measures') ),
       sup('Logomark', cat('Tape Measures') )]],
     ['Tool Sets',
      [match('name', ['tool set', 'tool kit', 'gift set'], 1),
       sup('Leeds',
           all(cat('Tools & Lighters', 'Tools'),
               match('name', ['tool set', 'tool kit']) ) ),
       sup('Lanco',
           all(cat('Tools / Knives', 'Screwdriver & Tool Set'),
               match('name', 'set') ) ),
       sup('Gemline',
           all(cat('Gifts', 'Home Improvement'),
               match('name', %w(kit set)) ) ),
       sup('Logomark', cat('Tool Sets') )
      ]],
     ['Multi Tools',
      [match('name', 'multi-', 1),
       sup('Leeds',
           all(cat('Tools & Lighters', 'Tools'),
               match('name', 'multi-tool') ) ),
       sup('Lanco',
           all(cat('Tools / Knives', 'Screwdriver & Tool Set'),
               match('name', 'pocket tool')) ),
       sup('Bullet Line', cat('Tools', 'Multi-Function Tools') ),
      ],[
         ['Leatherman',
          [sup('Sweda', cat('BRANDS', 'Leatherman') ) ]],
        ] ],
     ['Locks',
      [match('name', ' lock') ]],
    ] ],

 ['Writing',
  [ sup('High Caliber Line', cat('Writing Instruments') ),
    sup('Norwood', cat('WRITE', 'PENCIL') ),
    sup('Hit Promotional Products', cat('Writing Instruments') ),
    sup('Crown Products', cat('Writing Instruments') ),
  ],[
     ['Highlighters',
      [match('name', 'highlighter', 1),
       match('description', ['hi-lighter', 'highlighters']),
       sup('High Caliber Line', cat('Writing Instruments', 'Highlighters, Markers and Acceso') ),
       sup('Lanco',
           cat('Writing Instruments', 'Highlighters'),
           cat('Office / Computer Essentials', 'Highlighters')),
       sup('Prime Line',
           match('name', ['tri-liter', 'bi-liter']) ),
       sup('Norwood',
           all(match('name', ['highlighter', 'combo writer']),
               cat('WRITE', 'PENCIL') ) ),
       sup('Bullet Line', cat('Writing Instruments', 'Highlighters') ),
       sup('Bic Graphics',
           cat('Writing Instruments', 'Highlighter'),
           match('supplier_num', /^((BL)|(MRGE))/) ),
       sup('Logomark', cat('Highlighters') ),
       sup('Sweda', cat('Writing Instruments', 'Highlighters') )
       ]],
     ['Markers',
      [match('name', 'marker', 1),
       sup('Bic Graphics',
           cat('Writing Instruments', 'Marker'),
           match('supplier_num', /^MRP[GR]$/) ),
     ]],
     ['Pencils',
      [match('name', 'pencil'),
       sup('Gemline', cat('Writing Instruments', 'Pencils') ),
       sup('Bic Graphics',
           cat('Writing Instruments', 'Pencil'),
           match('supplier_num', /(^BP)|(PMR)|(PEVECO)/) ),
       sup('Logomark', cat('Pencils') )
      ]],
     ['Pens',
      [match('name', /pens?($|\s)/i, 1),
       sup('Leeds', cat('Pens-Plastic', 'Value Pens & Highlighters') ),
       sup('Gemline',
           ['Pens $3-$5', 'Pens $5-$10', 'Pens 10+', 'Pens under $3'].collect do |name|
             cat('Writing Instruments', name)
           end),
       sup('High Caliber Line',
           cat('Writing Instruments', 'Pens'),
           cat('Writing Instruments', 'Executive Pens') ),
       sup('Lanco',
           cat('Writing Instruments', 'Stick Pens'),
           cat('Writing Instruments', 'USA Made Pens') ),
       sup('Prime Line',
           match('name', %w(pen writer)) ),
       sup('Norwood',
           match('name', 'syringe pen'), # only 40017
           cat('WRITE', 'GIFTPEN'),
           cat('WRITE', 'PEN50'),
           cat('WRITE', 'PEN150')),
       sup('Bullet Line', cat('Writing Instruments', 'Plastic Pens') ),
       sup('Sweda',
           cat('Writing Instruments', 'Plastic'),
           cat('Writing Instruments', 'Metal') ),
       sup('The Magnet Group', cat('Innovations', 'Pens') ),
      ],[
         ['Carabiner Pens',
          [match(%w(name description), 'carabiner', 1),
           sup('Logomark', cat('Carabiners') ),
          ] ],
         ['Light Up Pens',
          [match('name', /(^|\s)light/, 1),
           sup('Bullet Line', cat('Writing Instruments', 'Light-up Pens') ),
           sup('Logomark', cat('Light Pens') ),
           sup('Sweda', cat('Writing Instruments', 'Light-Up & Laser') )
          ]],
         ['Pen Gift Boxes',
          [match('name', ['gift box', 'pen box'], 1),
           sup('Bullet Line', cat('Writing Instruments', 'Gift Boxes for Pens') ) ] ],
         ['Branded Pens',
          [sup('Leeds', cat('Pens-Metal', 'Branded') ) ]],
         ['Multi Function Pens',
          [match('name', %w(usb laser), 1),
           sup('Leeds', cat('Pens-Metal', 'Multi-Function') ),
           sup('High Caliber Line', cat('Writing Instruments', 'Laser Pointers & Light Up') ),
           sup('Lanco', cat('Writing Instruments', 'Pens with Staple Remover') ),
           sup('Bic Graphics',
               match('supplier_num', /^((4C)|(4CL)|(B3)|(TWOS))$/) ),
           sup('Logomark', cat('Multi-Function Pens') )
          ]],
         ['Pen Sets',
          [sup('Leeds', cat('Pens-Metal', 'Gift Sets') ),
           sup('Gemline', cat('Writing Instruments', 'Pen Sets') ),
           sup('Logomark',
               cat('Pen Sets'),
               cat('Rollerball Ballpoint Sets') )]],
         ['Scripto Plastic Pens',
          [sup('Leeds', cat('Pens-Plastic', 'Scripto') ) ]],

         ['Click Pens',
          [match('name', 'click', 1),
           match('name', 'click pen'),
           match('description', 'plunger action'), # Hit
           sup('Prime Line',
               match('description', ['click action', 'click-action'])),
           sup('Gemline', cat('Writing Instruments', 'Clicks') ),
           sup('Lanco', cat('Writing Instruments', 'Click Pens') ),
           sup('Bic Graphics',
               match('supplier_num', [/^(DC)?MC/, /^((CS)|(TS)|(TWP)|(CL))/]))
          ]],
         ['Roller Ball Pens',
          [match('name', 'roller', 1),
           match('name', 'rollerball'),
           sup('Gemline',
               cat('Writing Instruments', 'Roller Balls'),
               cat('Writing Instruments', 'Roller Needle')),
           sup('Leeds', cat('Pens-Metal', 'Roller Ball') ),
           sup('Bic Graphics',
               cat('Writing Instruments', 'Rollerball'),
               match('supplier_num', /^((GR)|(T537R)|(XS)|(Z4)|(PLCCR))/) ),
           sup('Logomark',
               cat('Rollerball Pens'),
               cat('Rollerball Ballpoint Sets')) 
          ]],
         ['Ballpoint Pens',
          [match(%w(name description), 'ballpoint'),
           sup('Leeds', cat('Pens-Metal', 'Ballpoint') ),
           sup('Gemline', cat('Writing Instruments', 'Ballpoint') ),
           sup('Bic Graphics', cat('Writing Instruments', 'Ballpoint') ),
           sup('Logomark',
               cat('Ballpoint Pens'),
               cat('Rollerball Ballpoint Sets'))]],
         ['Two-Piece Stic Pens',
          [match('name', 'stick pen'),
           sup('Bic Graphics',
               match('supplier_num', [/^STYL/, /^RS/, /^BC/, 'ATS']) )
          ]],
         ['Gel Pens',
          [match('name', 'gel', 1),
           sup('Gemline', cat('Writing Instruments', 'Gel') ),
           sup('Bullet Line', cat('Writing Instruments', 'Gel Pens') ),
           sup('Bic Graphics',
               cat('Writing Instruments', 'Gel Pen'),
               match('supplier_num', 'GEL') ),
           sup('Sweda', cat('Writing Instruments', 'Gel') )
          ]],
         ['Metal Pens',
          [sup('Bullet Line',
               cat('Writing Instruments', 'Metal Pens'),
               cat('Writing Instruments', 'Metal Pen') )
          ], [
              ['Aluminum Pens',
               [match('material', 'Aluminum', 2)
               ] ],
              ['Brass Pens',
               [match('material', 'brass', 2)
               ] ],
              ['Stainless Steel Pens',
               [match('material', 'stainless', 2),
                sup('Gemline',
                         cat('Writing Instruments', 'Stainless') ) ] ],
              ['Gold Plated Pens',
               [match('description', /\d{2}K gold/i),]],
             ] ],
         ['Twist Pens',
          [match(%w(name description), 'twist', 1),
           sup('Prime Line',
               match('description', 'twist-action')),
           sup('Gemline', cat('Writing Instruments', 'Twists') ),
           sup('Lanco', cat('Writing Instruments', 'Twist Pens') )]],
         ['Recycled Pens',
          [match(%w(name description), 'recycle', 1),
           sup('Gemline', cat('Writing Instruments', 'Recycled') ),
           sup('Leeds', cat('EcoSmart', 'Pens')) ]],
         ['Specialty Pens',
          [sup('Lanco', cat('Writing Instruments', 'Specialty Pens') ) ]],
         ['Pen Holders & Cases',
          [sup('Lanco', cat('Writing Instruments', 'Pen Holder/Cases') ),
           sup('Norwood',
               all(match('name', %w(box pouch)),
                   cat('WRITE', 'GIFTPEN') ) )]],
         ['Eco Friendly Pens',
          [sup('High Caliber Line', cat('Writing Instruments', 'Eco Friendly Pens') ) ] ],
         ['Magnetic Pens',
          [match('name', 'magnet', 1),
           sup('The Magnet Group', cat('Innovations', 'Magnetic Pens') ) ] ],
        ] ],
    ] ],

 ['Other',
  [
  ],[
     ['Dog Collars & Leashes',
      [match('name', %w(dog\ collar leashe)),
       sup('High Caliber Line',
           cat('Dog Collars & Leashes'),
           cat('Lanyards', 'Dog Leashes Lanyards') ) ] ],
     ['Pet Accessories',
      [match('name', /Pets?($|\s)/i), ]],
     ['Light Ups',
      [sup('High Caliber Line', cat('Light Up') )
      ],[
         ['Light Up Pens',
          [match('name', 'pen', 1) ] ],
         ['Other Light Ups',
          [sup('High Caliber Line', cat('Light Up', 'Others') ) ]],
         ['Light Up Necklaces',
          [sup('High Caliber Line', cat('Light Necklaces') ) ]],
         ['Light Up Buttons',
          [match('name', 'button', 1)]],
        ]],
     ['Neoprene',
      [match('description', 'neoprene'),
       sup('High Caliber Line', cat('Neoprene') ) ]],
     ['Ribbons',
      sup('Lanco', cat('Badge Holders / Ribbons', 'Custom Imprinted Ribbons') ) ],
     ['Blankets',
      [match('name', 'blanket'),
       sup('Norwood', cat('OUTDOOR', 'BLANKETS') ),
       sup('Leeds', cat('Outdoor Living', 'Blankets') ),
       sup('Prime Line', cat('Blankets') ),
       sup('Logomark', cat('Blankets') ),
       sup('Sweda', cat('Blankets') ),
       sup('The Magnet Group', cat('Bag Factory', 'Blankets') )
      ] ],
     ['Combo Products',
      [sup('Prime Line', cat('Combos') ) ]],
     ['Whistles',
      [match('name', 'whistle') ]],
     ['Gardening',
      [match('name', 'garden') ]],
     ['Gift Tins',
      [sup('Logomark', cat('Gift Tins') ) ] ],
     ['Stopwatches & Timers',
      [sup('Sweda', cat('Stopwatches & Timers') ) ] ],
    ] ],

 ['Ecologically Friendly',
  [sup('High Caliber Line', cat('Eco Friendly Products') ),
   sup('Gemline',
       cat('Eco-Choice', 'New Eco-Choice'),
       cat('Eco-Choice', 'Under $10'),
       cat('Eco-Choice', '$10+')),
   sup('Logomark', cat('Sustainable') )

  ],[
     ['Organic',
      [sup('Gemline', cat('Eco-Choice', 'Organic')) ]],
     ['Growables',
      sup('Leeds',
          cat('Desktop', 'Growables'),
          cat('EcoSmart', 'Growables') ) ],
     ['Gusto',
      sup('Leeds', cat('Gusto', 'Conserve') ) ],
     ['Recycled',
      [sup('Gemline', cat('Eco-Choice', 'Recycled') ),
       sup('Logomark', cat('Recycles') )
      ],[
         dup('Bags', 'Backpacks', 'Recycled Backpacks'),
         dup('Bags', 'Business Bags', 'Recycled Business Bags'),
         dup('Bags', 'Duffel Bags', 'Recycled Duffel Bags'),
         dup('Bags', 'Tote Bags', 'Recycled & Organic Totes'),
         dup('Coolers', 'Recycled Coolers'),
         dup('Housewares', 'Beverage & Bar', 'Recycled Bar Sets'),
         dup('Drinkware', 'Recycled Drinkware'),
         dup('Stationery', 'Jotters', 'Recycled Jotters'),
         dup('Stationery', 'Journals', 'Recycled Journals'),
         dup('Stationery', 'Padfolios & Writing Pads', 'Recycled Pads'),
         dup('Writing', 'Pens', 'Recycled Pens'),
        ]],
    ] ],
     
]
  end
end
